### ISSUE TITLE
zed backend use lakes for default storage

### ISSUE THREAD

**Issue by alfred-landrum** [brimdata/zed#1085]
We should transition to use the Zed lake (aka "archivestore") space storage by default in zqd. We may keep the `filestore` kind available for compatibility with existing Brim spaces, but it could transition to read-only.

**Comment by alfred-landrum** [comment]
FYI, I briefly made this change in manager.go to use ArchiveStore by default, and only saw several unit test failures, `make test-system` didn't fail. When we make this change, we need to be sure to run the Brim integration tests before merging.

**Comment by philrz** [comment]
Verified in Zed commit 709c769.

What was once handled by `zqd` is now handled by `zed lake serve`. Starting this in an empty `$ZED_LAKE_ROOT` and using `zapi` to confirm the default behaviors, we see that what gets created is now all pool-based. 

```
$ zapi new -k ts -order desc foo
foo: pool created

$ zapi -p foo post *
posted 44.71MB in 7.926360845s

$ cat $ZED_LAKE_ROOT/pools.json | jq .
{
  "Version": 0,
  "Pools": [
    {
      "Version": 0,
      "Name": "foo",
      "ID": "1s21khAy8O9mxcBPVVHdoDQr2JQ",
      "Keys": [
        [
          "ts"
        ]
      ],
      "Order": "desc",
      "Treshold": 524288000
    }
  ],
  "Indices": null
}
```

Thanks @mattnibs!
