### ISSUE TITLE
zqd: Sunset filestores

### ISSUE THREAD

**Issue by mattnibs** [brimdata/zed#1151]
Once switch over to lakes as the default space for add functionality limit the utility of filestore:

1.  New file store spaces cannot be created (we might have to add a testing hook to create filestores to ensure existing filestores can be queried)
2.  Existing file store spaces cannot have data posted to it.

---

...at least, that was our plan back in August, 2020. Depending on how things look when we next want to cut GA releases, we might simply drop support for filestores entirely such that users would have to reimport data to new lakes. Let's use this issue as a reminder to make that decision.

**Comment by philrz** [comment]
This was addressed via #2629, as that "gets rid of the Manager used to manage spaces and instead uses a single instance of zed lake". The backend now has no knowledge of File Stores. The work tracked in brimdata/brimcap#58 and brimdata/brim#1567 represent the one remaining loose end, as these will help users migrate their data from legacy Spaces to Pools.

Thanks @mattnibs!
