### ISSUE TITLE
Single-file driver.MultiSource

### ISSUE THREAD

**Issue by henridf** [brimdata/zed#1154]
Implement a reader that presents a single file as a multiSource by creating independent "segment readers" that seek into the file and read a portion from there. This could be useful to allow zq to run faster over large files. 

If or when we do this, we'll also want to expose the input sort field and direction as zq flags (as originally proposed by @nwt), so that the flowgraph can be suitably parallelized.

**Comment by mccanne** [comment]
This went away with hazmat thank goodness.
