### ISSUE TITLE
"zar find" needs more detail in error response to say what was not found

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#1186]
This repro is with `zq` commit `2dfb278`.

I'd entered the following command line while working on #1125 and got the accompanying error message:

```
$ zar find -z -x TypoGoesHere 10.47.21.138 | zq -t -
item does not exist
```

As a user, I was confused because I'd made an accidental typo in the `-x` filename option so I thought the "does not exist" was a reference to not being able to find the target `10.47.21.138` in the index, _not_ a reference to a file not being found in the `.zar` directories.

This issue should not be confused with #1137, which tracks the separate topic of using the generic term `item`.

**Comment by philrz** [comment]
As of `zar` commit `ccbfade`, this issue is now masked by the SEGV described in #1419.

**Comment by mccanne** [comment]
zed lake deprecates zar
