### ISSUE TITLE
Bad "type" value in JSON typing config fails with confusing error

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#1202]
I was helping a community user that was creating a custom config for [JSON Type Definitions](https://github.com/brimsec/zq/blob/master/zeek/README.md) and we ran into an issue that caused some confusion.

Specifically, the user was trying to assign the ZNG `null` data type (as described in the [ZNG spec](https://github.com/brimsec/zq/blob/master/zng/docs/spec.md#5-primitive-types)) to a field that was always unset. Here's a working config that captures the essence of what we eventually settled on:

```
$ cat types.json 
{
  "descriptors": {
    "foo": [
      {
        "name": "_path",
        "type": "string"
      },
      {
        "name": "testfield",
        "type": "null"
      }
    ]
  },
  "rules": [
    {
      "descriptor": "foo",
      "name": "_path",
      "value": "bar"
    }
  ]
}

$ cat record.ndjson 
{"_path": "bar", "testfield": null}

$ zq -t -j types.json record.ndjson 
#0:record[_path:string,testfield:null]
0:[bar;-;]
```

The problem we hit was that on the first try, the user had not used quotes around `null` in the `types.json`:

```
$ cat types.json 
{
  "descriptors": {
    "foo": [
      {
        "name": "_path",
        "type": "string"
      },
      {
        "name": "testfield",
        "type": null
      }
    ]
  },
  "rules": [
    {
      "descriptor": "foo",
      "name": "_path",
      "value": "bar"
    }
  ]
}

$ zq -t -j types.json record.ndjson 
#0:record[_path:string,testfield:string]
0:[bar;-;]
```

As you can see, `zq` did not kick back any kind of error, but instead just didn't assign any typing config. I assume there's some kind of pass done through the typing config to make sure it's sane, so perhaps we could benefit from a check that the `"type"` values are all valid ZNG types. Along those lines, I see I can trigger the same failure with _any_ invalid `"type"` value.

```
$ cat types.json 
{
  "descriptors": {
    "foo": [
      {
        "name": "_path",
        "type": "string"
      },
      {
        "name": "testfield",
        "type": "ackpth"
      }
    ]
  },
  "rules": [
    {
      "descriptor": "foo",
      "name": "_path",
      "value": "bar"
    }
  ]
}

$ zq -v -t -j types.json record.ndjson 
#0:record[_path:string,testfield:string]
0:[bar;-;]
```

**Comment by philrz** [comment]
The situation here has been improved thanks to the change in #1377. Now as of `zq` commit `5245402` we get an error message were we didn't before:

```
$ cat types-fail.ndjson 
{
  "descriptors": {
    "foo": [
      {
        "name": "_path",
        "type": "string"
      },
      {
        "name": "testfield",
        "type": null
      }
    ]
  },
  "rules": [
    {
      "descriptor": "foo",
      "name": "_path",
      "value": "bar"
    }
  ]
}

$ cat record.ndjson 
{"_path": "bar", "testfield": null}

$ zq -t -j types-fail.ndjson record.ndjson 
record.ndjson: error decoding type "": zjson type field contains invalid type
```

This is likely to confuse users since they likely won't know what `zjson` is and the error didn't point to the problem area of the typing config. Therefore I'm going to hold this issue open so we can circle back and improve it at a later date, or maybe we'll chase it away entirely if we overhaul the approach to typed JSON ingest.

**Comment by nwt** [comment]
#2587 remove the typed NDJSON reader.

**Comment by philrz** [comment]
Also, here's an example with `zq` commit 8f7e395 that uses a Zed shaper in place of the previous `types.json` approach to achieve what the user was originally attempting:

```
$ cat shaper.zed 
type foo={_path:string,testfield:null}
put . = shape(foo)

$ cat record.ndjson 
{"_path": "bar", "testfield": null}

$ zq -z -I shaper.zed record.ndjson 
{_path:"bar",testfield:null (null)} (=foo)
```
