### ISSUE TITLE
Store mapping definitions in the archive

### ISSUE THREAD

**Issue by alfred-landrum** [brimdata/zed#1265]
Per #1183 , we should store the map definitions in the archive so that writers - either when ingesting new data, or rewriting existing data - can easily generate new map files if needed.

Edit: this is now specific for handling mapping files; index handling is in #1656 .

**Comment by philrz** [comment]
When this is addressed, verify and close #865.

**Comment by philrz** [comment]
The terminology such as "mapping" and other concepts referenced in in the design docs from this & linked issues are now out-of-date, so I'm closing this specific one as a "won't fix". Based on context, it seems like "mapping" was a placeholder term for what we're now calling "shapers", so I've opened a new issue #2695 where we can track further.
