### ISSUE TITLE
"zapi repl" should be fixed or removed

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#1343]
While verifying #1306 I tried the `repl` mode of `zapi`, as I'd never tried it in its days of being the default `zapi` mode. As of `zapi` commit `85c80a4`, it doesn't seem usable, as it appears to be trying to return binary ZNG the same way `zq` does, but I don't see options to change the output mode (`-t`, while mentioned in the error response, is not available).

```
$ zapi -s hello repl
hello> count() by _path
writing binary zng data to terminal; override with -B or use -t for text.
```

Also FWIW, the help text looks to be a copy of `zapi help new` at the moment.

```
$ zapi help repl
NAME
    repl - enter read-eval-print loop

...
DESCRIPTION
    The repl command takes a single argument and creates a new, empty space
    named as specified.
```

I don't get the impression users are reaching for this mode right now so it's surely not a priority. However, at some point we should clean this up so it works or just remove it. I'd be fine with removing, personally, since `zapi get` seems to cover us pretty well.

**Comment by mccanne** [comment]
The repl is gone thank goodness.
