### ISSUE TITLE
zar import performance and memory regression

### ISSUE THREAD

**Issue by alfred-landrum** [brimdata/zed#1366]
When I run `zar import` on current master (1a4d35d7c367356cc7d4ddf8ad6a0214d4abdc66) with a ~150MB zng file, the virtual & resident memory shoots up to gigabytes & stays high until the import completes, and completes in 8 seconds. With the same source data using zar from v0.20.0 completes in 2 seconds, and I don't see the same spike in memory usage.

**Comment by alfred-landrum** [comment]
Here's a memory profile of running zar import with master:
<img width="557" alt="Screen Shot 2020-09-25 at 08 49 55" src="https://user-images.githubusercontent.com/704945/94288329-242f6e00-ff0c-11ea-9cba-64d3fc160f09.png">

**Comment by mccanne** [comment]
Deprecated by zed lake
