### ISSUE TITLE
lvalues should handle dotted assignments

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#1410]
You should be able to say count() by foo.bar = column and put x.y=1. We are close to having general functionality but it's not quite wired up. We need a slightly more universal version of proc.ColumnBuild and proc.Cutter.

**Comment by philrz** [comment]
@mccanne: I was just familiarizing myself with the current state of this as of `zq` commit `0c6b642`. It looks like your example with the aggregation is already working ok:

```
$ zq -t 'count() by foo.bar=_path | sort -r' *
#0:record[foo:record[bar:string],count:uint64]
0:[[conn;]1021952;]
0:[[files;]162986;]
0:[[http;]144034;]
...
```

However, `put` isn't there yet.

```
$ echo '{"foo": "bar"}' | zq -t 'put x.y=1' -
x.y: put currently supports only top-level field assignemnts
```

**Comment by mccanne** [comment]
Closing as this all works now
