### ISSUE TITLE
Aggregate functions returning intermediate values in expressions

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#1425]
@mccanne made an observation back in March, 2020:

> It would be nice to be able to say:
> ```
> zq 'count() >= 300000 && count() < 400000'
> ```

That is,  the expression would evaluate to the aggregate function's result over all the input up to that record.

**Comment by mccanne** [comment]
This is related to the traverse project.

**Comment by mattnibs** [comment]
Completed with https://github.com/brimdata/zed/pull/3305
