### ISSUE TITLE
IndexPostRequest.Keys should use []Field instead of []string 

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#1463]
Not urgent, but the Keys argument in IndexPostRequest uses dotted strings for fields, which does not work when "." is in the field name. 

There coud be an api.Field type that is a []string or it could use field.Static from zq/pkg/field.

**Comment by philrz** [comment]
This will be important when we want to add the ability in Brim for users to create indexes.

**Comment by nwt** [comment]
This was done in #2931 by giving `lake/index.FieldRule.Fields` the type `field.List`.

https://github.com/brimdata/zed/blob/9e3960c4f5e052c65528fd90c57a71c397570074/lake/index/rule.go#L23-L28
