### ISSUE TITLE
.zar directories not shown in "zar ls -l"

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#1471]
Starting with `zar` commit `d8f8855` (associated with #1330, cc: @alfred-landrum), the command `zar ls -l` no longer shows the `.zar` directories. However, the `.zar` directories are still shown in regular `zar ls` output, so that's a mistmatch. Here's the transition:

```
$ zq -version
Version: v0.21.0-52-gc9d7736
$ rm -rf logs && zq work/zq-sample-data/zeek-default/*.gz | zar import -s 25MB - && zar ls -l
file:///Users/phil/logs/20180324/1521912990.158766.zng.zar
file:///Users/phil/logs/20180324/1521912507.399929.zng.zar
file:///Users/phil/logs/20180324/1521912075.114273.zng.zar
file:///Users/phil/logs/20180324/1521911772.980384.zng.zar

$ zq -version
Version: v0.21.0-53-gd8f8855
$ rm -rf logs && zq work/zq-sample-data/zeek-default/*.gz | zar import -s 25MB - && zar ls -l
[no output]

$ zar ls
file:///Users/phil/logs/zd/20180324/d-1inHlmph1TPe0mbE5kymZa3lNzJ.zng.zar/
file:///Users/phil/logs/zd/20180324/d-1inHlq6ObKtxKROJfcuyxxHFr4c.zng.zar/
file:///Users/phil/logs/zd/20180324/d-1inHlosnmgJrkW8Bzl9ShtNfPQz.zng.zar/
file:///Users/phil/logs/zd/20180324/d-1inHltiqRdSOz1D60Duo0UW6qyv.zng.zar/
```

**Comment by philrz** [comment]
A user that recently went through the `zar` README offered the following feedback, which underscores our need to address this issue:

> The behavior of `zar ls` and `zar ls -l` seems non-intuitive to me. Typically `ls -l` just provides more info about each entry, but in this case, `zar ls -l` outputs more total entries than `zar ls`  - it seems to be outputting information about the indexes?

**Comment by mccanne** [comment]
zed lake deprecates zar
