### ISSUE TITLE
change name of archive to lake

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#1482]
We agreed to change the name of package archive to lake and rename the `zar` command `zed lake` to better reflect that we're really building a log and analytics lake rather than a log archive.

**Comment by alfred-landrum** [comment]
This first PR renamed the archive package to lake: zq#2053

**Comment by philrz** [comment]
By walking through the steps in the [`zed lake` README](https://github.com/brimdata/zed/blob/main/docs/lake/README.md), I've verified with `zed` commit e113e89 that the operations formerly performed with the command called `zar` are now working via `zed lake`. I did find a couple glitches in the README that should be fixed when the changes in #2490 are merged.

Thanks @mccanne and @alfred-landrum!
