### ISSUE TITLE
partials naming and decomposable interface

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#1495]
I found the naming convention for decomposable aggregations a little confusing because I read the `*Part` pattern as the A-part and the B-part rather than, e.g., `ConsumePart` implying it is consuming a sequence of partial results.

I propose we call partial results "partials" and rename `*Part` as `*Partials`.  Also, the groupby booleans might be `PartialsIn` and `PartialsOut`,

Also, I'm not sure it's explained anywhere that we use the same field name for the partial results as the final results.  Maybe this is obvious but it wasn't to me.  Also, there should be an explicit comment (probably on reducer.Decomposable interface) that a reducer becomes a decomposable simply by implementing this interface and the compiler and optimizer check for the existence of this interface in making optimization decisions.

**Comment by mccanne** [comment]
Maybe reducer interface method  for Reducer and Decomposable could be `WriteValue()` and `WritePartial()`...?

**Comment by henridf** [comment]
This all sounds good to me. I used "partials" terminology in boom and elsewhere and I agree that the "Part" names don't work as well.

**Comment by mccanne** [comment]
This was done a while ago
