### ISSUE TITLE
ZQL syntax for enum

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#1498]
As discussed in #1314, at the moment (`zq` commit `18045ab`), references to fields of type `enum` in expressions resolve to their _underlying_ value. Example:

```
$ zq -version
Version: v0.22.0-57-g18045ab

$ cat enum.tzng 
#0:record[e:enum[int32,foo:[1],bar:[2],baz:[4]]]
0:[0;]
0:[1;]
0:[2;]

$ zq -t "put s=e:string, v=e+1" enum.tzng 
#0:record[e:enum[int32,foo:[1],bar:[2],baz:[4]],s:string,v:int64]
0:[0;foo;2;]
0:[1;bar;3;]
0:[2;baz;5;]
```

However, there's not yet a way to operate with the _enumerated_ values when that's desired, such as in search terms, e.g.:

```
$ zq -t 'e="foo"' enum.tzng 
[no output]
```

We've discussed introducing ZQL syntax so both are possible. One proposal has been to do something like [Java's `valueOf()`](https://www.tutorialspoint.com/java/lang/enum_valueof.htm) for working with the underlying value while allowing the enumerated value to be matched against strings in search terms.

**Comment by mccanne** [comment]
We removed values from enums to simplify as is the convention in Avro.
