### ISSUE TITLE
Disambiguate equality from assignment in ZQL

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#1509]
The following example is run with `zq` commit `032d9c5` and the [zq-sample-data](https://github.com/brimsec/zq-sample-data).

Let's say you want a count of flows in which the source port and destination port were the same. The following works in ZQL:

```
~/work/zq-sample-data/zeek-default$ zq -f table '_path=conn | count() by talking_to_same_port=id.orig_p=id.resp_p,id.orig_p,id.resp_p | filter talking_to_same_port=true | sort -r' *
TALKING_TO_SAME_PORT ID.ORIG_P ID.RESP_P COUNT
T                    3         3         176
T                    123       123       134
T                    137       137       31
T                    60004     60004     11
T                    60008     60008     9
```

However, the portion `talking_to_same_port=id.orig_p=id.resp_p` is somewhat confusing. The first `=` is being used for assignment (populating the field named `talking_to_same_port` with a result), while the second `=` is being used to test for equality (comparing the contents of the fields named `id.orig_p` and `id.resp_p` to generate the boolean value that is ultimately assigned to `talking_to_same_port`).

In some languages `==` is used to test for strict equality, which would leave `=` available to be used for assignment. In other languages `:=` is used for assignment, which would free up `=` to be used for equality.

In a group discussion we debated between these options. It seems the choice we make largely depends on the expectations of the user. Users familiar with common search tools and SQL are likely accustomed to `=` being used for equality. Meanwhile, users that have programming experience (e.g. Python, which is certainly very common among data scientists) are accustomed to `==` being used for equality. It seems if we settled on just one approach in order to make the experience familiar for one class of user, that may present a learning curve for the other class of user.

One proposal advocates allowing the syntax shown above to still work the way it does now where the user can always type `=` and the parser will use context to determine what it does, but also offer synonyms such as `==` for equality and/or `:=` for assignment if a user wants to write ZQL that more clearly communicates intent.

**Comment by mccanne** [comment]
This was decided and done.  `==` for comparison, `:=` for dataflow data mutation, and `=` for const/var declarations.
