### ISSUE TITLE
finalize the tzng format

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#1566]
Now that the binary zng format is in beta, it's time to apply experience and lessons learned to make one last round of improvements the tzng (text) version of zng.

The observations are:
* parsing performance is not all that important as binary zng is used for production use cases and tzng has turned out mostly for use as a human readable form of zng and in tests and debug
* the use of semi-colon-terminated elements in values and comma-separated elements in types is dissonant and has created unnecessary complexity in the implementation (e.g., in terms of different escaping rules for comma vs semi-colon),
* the lack of flexible whitespace between elements prohibits pretty printing,
* the value representation for text, csv, tzng, and zeek formats creates complexity that could be unified with some simplifications, and
* like zng, tzng streams should be concatenate-able but they currently are not because type redefinitions cause errors.

The proposal here is as follows.

FIrst, we will change the tzng value representation to use comma separation instead of semi-colon termination.  This will allow us to unify the escaping rules for the tzng type syntax and value syntax where enum values are embedded in tzng types and field names in record types can be an arbitrary string (in this case ":" needs to be escaped).  We will also allow whitespace between comma-separated elements requiring the first character of an element to be escaped when it is whitespace. 

Next, we considered adding an "#eos" directive to allow for concatenation of tzng files but this is ugly and seems out of place if it is required and would be needed to make this work.  A better approach is to simply allow the redefinition of the type tags in a tzng stream so that when they are encountered instead of flagging an error.  This makes sense when you realize that type tags are a bit different than the underlying zng type ID mechanism, which would otherwise be burdensome to translate 1-to-1 to text format.

Third, we will drop support for zeek tsv output format in zq so that we can have a single method on the zng types that format a value in a consistent way for csv, text, table, and tzng formats.  Note that csv uses comma-separation too (of course!) so it need not be special-cased differently from tzng.  Also, since the first character of a value must be escaped if it's whitespace (and in particular a tab), then tab separated forms of text and table are also covered with this one approach.

Finally, we will take advantage of the whitespace robustness in the first change to create a pretty printer that outputs appropriate whitespace to make tzng be easier to read.

**Comment by mccanne** [comment]
Looks like we will probably deprecate tzng.  See issue #1678.

Woohoo!

**Comment by philrz** [comment]
Per @mccanne's comment above, the current plan-of-record is to morph TZNG into a write-only "assembler"-style representation of TZNG and phase out TZNG as we knew it.

**Comment by mccanne** [comment]
This is complete.
