### ISSUE TITLE
"count() by ." produces "tzng syntax error" on more than 1000000 events

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#1570]
I stumbled onto this one quite by accident. It's not based on a real use case. Rather, I made a mistake in my ZQL, then after seeing the error message that was produced, I sensed that maybe this might point to some other underlying bug. Repro is with `zq` commit `31da57d7`.

Using the [Zeek TSV zq-sample-data](https://github.com/brimsec/zq-sample-data/tree/master/zeek-default):

```
~/work/zq-sample-data/zeek-default$ zq -version
Version: v0.22.0-99-g31da57d7

~/work/zq-sample-data/zeek-default$ zq -t 'count() by .' * > /dev/null
tzng syntax error
```

I narrowed the repro down to a magic number of 1000000.

```
~/work/zq-sample-data/zeek-default$ zq -t 'head 1000000 | count() by .' * > /dev/null
[no error... finishes fine!]

~/work/zq-sample-data/zeek-default$ zq -t 'head 1000001 | count() by .' * > /dev/null
tzng syntax error
```

As mentioned, this was found by accident. What I _meant_ to be doing was `zq -t 'count() by typeof(.)' *`, which works fine. I have no idea if `count() by .` even makes sense, but now that I see an error, I can't un-see it. 😄

**Comment by mccanne** [comment]
Confirmed no error anymore with
```
zq "count() by this" zed-sample-data/zeek-default/* > /dev/null
```
