### ISSUE TITLE
handle casts using an alias type

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#1572]
Casts with aliases should be allowed.  An alias cast needs to know alias binding at runtime in order to build the cast object.   This is straightforward as long as the type context is available.

**Comment by henridf** [comment]
There might be some ambiguity to resolve, e.g. if you define an alias `abs`, then is `abs(field)` an alias cast or the function `abs()`?

**Comment by philrz** [comment]
In a discussion with @mccanne he indicated that this may have been fixed as part of a PR @henridf merged recently. He intends to confirm that and close/update this one as appropriate.

**Comment by mccanne** [comment]
We should also add simple logic to the cast expr to nop if the types are already the same and just swap type pointer if a typedef with the same underlying type.

**Comment by mccanne** [comment]
This will be easy to do with structured errors because you could simply say....
```
error<complicated structure>(value)
```
We need to make sure the grammar can handle this.

**Comment by mccanne** [comment]
Closing as we decided the current syntax and functionality of...
```
cast(val, <foo>)
cast(val, error<complicated structure>)
```
works just ifne
