### ISSUE TITLE
add running functions and integrate with stateful functions

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#1768]
This issue is to create running aggregation functions, which can be created from reducers with a simple wrapper around reducer that implements function.Function.  No change is required to the grammar as we simply look for function calls that have the name of an aggregator.  We need to make sure the aggregator and function name spaces are disjoint.

Given this, we need to generalize how stateful functions like pick and cut get compiled and invoked as well as how these new stateful, running aggregations get created in compiler/expr.go

**Comment by philrz** [comment]
Thanks for spotting @jameskerr. Migrated!

**Comment by mccanne** [comment]
This is related to #1425

**Comment by mattnibs** [comment]
Resolved with https://github.com/brimdata/zed/pull/3305
