### ISSUE TITLE
zq not emitting records for slow, low volume stdin streams

### ISSUE THREAD

**Issue by mattnibs** [brimdata/zed#1796]
If I am reading into zq from say stdin from a stream with data arriving slowly, I would expect zq to process records as they arrive. However, our implementation of zbuf.Scanner only releases batches when they accumulate to a variable Size (100 by default). I think Scanners should behave similar to io.Reader- it only blocks when called when it has no data to return when, otherwise it returns what data it has.

Example:
```bash
$ cat << EOF > data.ndjson
{ "line": "one" }
{ "line": "two" }
EOF
$ tail -f data.ndjson | zq -i ndjson -t -
```

The above will not emit anything and just sit around waiting till it gets to 100 records.

**Comment by nwt** [comment]
The -unbuffered flag added in #4320 takes care of this.
