### ISSUE TITLE
zq runtime sensitive to SequentialProc layout

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#1809]
Except for FilterProc, the zq runtime cannot reliably handle single-node procs that are lifted out of SequentialProc,
e.g., 
```
{
    "op": "SequentialProc",
    "procs": [
        {
            "fields": [
                {
                    "lhs": {
                        "op": "RootRecord"
                    },
                    "op": "BinaryExpr",
                    "operator": ".",
                    "rhs": {
                        "name": "foo",
                        "op": "Identifier"
                    }
                }
            ],
            "nullsfirst": false,
            "op": "SortProc",
            "sortdir": 1
        }
    ]
}
```
vs
```
{
    "op": "SortProc",
    "fields": [
        {
            "lhs": {
                "op": "RootRecord"
            },
            "op": "BinaryExpr",
            "operator": ".",
            "rhs": {
               "name": "foo",
                "op": "Identifier"
            }
        }
    ],
    "nullsfirst": false,
    "sortdir": 1
}
```
The compiler handles this just fine but the optimizer and lots of tests break.  As we do more AST transformations and optimizations, it seems like a bad convention to require every single-node proc to be wrapped in a sequential proc of length 1.

**Comment by henridf** [comment]
I agree we should handle non-wrapped single procs. This is probably a case of overfitting, e.g. given that the grammar always (?) wrapped single procs into a SequentialProc, a bunch of compiler-related stuff was written with that behavior in mind.

**Comment by mccanne** [comment]
This is not important now as the AST is longer part of the API.
