### ISSUE TITLE
zngio NewWriter should have compression by default

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#1812]
When using package zq externally, it would be nice if you could create zio Writers (and Readers) with all the best options so you don't have to worry about ReaderOpts and WriterOpts.  For example, zng compression is on by default in zq because sets the flag in WriterOpts but if you create a NewWriter as a dev user of zngio with WriterOpts{}, compressions is turned off.

We could have a pattern of NewWriter() / NewWriterWithOptions etc and use the latter internally but make available the former as a more common external use case.

**Comment by nwt** [comment]
#3966 implements the `NewWriter`/`NewWriterWithOpts` pattern.

(We already have `NewReader`/`NewReaderWithOpts`.)
