### ISSUE TITLE
improve ZSON syntax for map values

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#1824]
Per @nwt 's suggestion, map values she be encoded as follows:
```
|{ <key> : <value> , ... }|
```

**Comment by philrz** [comment]
Verified in Zed commit c5e51f0.

In brief, the former map syntax looked like:

```
$ zq -version
Version: v0.30.0-39-ge72fe38b

$ zq -z /tmp/map.zng 
{m:|{{"a",1(int32)},{"b",2(int32)},{"c",3(int32)}}|}
```

The newer map syntax:

```
$ zq -version
Version: v0.30.0-45-gc5e51f05

$ zq -z /tmp/map.zng 
{m:|{"a":1(int32),"b":2(int32),"c":3(int32)}|}
```

The [ZSON spec](https://github.com/brimdata/zed/blob/main/docs/formats/zson.md#346-map-value) has been updated as well.

Thanks @nwt!
