### ISSUE TITLE
Shorthand syntax for multiple exclusions/inclusions

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#1891]
A community user asked if we could offer a shorthand query syntax to exclude all traffic involving one of several source IP addresses, suggesting the syntax `src_ip not [ip1, ip2, ip3, ip4]`. The user described wanting to do this for port fields as well. In follow-on discussion, we established the main motivation of the suggestion is eliminating the need to repeatedly type operators like `or` or `!=` as is necessary to achieve this logic with current syntax. They suggested that including an additional operator before the list (such as `in`) would seem reasonable.

**Comment by mccanne** [comment]
This can be done as follows:
```
% cat in.zson
{addr:10.0.0.1}
{addr:10.0.0.2}
{addr:10.0.0.3}
{addr:10.0.0.4}
% zq "not addr in [10.0.0.2,10.0.0.3]" in.zson
{addr:10.0.0.1}
{addr:10.0.0.4}
```
