### ISSUE TITLE
Make "zapi post -z" behavior consistent with zq

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#1913]
In verification notes at https://github.com/brimsec/zq/issues/1833#issuecomment-752278326, I pointed out how as of `zqd` commit `4dff9e9` the `-z` option on a `zapi post` currently expects Z whereas `zq -z` expects a filename that contains Z, and this functional mismatch tripped me up a bit as a user. @henridf and I discussed this offline and we agreed we should make it consistent. The current proposal:

1. `zapi post -z <file.zs> <filename>` would take the approach similar to `zq -z`, applying the Z in `<file.zs>` while posting the contents of `<filename>` for import. The use of a file is great for when these shaper configs become complex, when users want to keep them under revision control, etc.

2. `zapi post <z expression> <filename>` would take the approach similar to traditional `zq` query execution command lines, applying the Z in `<z expression>` while posting the contents of `<filename>` for import. The quick invocation of Z right there in the command line would be great for "quick & dirty" exercises, such as when the user just wants to apply data typing to a couple fields and is otherwise happy with default treatments.

**Comment by mccanne** [comment]
No longer relevant wrt lake API
