### ISSUE TITLE
Reject inappropriate flowgraphs in Z ingest scripts

### ISSUE THREAD

**Issue by henridf** [brimdata/zed#1924]
With #1833, a user can send a script to process data upon ingest. We should think through what types of processing are ok for ingest and add a semantic check that rejects those that aren't. 

For example, `tail 1` or `count() by uid` on ingest is probably not what a user wants.  A more subtle (and more likely to come up) would be the use of  `* | fuse()`: on a long-running ingest job, this would spill and exceed the node's disk space, not to mention that no data would appear until the end of ingest.

Maybe as a first pass we can simply distinguish between  streaming procs ( `put`, `cut`, `every-groupby`, `rename`, ...) vs batch procs (`sort`, `groupby`, `fuse`) and reject the latter.

**Comment by mccanne** [comment]
This is no longer relevant and shaping is not part of the load API.  Instead, agents will either shape themselves or load data into a staging pool and shape it within the lake.
