### ISSUE TITLE
Misleading compiler error message with bad cut

### ISSUE THREAD

**Issue by henridf** [brimdata/zed#1933]
The problem here is the `a+b` expression being passed to cut, but the error message refers to the LHS of an unspecified assignment.

```
$ echo '' | zq -t "put a = cut(a+b)" -
rhs of assigment expression: lhs of assigment expression: invalid expression on lhs of assignment
```

**Comment by henridf** [comment]
(On thinking this over, this might be best addressed in the forthcoming semantic pass).

**Comment by henridf** [comment]
Another one: 

```
$ echo '' | zq -f zson "put 21+1 =a" -
assigment name could not be inferred from rhs expressioin
```

**Comment by henridf** [comment]
Also:
```
$ echo '' | zq -f zson "cut b=boo+1" -
cut: no record found with columns <not a field>
```

**Comment by mccanne** [comment]
Cut is no longer available as a function and all of this other stuff is now basically fixed.  Closing.
