### ISSUE TITLE
add static tsdir configuration to zar metadata file

### ISSUE THREAD

**Issue by alfred-landrum** [brimdata/zed#1950]

**Comment by alfred-landrum** [comment]
The current archive code is based on a static `tsDir` range of 24 hours. We should put this value in the `metadata.json` file, and alter the code to fail to open an archive if it reads a different value. This will ensure forward compatibility & better error reporting if we change how the `tsDir` logic works.

**Comment by philrz** [comment]
@mccanne says this is becoming obsolete by his work to make keys generic in lakes, so closing this one.
