### ISSUE TITLE
zqd archivestore: status code 502 error

### ISSUE THREAD

**Issue by mattnibs** [brimdata/zed#1989]
We've been seeing this error periodically in the zapi tests for master continuous delivery tests (e.g. https://github.com/brimsec/zq/runs/1723942257?check_suite_focus=true)

The test fails with an exit code 1. Combing through the log artifacts of the test run, there's this curious warning message:

```
{"level":"warn","ts":1611002727.443269,"logger":"core","msg":"Error writing response","personality":"all","request_id":"64","error":"status code 502: "}
```

In the next log line the same request "64" exits with status code 200:

```
{"level":"info","ts":1611002727.4433365,"logger":"http.access","msg":"Request completed","request_id":"64","host":"localhost:9867","method":"POST","proto":"HTTP/1.1","remote_addr":"127.0.0.1:43522","request_content_length":349,"url":"/worker/rootsearch?format=zng","elapsed":2.102102447,"response_content_length":988,"status_code":200}
```

The success status code of the http response doesn't mean anything really- the success status code is generated at the start of a search request and does not reflect if an error occurred during the search.

Still not sure where the error is coming from. A good first might be to enable stack traces on warning log messages and above. Would also be nice to have the request_id persisted between root->worker requests.

**Comment by mattnibs** [comment]
I am guessing this is related- at the same time of this bug we also see an error "write: broken pipe" in the log for a worker:

```
{"level":"warn","ts":1611002727.4493227,"logger":"core","msg":"Error writing response","personality":"worker","request_id":"56","error":"write tcp 127.0.0.1:9867->127.0.0.1:42678: write: broken pipe"}
```

**Comment by mccanne** [comment]
Closing as zqd archivestore no longer exists.
