### ISSUE TITLE
Proposal: fully self-describing ZSON

### ISSUE THREAD

**Issue by henridf** [brimdata/zed#2051]
### Proposal: fully implied ZSON 

Currently, a ZSON stream is stateful in that each record potentially refers to type-definitions that were introduced by preceding records. This reflects the ZNG format, but means that ZSON is not readily human-understandable (other than the first record of a file). It also means that a newline-delimited ZSON is not amenable to the kinds of shell processing that one might expect of a text-based format. For example, cutting a ZSON file into two files (such as with the `split` UNIX utility) would result in one file that is invalid ZSON. Likewise with `head`, `tail`, and others.

To address this, the proposal here is to add a flag to zq such that it outputs ZSON that is "fully self-describing", meaning that each record in a ZSON stream is standalone and self-describing.

For context, note that this is already done for primitive types. As illustrated below, leaves are only decorated when their type is not implied by the literal.

```
echo '{a: 1.1.1.1, b: 1, c: 1 ( int8 )}' | zq -pretty=0 -i zson -f zson  -
{a:1.1.1.1,b:1,c:1 (int8)} (=0)
```

There are different ways to make a record fully implied. For example, the following three ZSON records are each fully implied, and each represent the same record value.

```
{a: {a:1 (int8) } }
{a: {a:1} ({a:int8}) }
{a: {a:1} } ({a: {a:int8}})
```

In this proposal, the fully implied mode always decorates at the lowest level possible (`{a: {a:1 (int8) } }` in the example above). This is easier to read, with the annotation close to the literal it is annotating.

This doesn't mean however that there would never be record type decorations. Specifically, in cases where a complex value is null, its shape cannot be inferred and so a record type decoration is needed. For example this:

```
#0:record[r:record[x:int64,y:int64]]
0:[[1;2;]]
0:[-;]
```
would be 
```
{r:{x:1,y:2}} // no decoration needed
{r:null ({x:int32,y:int32}) }
```
in fully-implied ZSON. 

Of course, this change will tend to make the ZSON output a bit larger, but as has been stated elsewhere, ZSON is for users and ZNG is for performance.

**Comment by henridf** [comment]
Note that this issue is a bigger change (hence "proposal") than it's smaller friend https://github.com/brimsec/zq/issues/2118, which per @mccanne we should do for sure.

**Comment by mccanne** [comment]
What if you just made this be ZSON?  Then you only have typedefs for named types.
Then type contexts and streaming typedefs are explained in ZNG (instead of ZSON) as an efficient mechanism for not having to determine a ZSON's values type (with lots of parsing and string to type lookups) when parsing each record.

This would make ZSON more approachable overall and easier to explain.

Nice work here!

**Comment by mccanne** [comment]
This has been done and the `-persist` flag was added to zq to allow named typedefs to persist across records for less noisy output.
