### ISSUE TITLE
Creation of null values when a field isn't present

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#2066]
In a team discussion on 2021-02-02, we started out by discussing the state of the Activity Overview table as it exists in GA Brim tagged `v0.23.0`. As it exists currently, after importing a pcap, it would show only Zeek events and not include the Suricata alerts.

![image](https://user-images.githubusercontent.com/5934157/106836433-060e1300-664e-11eb-90ed-2d37ece3f47d.png)

However, a community user recently [asked on Slack](https://brimsec.slack.com/archives/CTT24051C/p1612047900012400) about how they could go about including the Suricata alerts in the same table and be able to still use "Pivot to logs" when necessary to see the individual events for a particular counted row.

As @mccanne pointed out, most other systems address this as an ETL problem, such as if we'd renamed the `event_type` field in the Suricata events to `_path` as the logs were being imported and hence maintain the simple `count() by _path`. While this is technically feasible and is something we intend to enable through "Z shaper" functionality, we'd also like to know users have the flexibility in Z expressions to make this possible at query time even if the logs are still in their original native form.

One approach a user might try that won't work is `count() by _path,event_type | sort -r`. This would return no results because this `by` clause would require a field to have a value for `_path` _and_ for `event_type` in order to be counted. However, the current default schema for Zeek include only `_path`, and for Suricata only `event_type` is present.

@mccanne proposed the idea of a new function, for which we'll assign a placeholder name `nullify`. The syntax to achieve the query above could therefore look something like:

```
count() by _path=nullify(_path),event_type=nullify(event_type) | sort -r
```

Now all Zeek and Suricata records would always have both `_path` and `event_type` fields present before the aggregate function operates on them, but the Zeek ones would have an `event_type` value of `null` and the Suricata ones would have a `_path` of `null`.

Once this allows the creation of the table, it's still TBD whether we could make "Pivot to logs" in Brim smart enough to adjust the query to isolate the intended events. That subject is discussed separately at https://github.com/brimsec/brim/issues/1420.

**Comment by mccanne** [comment]
Closing this as error("missing") now shows up for columns not present.

**Comment by philrz** [comment]
I was curious to see this one for myself, so I fired up a Brim at commit `76ec25b` which uses Zed commit ba042cf. Revisiting the query described above that previously returned no data, the "missing" errors do indeed now populate the columns where appropriate and hence an output table is shown where none was previously.

![](https://user-images.githubusercontent.com/5934157/147592610-bbd49239-61da-450f-bcf7-0927e275db2c.png)

However, brimdata/brim#1420 is still relevant as noted previously, since the right-click "Pivot to logs" doesn't currently seem to know how to handle these error values. For instance, attempting this on the "conn" records:

![](https://user-images.githubusercontent.com/5934157/147593008-26367a65-9b27-48cb-9a6b-28e1cc39c44e.png)
