### ISSUE TITLE
Normalize order of union types

### ISSUE THREAD

**Issue by henridf** [brimdata/zed#2145]
Union types are currently order sensitive, meaning that `union[float64,bool]` and `union[bool,float64]` are different types. We should make those types be the same.

**Comment by nwt** [comment]
Looks like `expr/agg/ztests/fuse-container.yaml` and `expr/agg/ztests/fuse-dup.yaml` are flaky because of this.

**Comment by mccanne** [comment]
@nwt had a really good suggestion to define a total order on the type system that would of course work recursively for complex types.   This makes it also easy to check for dup types since the types would have to be strictly increasing (or decreasing), e.g., `(t1,t2...)` requires `t1 < t2 < ...`

**Comment by philrz** [comment]
This is implied by the "mentioned" note GitHub added above, but it sounds like once we address this we'll want to circle back and un-skip the tests that were skipped in #2159.
