### ISSUE TITLE
Casting to same type fails

### ISSUE THREAD

**Issue by henridf** [brimdata/zed#2196]
Casting a primitive to its own type should be a no-op, but currently fails: 

```
$ echo {}  | zq -t "put a=1.1.1.1 | cut a=a:ip" -
bad cast
```

(This may not fail for all primitive types, but does at least for addr, time, and duration)

**Comment by philrz** [comment]
Not only is it still broken as of current Zed commit 7db68a5, but a community user has bumped into it as well during beta testing. I'm putting this one nearer the top of our list for consideration of the next issues to take on after the `v0.25.0` goes GA.

```
$ zq -version
Version: v0.29.0-513-g7db68a51

$ echo {} | zq 'put a:=1.1.1.1 | a:=ip(a)' -
bad cast
{a:1.1.1.1}
```
