### ISSUE TITLE
-I should be a generic input flag

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#2212]
zq and ast use -I for Z includes.  This should work for any command that can specify Z.

**Comment by philrz** [comment]
As of Zed commit 26dbda0, user-facing Zed tooling is now converged into just the `zq` and `zed` binaries, and the `-I` option is available in both and behaves similarly.

```
$ zq -version
Version: v1.2.0-20-g26dbda03

$ zq -h
NAME
    zq - process data with Zed queries

USAGE
    zq [ options ] [ zed-query ] file [ file ... ]

OPTIONS
...
    -I source file containing Zed query text (may be used multiple times)
...

$ zed -version
Version: v1.2.0-20-g26dbda03

$ zed query -h
NAME
    zed query - run a Zed query on a Zed data lake

USAGE
    query [options] [zed-query]

OPTIONS
...
    -I source file containing Zed query text (may be used multiple times)
...
```

As other contexts arise where we need to add this same `-I` option, we're positioned to do so.

Closing this one as completed.
