### ISSUE TITLE
Escaping quotes causes a parsing error (regression at 9be1403)

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#2244]
(This issue was found via a re-run of the Rug tests.)

At `zq` commit `db76d01` that came right before the changes in #2072 (cc: @mccanne), this was working:

```
$ zq -version
Version: v0.29.0

$ echo '{"foo": "\"bar\""}' | zq -f zson '\"bar\"' -
{
    foo: "\"bar\""
} (=0)
```

However, ever since the changes in #2072, this has been a parse error. Here it is failing with current `zq` at commit 8ea1b4c.

```
$ zq -version
Version: v0.29.0-75-g8ea1b4c6

$ echo '{"foo": "\"bar\""}' | zq -f zson '\"bar\"' -
zq: parse error: error parsing Z at column 8:
\"bar\"
   === ^ ===
```

**Comment by philrz** [comment]
In my attempt to verify the fix, I can see we've made progress, but an example like the one that spawned this issue is not working yet.

Using the test data in the first linked PR and testing with `zq` commit 3cc324e, we can see that a search term containing a single quote works where it wouldn't have before the fix.

```
$ zq -version
Version: v0.29.0-80-g3cc324e6

$ cat input.tzng 
#0:record[s:string]
0:[foo"bar;]
0:[foobar;]
0:["foobar";]

$ zq -f tzng '"foo\"bar"' input.tzng 
#0:record[s:string]
0:[foo"bar;]
```

However, the one with _two_ quoted strings in it is still a failure.

```
$ zq -f tzng '\"foobar\"' input.tzng 
zq: parse error: error parsing Z at column 11:
\"foobar\"
      === ^ ===
```

It used to work back before #2072 though.

```
$ zq -version
Version: v0.29.0

$ zq -f tzng '\"foobar\"' input.tzng 
#0:record[s:string]
0:["foobar";]
```

**Comment by mccanne** [comment]
Well, I'm not sure this is something that we should.   You're putting an escaped quote into an identifier then wanting the search rules to treat the identifier as a string.  The way you get around similar such confusion is to put quotes around the string you want to search for.

**Comment by mccanne** [comment]
In general, we don't have an escape syntax for identifiers...

**Comment by mccanne** [comment]
Maybe I;n thinking about this the wrong way.  We can certainly put escapes in search keywords.

**Comment by nwt** [comment]
I'm with @mccanne here. It's a bit of a surprise to me that
```
echo '{"foo": "\"bar\""}' | zq -f zson '\"bar\"' -
```
produced the same output as
```
echo '{"foo": "\"bar\""}' | go run ./cmd/zq -f zson '"\"bar\""' -
```
rather than a parse error prior to #2072.

**Comment by nwt** [comment]
But whichever direction we decide to go, let's codify as a test before closing this.

**Comment by philrz** [comment]
Verified in `zq` commit 99477b6.

Now this works, whereas it was a parse error last time I tried:

```
$ zq -version
Version: v0.29.0-235-g99477b61

$ cat input.tzng 
#0:record[s:string]
0:[foo"bar;]
0:[foobar;]
0:["foobar";]

$ zq -f tzng '\"foobar\"' input.tzng
#0:record[s:string]
0:["foobar";]
```

Thanks @nwt!
