### ISSUE TITLE
Consistent alias handling in zng type-related helpers 

### ISSUE THREAD

**Issue by henridf** [brimdata/zed#2270]
The zng package has a number of type related helpers such as `zng.IsUnionType()`,`zng.IsContainerType()`, `zng.InnerType()`, etc. 

Their behavior is inconsistent wrt to aliases: some automatically access the underlying type when passed an alias, while others don't. We should make this consistent one way or the other.

**Comment by henridf** [comment]
Reminder: when we address this we should circle back to https://github.com/brimsec/zq/pull/2257#discussion_r584919027

**Comment by mccanne** [comment]
We should do a final cleanup on all these now that the dust has settled on Zed.

**Comment by mccanne** [comment]
We've mostly fixed this...
