### ISSUE TITLE
Turning bare search to an "in" check makes it into an expr

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#2295]
Repros are with `zq` commit 04d20a8.

While making the docs changes in #2294, as a user I briefly fell into a trap that we want to protect users from.

Let's say the user started with this successful "bare" search.

```
$ echo '{"answers": ["www.google.com", "e5803.b.akamaiedge.net", "www.yahoo.com"]}' | zq -z 'e5803.b.akamaiedge.net' -
{answers:["www.google.com","e5803.b.akamaiedge.net","www.yahoo.com"]}
```

If they try to employ the `in` operator to narrow the search to just the named `answers` field, it no longer shows output.

```
$ echo '{"answers": ["www.google.com", "e5803.b.akamaiedge.net", "www.yahoo.com"]}' | zq -z 'e5803.b.akamaiedge.net in answers' -
[no output]
```

Of course, I can see what's going on here: `e5803.b.akamaiedge.net` is now being treated as a field name, so it's checking to see if that field contains a value that's in a top-level complex field called `answers`. This is contrived, but to drive home the point:

```
$ echo '{"e5803": {"b": {"akamaiedge": {"net": "www.google.com"}}}, "answers": ["www.google.com", "e5803.b.akamaiedge.net", "www.yahoo.com"]}' | zq -z 'e5803.b.akamaiedge.net in answers' -
{e5803:{b:{akamaiedge:{net:"www.google.com"}}},answers:["www.google.com","e5803.b.akamaiedge.net","www.yahoo.com"]}
```

Therefore I explained this in the docs and advised the user to wrap the original term in quotes.

```
$ echo '{"answers": ["www.google.com", "e5803.b.akamaiedge.net", "www.yahoo.com"]}' | zq -z '"e5803.b.akamaiedge.net" in answers' -
{answers:["www.google.com","e5803.b.akamaiedge.net","www.yahoo.com"]}
```

Alas, most users don't read the docs until they have a problem, and when the search returns no output it can be challenging for the user to tell the difference between the search being interpreted as intended and nothing was found vs. the search ended up not expressing the user's intent. Therefore it seems we want to do what we can to help the user catch their mistake. I've had high hopes on showing canonical Z (#2197) prominently in the Brim app to help here.

If one were to look at the ASTs (not what we want to require users to do, but we can do it), the difference is pretty easy to spot. Here's the Z where the hostname was _not_ quoted, which returned nothing.

```
$ ast 'e5803.b.akamaiedge.net in answers'
{
    "op": "SequentialProc",
    "procs": [
        {
            "filter": {
                "lhs": {
                    "lhs": {
                        "lhs": {
                            "lhs": {
                                "name": "e5803",
                                "op": "Identifier"
                            },
                            "op": "BinaryExpr",
                            "operator": ".",
                            "rhs": {
                                "name": "b",
                                "op": "Identifier"
                            }
                        },
                        "op": "BinaryExpr",
                        "operator": ".",
                        "rhs": {
                            "name": "akamaiedge",
                            "op": "Identifier"
                        }
                    },
                    "op": "BinaryExpr",
                    "operator": ".",
                    "rhs": {
                        "name": "net",
                        "op": "Identifier"
                    }
                },
                "op": "BinaryExpr",
                "operator": "in",
                "rhs": {
                    "name": "answers",
                    "op": "Identifier"
                }
            },
            "op": "FilterProc"
        }
    ]
}
```

Here's the one where the hostname was quoted and we got the expected result.

```
$ ast '"e5803.b.akamaiedge.net" in answers'
{
    "op": "SequentialProc",
    "procs": [
        {
            "filter": {
                "lhs": {
                    "op": "Literal",
                    "type": "string",
                    "value": "e5803.b.akamaiedge.net"
                },
                "op": "BinaryExpr",
                "operator": "in",
                "rhs": {
                    "name": "answers",
                    "op": "Identifier"
                }
            },
            "op": "FilterProc"
        }
    ]
}
```

Unfortunately, the current canonical Z shows them looking very similar. Yes, the quotes are preserved in the second one, but I still don't think that helps much with communicating that `e5803.b.akamaiedge.net` in the first one ended up being treated as a field name.

```
$ ast -C 'e5803.b.akamaiedge.net in answers'
filter e5803.b.akamaiedge.net in answers

$ ast -C '"e5803.b.akamaiedge.net" in answers'
filter "e5803.b.akamaiedge.net" in answers
```

Q: Would it make sense to add something to canonical Z to show explicitly when something is being treated as a field reference?

**Comment by mccanne** [comment]
@philrz in light of #2692, are you ok to close this?  Quotes are not more prevalent and expected for strings in any expression that is not a bare, keyword search.  Right?

**Comment by philrz** [comment]
Yes, agreed. I'm intending to emphasize this aplenty in the docs updates. Thanks @mccanne!
