### ISSUE TITLE
CSV reader not tolerant of some dialects

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#2332]
Repro is with `zq` commit 2897dd3.

When attempting to verify #999, I happened to randomly grab this CSV test data [letter\_frequency.csv](https://people.sc.fsu.edu/~jburkardt/data/csv/letter_frequency.csv):

```
"Letter", "Frequency", "Percentage"
    "A",  24373121,  8.1
    "B",   4762938,  1.6
    "C",   8982417,  3.0
    "D",  10805580,  3.6
    "E",  37907119, 12.6
    "F",   7486889,  2.5
    "G",   5143059,  1.7
    "H",  18058207,  6.0
    "I",  21820970,  7.3
    "J",    474021,  0.2
    "K",   1720909,  0.6
    "L",  11730498,  3.9
    "M",   7391366,  2.5
    "N",  21402466,  7.1
    "O",  23215532,  7.7
    "P",   5719422,  1.9
    "Q",    297237,  0.1
    "R",  17897352,  5.9
    "S",  19059775,  6.3
    "T",  28691274,  9.5
    "U",   8022379,  2.7
    "V",   2835696,  0.9
    "W",   6505294,  2.2
    "X",    562732,  0.2
    "Y",   5910495,  2.0
    "Z",     93172,  0.0
```

When I attempt to read it with `zq`, I get an error:

```
$ zq -version
Version: v0.29.0-120-g2897dd3b

$ zq -z -i csv letter_frequency.csv 
letter_frequency.csv: parse error on line 1, column 10: bare " in non-quoted-field
```

[This article](https://stackoverflow.com/questions/31326659/golang-csv-error-bare-in-non-quoted-field) indicates this issue can be resolved by setting `LazyQuotes = true` in the Go CSV reader.

**Comment by mccanne** [comment]
This in general shouldn't be hard but we decided to stick with RFC 4180 for now, as supported by Go's csv library.  There is a relevant discussion here...

https://github.com/golang/go/issues/3150#issuecomment-380932754

If/when our user community wants more variation and robustness to CSV, we can tackle this later.  From a cursory search, I didn't find a relevant alternative Go library but one is probably out there somewhere.  For now, this issue is moving to icebox.

**Comment by philrz** [comment]
A community user was engaged in beta testing and was unable to read some CSV data with Zed, creating a quote-related failure similar (but not exactly the same as) to the one already captured above. Repro is with Zed commit af73996.

The attached [evtx_repro.zip](https://github.com/brimdata/zed/files/6671417/evtx_repro.zip) contains everything necessary for the repro. When unpacked, you'll have:

* `evtx_to_csv.ps1` - A PowerShell script that turns Windows EVTX logs (https://github.com/brimdata/zed/issues/2793) into CSV
* `Sysmon_SlothFulMedia.evtx` - A sample EVTX log
* `Sysmon_SlothFulMedia.csv` - The CSV output from running that EVTX log through the PowerShell script

The repro steps performed in PowerShell on my Windows 10 laptop:

```
PS C:\> zq -version
Version: af73996

PS C:\> .\evtx_to_csv.ps1 .\Sysmon_SlothFulMedia.evtx
Reading in the .evtx.
Finding unique fields.
Processing lines.
Processed 86 events.
Writing output file

PS C:\> zq -z -i csv Sysmon_SlothFulMedia.csv
Sysmon_SlothFulMedia.csv: parse error on line 8, column 380: extraneous or missing " in quoted-field
```

For what it's worth, I was able to read this CSV file without complaint into both Excel and Google Sheets. So while it does seem an argument could be made about how this particular CSV output is technically impure ([RFC4180](https://datatracker.ietf.org/doc/html/rfc4180) covers this topic in some detail), given our intent to have Zed be friendly to as much input data as possible, it seems it would be good for us to be as tolerant as the others. Even if we had to require the user to twiddle some flags to get it right, it seems that would be an improvement over requiring them to preprocess with other tools first, which is what it seems they'd be stuck doing currently.

In terms of the specific place it's choking with this example, that line 8 happens to be the first location of any `"` in the file. In the original input CSV, the value where the `"` appears happens to be:

```
"C:\Windows\SysWOW64\DllHost.exe" /Processid:{776DBC8D-7347-478C-8D71-791E12EF49D8}
```

When Google Sheets reads in this CSV, it appears in Sheets with the quotes stripped away:

```
C:\Windows\SysWOW64\DllHost.exe /Processid:{776DBC8D-7347-478C-8D71-791E12EF49D8}
```

**Comment by philrz** [comment]
I've verified in Zed commit 96be300 that we've addressed the problem with the CSV dialect initially described in the issue.

```
$ zq -version
Version: v0.29.0-416-g96be3005

$ zq -z -i csv letter_frequency.csv
{Letter:"A",Frequency:24373121.,Percentage:8.1}
{Letter:"B",Frequency:4762938.,Percentage:1.6}
{Letter:"C",Frequency:8982417.,Percentage:3.}
{Letter:"D",Frequency:10805580.,Percentage:3.6}
{Letter:"E",Frequency:37907119.,Percentage:12.6}
{Letter:false,Frequency:7486889.,Percentage:2.5}
{Letter:"G",Frequency:5143059.,Percentage:1.7}
{Letter:"H",Frequency:18058207.,Percentage:6.}
{Letter:"I",Frequency:21820970.,Percentage:7.3}
{Letter:"J",Frequency:474021.,Percentage:0.2}
{Letter:"K",Frequency:1720909.,Percentage:0.6}
{Letter:"L",Frequency:11730498.,Percentage:3.9}
{Letter:"M",Frequency:7391366.,Percentage:2.5}
{Letter:"N",Frequency:21402466.,Percentage:7.1}
{Letter:"O",Frequency:23215532.,Percentage:7.7}
{Letter:"P",Frequency:5719422.,Percentage:1.9}
{Letter:"Q",Frequency:297237.,Percentage:0.1}
{Letter:"R",Frequency:17897352.,Percentage:5.9}
{Letter:"S",Frequency:19059775.,Percentage:6.3}
{Letter:true,Frequency:28691274.,Percentage:9.5}
{Letter:"U",Frequency:8022379.,Percentage:2.7}
{Letter:"V",Frequency:2835696.,Percentage:0.9}
{Letter:"W",Frequency:6505294.,Percentage:2.2}
{Letter:"X",Frequency:562732.,Percentage:0.2}
{Letter:"Y",Frequency:5910495.,Percentage:2.}
{Letter:"Z",Frequency:93172.,Percentage:0.}
```

There was a separate, slightly-different quote-related CSV reader problem originally cited in a separate comment above, but that does not seem to have been addressed by the change in the linked PR, so I've moved that to a separate issue #2862 where we may pursue that.

Thanks @mattnibs!
