### ISSUE TITLE
zed-ify command names

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#2346]
@mccanne has a proposal to reorganize the family of commands compiled from the `zq` repo under a single top-level `zed` command with sub-commands, similar to how tools like `kubectl` work. As part of this, shortcuts will remain so users accustomed to typing `zq` by itself will still work as well.

**Comment by mccanne** [comment]
#2450 is step 1 here.  Next, we need to figure out what to do with `ppl/cmd/{zqd,zar}`

**Comment by philrz** [comment]
In the last chat I had with @mccanne about this one, the current plan of record is to lift the `lake` stuff out of `ppl/` and leave `zqd` under `ppl/` for now. At some point we'll figure out how to have separate ppl and non-ppl versions of `zqd` that offer the cloud-inclusive & free functionality, respectively.

**Comment by philrz** [comment]
`ppl/` is gone for the moment. I've opened #2675 as a reminder for us to repopulate it when appropriate.
