### ISSUE TITLE
"zed lake" ergonomics & named layers

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#2352]
This is expected to require some brainstorming between @mccanne, @mattnibs, @nwt, and @jameskerr about the UX. Perhaps kick things off by playing with `zed lake` a bit to reacquaint ourselves with how it's worked in the past vs. where we want it to go.

@mccanne expects that "layers" may not make the MVP0 cut, but he expects to figure that out as part of the current research.

**Comment by mccanne** [comment]
After thinking about this, I think a layer should just be a pool and we should add a way to do a merge-scan from multiple pools.  Then this becomes a UX issue for the app, e.g., mixing beacon alerts from one pool in with zeek logs from another pool and displaying and querying together.

**Comment by mccanne** [comment]
This is moot by now.
