### ISSUE TITLE
zjson type values need to be updated

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#2376]
zjson type values are currently encoded as strings.  This means that the client would have to parse the string to recreate a complex type structure.  Instead, we should update zjson to use nested JSON structure to encode the Z type just like it does for complex values allowing native JSON-oritned clients (like zealot and the python library) to more easily decode a Z type value.

**Comment by philrz** [comment]
This will be important for the app to be able to show the structure of type values.

**Comment by philrz** [comment]
Duplicate of #1780.
