### ISSUE TITLE
Improve error message for ZSON with missing field

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#2394]
Repros are with `zq` commit c5ecae7.

When updating test [ppl/lake/ztests/import-check.yaml](https://github.com/brimsec/zq/pull/2389/files/4d44b7c8c591979d1a3e3446070d7750dc77b9bc#diff-ca3d35f9be8b014fd9fd1f4b4a65041d0363df03bad21568965a3c26bb0bd6ce) to convert its input data from TZNG to ZSON, we noted the error message for the ZSON equivalent could stand to be improved.

The TZNG one:

```
$ cat missingcol.tzng 
#0:record[a:string,b:string]
0:[a;]

$ zq -z -i tzng missingcol.tzng 
missingcol.tzng: line 2: b (string): record missing a field
```

The ZSON equivalent:

```
$ cat missingcol.zson 
{a:"a",b:"b"} (=foo)
{a:"a"} (foo)

$ zq -z -i zson missingcol.zson 
missingcol.zson: record decorator columns (2) mismatched with value columns (1)
```

**Comment by philrz** [comment]
@mccanne noted that this will only come up if someone is writing ZSON by hand (or has written software that's outputting buggy ZSON), hence probably a low priority.

**Comment by mccanne** [comment]
No longer relevant.
