### ISSUE TITLE
coercion should embed error instead of failing with "incompatible types"

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#2404]
I did this by mistake, `d=1y` with this data 
```
{d:"1y"}
{d:"1y3m"}
```
And because d is a string instead of an error, zq exits with "incompatible types".  Instead it should embed an error.

**Comment by mccanne** [comment]
I think this is fine now.  On #2692,
```
$ cat in.zson 
{d:"1y"}
{d:"1y3m"}
{d:1y}
$ zq -z "d==1y" in.zson
{d:1y}
$ zq -z "duration(d)==1y" in.zson
{d:"1y"}
{d:1y}
```

**Comment by mccanne** [comment]
No longer a problem after #2692.

**Comment by philrz** [comment]
Verified in Zed commit 035b439.

```
$ zq -version
Version: v0.29.0-345-g035b439b

$ cat in.zson 
{d:"1y"}
{d:"1y3m"}
{d:1y}
```

The first query returns the record with the value that's of type `duration`.

```
$ zq -z "d==1y" in.zson
{d:1y}
```

The second query returns another record as well whose string value `"1y"` successfully casts to the `duration` type and hence succeeds in the equality test.

```
$ zq -z "duration(d)==1y" in.zson
{d:"1y"}
{d:1y}
```

Thanks @mccanne!
