### ISSUE TITLE
Automated testing of zed lake README

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#2429]
Several times during its life, the [`zar` README](https://github.com/brimsec/zq/blob/master/ppl/cmd/zar/README.md) has gotten out-of-sync with the actual tech it describes. Sometimes this has been semi-benign changes such as output formatting, and other times it's been genuine bugs/panics. Since we want the README to be a doc that's approachable for users unfamiliar with the technology, all such kinds of such divergence are a problem.

When they diverge, we've also found that getting the README and the tech back in sync again is a fairly expensive operation. In addition to it having been a manual task (executing the commands from the README manually and eyeballing the outputs), when multiple changes/bugs have stacked up over time, it becomes complicated to unravel the layers and determine what the individual bugs are, which are intentional changes in functionality that justify changing the descriptive text in the README, and so on.

Like with other things we improve incrementally, it seems we'd benefit from a "pay as you go" approach. Like we do with the ZQL examples in the Markdown docs, we could benefit from automation that runs the commands in the `zar` README via CI and notifies us when they start to fail or their outputs have changed from what's expected. The automation that already exists for the ZQL examples is close in spirit to what's needed, but the approach of the `zar` README are just different enough that it seems we'd need to create a variation to get the coverage we need.

Having just completed an overhaul of the README where I went through all the commands & output several times, here's a laundry list of things I expect we'd need to deal with in designing an MVP of this.

1.  It would be great to preserve the same approach we use with the ZQL examples where the command lines run by the automation and the outputs that are checked are exactly the same ones that the user sees when they read the rendered Markdown. That way a developer responding to a breakage in the test fixes both the test and the doc at the same time.  
     
2.  Whereas each ZQL example is standalone, workflow in the `zar` README requires a single "state" that persists for the life of the executed commands, i.e. data is imported into a fresh lake at the start of the README and all the subsequent `zar` and `zq` commands depend on that data having already been imported. If we wanted to get fancy, perhaps we could build the automation with the concept of multiple such "states" (e.g. ways to tag different sets of commands within the same Markdown file that are tied to different stateful test environments), but that's not needed for the `zar` README in its current state, so that's "nice-to-have", not "must-have".  
     
3.  The data imported in the README is currently part of the [zq-sample-data](https://github.com/brimsec/zq-sample-data). At the moment the `zq` Makefile is wired such that the zq-sample-data gets cloned as a dependency when running `test-heavy`, and the ZQL examples are all of this "heavy" category. Therefore if we mimic that with the automation that's created to cover the `zar` README, hopefully handling import will be trivial.  
     
4.  Whereas the ZQL examples basically all exist precisely for the purpose of to showing their outputs, for brevity, in the `zar` README there's currently several commands that we advise the user to type but we don't show the output in the README. I see various options for what we could do to cover these, with easiest ideas listed first.
    1.  Do nothing. We can just be happy with the coverage we've got from all the other commands that'll now be checked that weren't in the past. Hopefully we already have other tests that cover these (e.g. running `zar ls`), and if we start finding subtle failures keep sneaking through (e.g. if our "regular" ztest for `zar ls` keeps passing but it fails with the data set in the `zar` README), we can deal with the problem then.
    2.  We could start including the outputs from more of such commands in the README as a low-cost way of getting more coverage without adding enhancements to the automation. The verbosity in the README may even be appreciated by some readers.
    3.  Have a way in the automation to flag a command that's run and the automation only checks that it finishes successfully, not checking its output. That would at least get us coverage against panics and the like.
    4.  Have a way for the expected output to be somehow present in the Markdown where the automation can find it & use it to check correctness of output but the reader never sees that output as part of the rendered Markdown. (Make it part of a comment, tagged/formatted in a certain way?)  
         
5.  There's several outputs currently in the README that we know will change per run, e.g the filenames in the lake of the formats such as `d-1jQ2dLYVOL4NSSYCYC4P400ZfPN.zng`. The text currently alerts the reader to this so they know not to panic if they notice it while repeating the README steps. We _would_ want to check _other_ non-changing portions of these outputs for correctness, though (e.g. event counts). @nwt and I kicked around a couple ideas here that seem viable. One thought was to have the automation scrub the output before checking for correctness (e.g. use a regexp that would have changed the above to `d-XXXXXXXXXXXXXXXXXXXXXXXXXXX.zng`). Another was to maybe introduce some kind of test mode to the `zar` tech itself that would allow the setting of a seed for the hash functions to make it produce deterministic outputs when we run the automation.

**Comment by mccanne** [comment]
zar README no longer relevant.  This is a general problem that we handle with our markdown tests but adding this to top level READMEs will be "noisy".  In the long run, there are other ways to solve this docs problem.
