### ISSUE TITLE
Change ZSON methods to string methods

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#2473]
After the rework that was done resulting in the closure of #1417, @mccanne indicates there's some remaining tech debt to change the ZSON methods to string methods, now that the string methods have been freed up. This is just renaming, as @mccanne says the code works fine the way it is.

**Comment by mccanne** [comment]
meaining... zng.Type.ZSON() should be replaced with String() and ZSONOf() should be replaced with StringOf()

**Comment by mccanne** [comment]
We actually might want to move all formatting to package ZSON.
```
zson.FormatValue(zng.Value)
zson.FormatType(zng.Type)
```
