### ISSUE TITLE
'cut .=a' fails when a is unset

### ISSUE THREAD

**Issue by nwt** [brimdata/zed#2476]
```
$ zq -z 'cut .=a' - <<<'{a:null (0=({b:int32}))} (=1)'
b (int32): record missing a field
exit status 1
```

**Comment by philrz** [comment]
Convert the test in [expr/ztests/cut-to-root.yaml](https://github.com/brimdata/zed/pull/2477/files#diff-f978cec0b1a746fb6d43f45f447eda265cc51dfd9528c2a4559ef2e6e809e8e4) to use ZSON when this issue is fixed.

**Comment by philrz** [comment]
In talking over this one with @mccanne, he noted that while the test appears to run successfully and outputs TZNG, that TZNG is actually invalid. With `zq` commit 12951f1.

```
$ cat in.zson 
{a:null (0=({b:int32}))} (=1)
{a:{b:null}} (1)
{a:{b:1}} (1)

$ zq -f tzng 'cut .=a' in.zson 
#0:record[b:int32]
0:[]
0:[-;]
0:[1;]

$ zq -f tzng 'cut .=a' in.zson | zq -z -i tzng -
stdio:///stdin: line 2: b (int32): record missing a field
```

That said, he also acknowledges there's something deeper to be found here, so it's been moved to his backlog.
