### ISSUE TITLE
Triggered compaction

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#2497]
For MVP0, we may simply rely on manual `zed lake compact` to cover compaction needs. After that, we'll surely want more sophisticated ways to trigger compaction. One thought is that it may be triggered periodically during some kind of continuous ingest process. Another is that it can be invoked by a user as part of the Git-style commit/merge workflow that's being considered for the Zed lake. Ways it's invoked at the CLI level may also become fair game to invoke in the Brim app.

Overall we expect the answers to reveal themselves as we create the building blocks, so this is effectively a placeholder issue.

**Comment by mccanne** [comment]
This will be done by the lake manager (see #3923) and should be solve in this context rather than a generic feature of the zed lake service.  Closing this as it will be covered there.
