### ISSUE TITLE
Resolve to underlying types (such as for comparison)

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#2502]
As shown in the following Zed at `zq` commit 12951f1, comparing two `type` values only shows them to be equal if they're exactly the same. That is, even though `port` is ultimately stored the same as `uint16`, there's not currently a way to confirm this.

```
$ cat in.zson 
{dst_port:39681 (port=(uint16)),a:0 (uint16), b:0 (uint16)} (=0)

$ zq -Z 'put same=(typeof(a)=typeof(b)),diff=(typeof(dst_port)=typeof(a))' in.zson 
{
    dst_port: 39681 (port=(uint16)),
    a: 0 (uint16),
    b: 0 (uint16),
    same: true,
    diff: false
} (=0)
```

We've envisioned addressing this with a function that resolves to the underlying type, e.g. effectively "stripping" the named type.

**Comment by mccanne** [comment]
`Typeunder()` takes care of this:
```
% cat in.zson 
 {dst_port:39681 (port=(uint16)),a:0 (uint16), b:0 (uint16)} (=0)
bay 515 > zq -Z 'same:=(typeunder(a)==typeunder(b)),same2:=(typeunder(dst_port)==typeunder(a))' in.zson
{
    dst_port: 39681 (port=(uint16)),
    a: 0 (uint16),
    b: 0 (uint16),
    same: true,
    same2: true
}
```
