### ISSUE TITLE
simplify ZSON enum type

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#2508]
The current enum type allows arbitrary ZSON values to be assigned to enum Symbols.
Let's simplify the ZSON enum type to consist solely as a list of symbols.
The symbol syntax shall follow identifiers.
The canonical format for an enum type shall sort the list of symbols alphabetically.
In the zng.TypeEnum struct, change the name of the symbols from Elements to Symbols.

This is a breaking change to ZNG, ZST, and ZSON but nothing uses enum as far as I know.
(The Zed journal will use it.)
The format will not otherwise break if there are no enum types in use.

**Comment by philrz** [comment]
A test in the linked PR shows the change. As described above, in the past enums had values assigned to the enum symbols, such as in this example where `HEADS` and `TAILS` were assigned integer values of `0` and `1`, respectively.

```
$ cat input-before.zson 
{flip:HEADS (0=(<HEADS:0 (uint8),TAILS:1>))} (=1)
{flip:TAILS} (1)
{flip:HEADS} (1)

$ zq -version
Version: v0.29.0-394-g2b3d086f

$ zq -z input-before.zson 
{flip:HEADS (0=(<HEADS:0 (uint8),TAILS:1>))} (=1)
{flip:TAILS} (1)
{flip:HEADS} (1)
```

Now it's simplified to just a list of symbols.

```
$ zq -version
Version: v0.29.0-403-gb28cfe0b

$ cat input-after.zson 
{flip:HEADS (0=(<HEADS,TAILS>))} (=1)
{flip:TAILS} (1)
{flip:HEADS} (1)

$ zq -z input-after.zson 
{flip:HEADS (0=(<HEADS,TAILS>))} (=1)
{flip:TAILS} (1)
{flip:HEADS} (1)
```

Thanks @mccanne!
