### ISSUE TITLE
new zed lake: make indexing work again

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#2532]
The indexing logic needs to be updated for the new zed lake layout.

The index writer has been removed from the segment data write-path as it is typically memory intensive and should be done in a separate pass tuned for the indexing workload.  It will be run from orchestration external to the write path and may very well be run by agents outside of the core that simply run indexing work, introspection, and analysis through the service API.  Different indexing events may happen at different times and could even be triggered off reactive algorithms that adapt to the query workload patterns.

This task involves updating the indexing core (not the orchestration) and `zed lake index` commands.  Indexes will be named with ksuid's (but the ksuid does not appear in the object path of the zng index file).  The commit log holds the index rules and index add/del ops for each segment (which refer to the ksuid of the rule).

_(See comment below for modified proposal.)_ 

Proposal is:
* assign a ksuid to each index rule, call it `<xid>`
* put `<xid>`'s rule in the commit log as log-oriented ref
* index add are just like add commits and can be intermixed in a single commit
* add index-add (`<seg>`,`<xid>`) and index-delete actions to commit actions
* store an index of data segment `<segid>` as immutable object `<poolid>/index/<segid>.zng`

**Comment by mccanne** [comment]
`lake/ztests/index-on-compact.yaml` is currently skipped and should be updated in this task

**Comment by mccanne** [comment]
Modified proposal after discussing with @mattnibs :

* assign a ksuid to each index rule, call it `<rid>`
* put `<rid>`'s rule in the commit log as AddIndexRule, DeleteIndexRule
* use the segment `<id>` that was indexed for a given `<rid>` and name it `<pool>/X/<rid>/<id>.zng`
* create new transaction types for AddIndex, DelIndex
* AddIndex, DeleteIndex, AddIndexRule, and DeleteIndexRule are just any other actions.Interface in a commit.Interface and can be intermixed in a single commit along with Add and Delete

**Comment by philrz** [comment]
We established in a recent group discussion that there's still unfinished business in the indexing area, so I'm reopening this issue as a reminder that we circle back to it.

**Comment by mccanne** [comment]
Many lake ztests need to be updated and are skipped because of this issue....
