### ISSUE TITLE
new zed lake: finish merge command

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#2537]
The new zed lake supports a merge operation that takes a set of tags, reads the commits/objects into a new commit, and outputs the new commit tag.

This task involves implementing the stub in `cmd/zed/lake/merge`.  It is very simple.  Just copy code from `zed lake query` and take stuff out.  It should take 15 minutes to code and a bit more time to write some tests.

**Comment by mccanne** [comment]
`lake/ztests/compact.yaml` should be converted to `zed lake merge`

**Comment by philrz** [comment]
Note to self: When this gets implemented, update the Zed lake design doc to remove the reference to this being an open isssue.

**Comment by mccanne** [comment]
This is subsumed by branches and merging...
