### ISSUE TITLE
new zed lake: delete by key range

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#2540]
One should be able to delete pool data by specifying a key range.

This requires detecting segments that overlap but spill over outside the range then rewriting the spill over potion and finally commting add for the spillovers and deletes for everything that overlapped.

**Comment by philrz** [comment]
This was added some time ago and we've since gone even further to allow deletes based on things other than the pool key. See the [docs](https://zed.brimdata.io/docs/commands/zed#24-delete) and verification notes in #3992 for example uses.
