### ISSUE TITLE
zed lake stage -drop tag

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#2541]
You should be able to remove commits from staging with `zed lake stage -drop tag tag...` 

This is stubbed out in cmd/zed/lake/stage/command.go

**Comment by mattnibs** [comment]
These is no zed lake stage command, @mccanne did you mean zed lake status here?

**Comment by mattnibs** [comment]
For now we're going to have this functionality exist in the delete command. The delete command will also include a `-staging` flag that will drop all commits in staging.

**Comment by mattnibs** [comment]
Closing this ticket because the plan is to get rid of staging once branches are implemented.
