### ISSUE TITLE
seek index stride parameter

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#2542]
The seek index stride parameter shouldn't be called `-streammax`

**Comment by philrz** [comment]
"Time index density"?

**Comment by mccanne** [comment]
We agreed today that we would call the command option `-seekstride` and base it on bytes rather than records.  Also, when this change gets made,  we should clean up the API with `zngio.Writer` for how the decision points are mode.  The logic in `lake/segment/writer.go` seems overly complicated for how/when seek points are signaled and tracked with `zngio.Writer`.
