### ISSUE TITLE
Typo in search syntax doc for "greater than or equal to" operator

### ISSUE THREAD

**Issue by wan-xiang** [brimdata/zed#2551]
zed/zql/docs/search-syntax/README.md 
Field/Value Match->Comparisons
!=, <, >, <=, and =>

**Comment by philrz** [comment]
@wan-xiang: Thanks for bringing this to our attention! I've got a PR up to fix this. The tagged version of docs that are linked from [https://github.com/brimdata/zed/tree/main/zql/docs](https://github.com/brimdata/zed/tree/main/zql/docs) to go with the most recent GA releases of zq and Brim are effectively locked in place, but the fix will be reflected in the docs in the `main` branch that now live under [https://github.com/brimdata/zed/tree/main/docs/language](https://github.com/brimdata/zed/tree/main/docs/language) and reflect more recent improvements to the language.
