### ISSUE TITLE
Document err or soft bug 

### ISSUE THREAD

**Issue by wan-xiang** [brimdata/zed#2554]
zed/docs/language/grouping/README.md  ->Time Grouping - every
 Example #2 and example #3
example 2
every 0.5m count() | sort -r count，give err "SyntaxError: Expected ".", "e", "in", "|", [0-9], [\n\r  ], comment, or whitespace but "m" found.". but "every 30s count() | sort -r count" can search.
example 3
every 1m30s max(id.resp_p) | sort -r ts ,give err"SyntaxError: Expected "!=", "!~", ".", "<", "<=", "=", "=~", ">", ">=", "[", "\\", "in", "|", [0-9], [A-Za-z_$], [\n\r  ], comment, or whitespace but "(" found.". 1m30 ->90s can search.
Brim for windows 0.24.0 .

**Comment by philrz** [comment]
@wan-xiang: Indeed, the docs you're referring to are relevant for the language as it exists in the tip of `main` (i.e. if you were building Brim or Zed using the most recent code), but the language was different in this area in the last GA release Brim v0.24.0 that you're running. If you want to refer to the language docs as they were as of that release, start by browsing from the tag [https://github.com/brimdata/zed/tree/v0.29.0/zql/docs.](https://github.com/brimdata/zed/tree/v0.29.0/zql/docs.)

As for the specific examples with time grouping, the support in the older rev of the language as described at [https://github.com/brimdata/zed/tree/v0.29.0/zql/docs/grouping](https://github.com/brimdata/zed/tree/v0.29.0/zql/docs/grouping) lacked the ability to do the fractional units like the `0.5m` (so, you'd do `30sec` in the older language) as well as the ability to combine multiple units like `1m30s` (you'd do `90sec` in the older language).

Hopefully that clears it up. I'll close the issue for now, but feel free to add more comments if you have more questions. You might also want to consider [joining our public Slack](https://www.brimsecurity.com/join-slack/) as we can often respond quicker there for quick inquiries like these.
