### ISSUE TITLE
zson colorization

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#2578]
Pretty-zson (-Z) should be colorize fields and values (but not other syntax) like `jq` does,
when writing to terminal stdout.

Example use is in lakeio (which currently just colors the commit tag).

**Comment by philrz** [comment]
Verified in `zq` commit `3fb771c5`.

Here's examples of the colorization in action, along with turning it off via `-color=false`.

![image](https://user-images.githubusercontent.com/5934157/115939475-05b63480-a453-11eb-87ba-f6ee19827034.png)

Thanks @mccanne!
