### ISSUE TITLE
zed lake clear

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#2579]
Add `zed lake clear` command to delete staged commits and the underlying data that will not be committed.

**Comment by mccanne** [comment]
Actually, you can only delete the data if you know it was not committed previously and still referred to.  So best to leave this to vacate (or include a force-delete flag?)

**Comment by philrz** [comment]
Note to self: When this gets implemented, update the Zed lake design doc to remove the reference to this being an open isssue.

**Comment by mccanne** [comment]
Closing because we eliminated the staging concept.
