### ISSUE TITLE
zng marshaler shouldn't panic when encountering private struct values

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#2582]
Michael on the brim slack channel [reported this problem](https://brimsec.slack.com/archives/CTT24051C/p1618804259032000). The zng marshaler should instead silently ignore unexported fields as is the design pattern in the Go's `encoding/json` package.

Repro with :

```
package main
import (
    "log"
    "os"
    "time"
    "github.com/brimsec/zq/zio/zngio"
    "github.com/brimsec/zq/zson"
)
type SomeType struct {
    ExportedS string
    ExportedT time.Time
    privateS  string
}
func main() {
    data := []SomeType{
        {
            ExportedS: "Sample",
            ExportedT: time.Now(),
            privateS:  "Not Public",
        },
        {
            ExportedS: "Sample 2",
            ExportedT: time.Now(),
            privateS:  "Not Public 2",
        },
    }
    // Create Marshaller
    marshaller := zson.NewMarshaler()
    // Create File
    f, err := os.Create("sample.zng")
    if err != nil {
        log.Println(err)
    }
    // Create Writer
    zw := zngio.NewWriter(f, zngio.WriterOpts{})
    defer zw.Close()
    // Add Data to file
    for _, event := range data {
        record, err := marshaller.MarshalRecord(event)
        if err != nil {
            log.Println(err)
        }
        if record == nil {
            break
        }
        err = zw.Write(record)
        if err != nil {
            log.Println(err)
        }
    }
}
```

**Comment by MichaelRoberts-CyberSecurity** [comment]
**Panic Results**

> panic: reflect.Value.Interface: cannot return value obtained from unexported field or method
goroutine 1 [running]:
reflect.valueInterface(0x6db020, 0xc00001e150, 0xab, 0x738501, 0x6db020, 0xc00000a1d0)
	C:/Users/_____/go/go1.16.2/src/reflect/value.go:1027 +0x169
reflect.Value.Interface(...)
	C:/Users/_____/go/go1.16.2/src/reflect/value.go:1016
github.com/brimsec/zq/zng/resolver.(*MarshalContext).encodeAny(0xc00004e0f0, 0x6db020, 0xc00001e150, 0xab, 0x0, 0x0, 0xc00000a1d0, 0x1)
	C:/Users/_____/go/pkg/mod/github.com/brimsec/zq@v0.29.0/zng/resolver/marshal.go:235 +0xd6
github.com/brimsec/zq/zng/resolver.(*MarshalContext).encodeValue(0xc00004e0f0, 0x6db020, 0xc00001e150, 0xab, 0x6db020, 0xc00001e150, 0xab, 0x0)
	C:/Users/_____/go/pkg/mod/github.com/brimsec/zq@v0.29.0/zng/resolver/marshal.go:197 +0x6e
github.com/brimsec/zq/zng/resolver.(*MarshalContext).encodeRecord(0xc00004e0f0, 0x701020, 0xc00001e150, 0x99, 0x701020, 0xc00001e150, 0xc00010f920, 0x639b3f)
	C:/Users/_____/go/pkg/mod/github.com/brimsec/zq@v0.29.0/zng/resolver/marshal.go:308 +0x256
github.com/brimsec/zq/zng/resolver.(*MarshalContext).encodeAny(0xc00004e0f0, 0x701020, 0xc00001e150, 0x99, 0x0, 0x10, 0xc00000a1a8, 0x1)
	C:/Users/_____/go/pkg/mod/github.com/brimsec/zq@v0.29.0/zng/resolver/marshal.go:248 +0xbad
github.com/brimsec/zq/zng/resolver.(*MarshalContext).encodeValue(0xc00004e0f0, 0x701020, 0xc00001e150, 0x99, 0x701020, 0xc00001e150, 0x99, 0x0)
	C:/Users/_____/go/pkg/mod/github.com/brimsec/zq@v0.29.0/zng/resolver/marshal.go:197 +0x6e
github.com/brimsec/zq/zng/resolver.(*MarshalContext).encodeRecord(0xc00004e0f0, 0x6ede40, 0xc00001e140, 0x99, 0x6ede40, 0xc00001e140, 0x4, 0x704e23)
	C:/Users/_____/go/pkg/mod/github.com/brimsec/zq@v0.29.0/zng/resolver/marshal.go:308 +0x256
github.com/brimsec/zq/zng/resolver.(*MarshalContext).encodeAny(0xc00004e0f0, 0x6ede40, 0xc00001e140, 0x99, 0x663e00, 0x1, 0x2030000, 0x2030000)
	C:/Users/_____/go/pkg/mod/github.com/brimsec/zq@v0.29.0/zng/resolver/marshal.go:248 +0xbad
github.com/brimsec/zq/zng/resolver.(*MarshalContext).encodeValue(0xc00004e0f0, 0x6ede40, 0xc00001e140, 0x99, 0x38, 0x7ffb80, 0x0, 0xc00010fd58)
	C:/Users/_____/go/pkg/mod/github.com/brimsec/zq@v0.29.0/zng/resolver/marshal.go:197 +0x6e
github.com/brimsec/zq/zng/resolver.(*MarshalContext).MarshalRecord(0xc00004e0f0, 0x6ede40, 0xc00001e140, 0xc00001e140, 0xc000006030, 0x0)
	C:/Users/_____/go/pkg/mod/github.com/brimsec/zq@v0.29.0/zng/resolver/marshal.go:74 +0xed
main.main()
	C:/Users/_____/go/src/_____/Support/TEST/TEST.go:48 +0x55f
