### ISSUE TITLE
Improve error message for clash between type name & field reference

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#2598]
Repro is with `zq` commit f8d7a87 and the [Zeek NDJSON sample data](https://github.com/brimdata/zed-sample-data/tree/main/zeek-ndjson).

When attempting certain additional Zed operations after applying the [reference shaper for Zeek](https://github.com/brimdata/zed/blob/main/zeek/shaper.zed), we see failures with error messages that aren't too helpful.

```
$ zq -z -I ~/work/zed/zeek/shaper.zed '| head 1 | cut id.resp_h' weird.ndjson.gz 
invalid expression on lhs of assignment

$ zq -z -I ~/work/zed/zeek/shaper.zed '| head 1 | put classnet=network_of(id.resp_h) | count() by classnet | sort classnet' weird.ndjson.gz 
put: a referenced field is missing
```

The root cause turns out to be that there's currently a type definition called `id` within the shaper:

```
type id={orig_h:ip,orig_p:port,resp_h:ip,resp_p:port};
```

This clashes with these later attempts to treat `id` as a reference to a named field in the log data.

We discussed this as a group and there was consensus that the way to address in the short term is to use more descriptive names for the types in the shaper such that they would not conflict with named fields in the data, e.g. `type socket` in this case. However, even if we show best practices in our reference configs and docs, since certain data sources may have hundreds or thousands of fields of different names, we can't rule out that this might still happen in the wild. Therefore the error messages should be improved to indicate what actually happened, i.e. explicitly mention the clash.

**Comment by mccanne** [comment]
This has been fixed as we now require type values to be wrapped in angle brackets...
