### ISSUE TITLE
Quoted string as a typedef is silently accepted, but should be an error

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#2606]
Repro is with `zq` commit 9ff0418.

Start from this working shaper config.

```
$ cat shaper.zed 
type foo={_path:string,testfield:null}
put . = shape(foo)

$ echo '{"_path": "bar", "testfield": null}' | zq -z -I shaper.zed -
{_path:"bar",testfield:null (null)} (=foo)
```

Let's say I was a new user that was inexperienced with shaping configs and had tried putting `"null"` in quotes similar to how it appears in [JSON Schema](https://json-schema.org/draft/2020-12/json-schema-core.html). When doing this, I found it silently accepted the config.

```
$ cat badshaper.zed 
type foo={_path:string,testfield:"null"}
put . = shape(foo)

$ echo '{"_path": "bar", "testfield": null}' | zq -z -I badshaper.zed -
[no output]
```

Seeing this, @mccanne confirmed the parser should have kicked this back as an error.

**Comment by mccanne** [comment]
Hmm, this is parsing as follows...
```
$ zc -C -I badshaper.zed
filter match("type") and foo=(unknown expr *ast.RecordExpr)
   and match("put") and this=shape(foo)
```
Let's see where the latest keyword-search stuff lands and how this fits in then...

Is there an issue for `(unknown expr *ast.RecordExpr)`?

**Comment by mccanne** [comment]
After looking again here, as long as `type` and `put` are valid search terms `x=<expr>` can be used as a search term, I don't see how to raise an error for this.  Some options: 
* The type statement could require semi-colon termination, which would help here. 
* We could say reserved word (put, cut, from, in, etc) have to be escaped in keyword search
* We could have a warning that if any search begins with a reserved word (or a specific set of leading reserved word), we could print a warning (by checking in the semantic pass).  Or we could just error and say you need an escape for this case.

**Comment by mccanne** [comment]
On #2692, with this badshaper.zed, we get the desired parse error...
(though there is a missing newline in the error message)
```
$ cat badshaper.zed 
type foo={_path:string,testfield:"null"}
put this := shape(foo)
$ echo '{"_path": "bar", "testfield": null}' | zq -z -I badshaper.zed -
zq: parse error: error parsing Z at line 1, col 34:type foo={_path:string,testfield:"null"}
                             === ^ ===
put this := shape(foo)
```

So I say we fix the missing newline and add a test for this after #2692 is merged, then close this on that PR.

**Comment by mccanne** [comment]
@philrz I think we can close this per comment above...

**Comment by philrz** [comment]
Verified in Zed commit d0b2458.

Now when I attempt to use the "bad shaper" I am shown a well-formatted parse error.

```
$ zq -version
Version: v0.29.0-350-gd0b2458c

$ cat badshaper.zed 
type foo={_path:string,testfield:"null"}
put . = shape(foo)

$ echo '{"_path": "bar", "testfield": null}' | zq -z -I badshaper.zed -
zq: parse error: error parsing Z at line 1, col 34:
type foo={_path:string,testfield:"null"}
                             === ^ ===
put . = shape(foo)
```

Thanks @mccanne!
