### ISSUE TITLE
recast iosrc into cloud-object model

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#2615]
The iosrc currently implements a subset of file system semantics then maps those onto s3.   This is upside down.  We should have a storage abstraction that implements cloud object store semantics then we should map those semantics onto a file system for local operation.    This should lead to cleaner code and fewer bugs since the cloud peculiarities are hidden behind a layer.  Also, it will then make immutable object caching trivial as a wrapper on the new storage interface.  While we're at it, we should get rid of the single mux and just have entities that want to talk to storage keep an interface pointer to a storage implementation.

**Comment by philrz** [comment]
Note-to-self: When verifying the changes linked to this issue, revisit the notes in [https://github.com/brimdata/zed/issues/2614#issuecomment-825996315](https://github.com/brimdata/zed/issues/2614#issuecomment-825996315) regarding an abusive concurrency test we should re-run.

**Comment by mccanne** [comment]
Also, I realized this is the right place to put http.  With this change we can unify proc.DataAdaptor.Open()/Get() to use the Get() method on the ported storage engine (iosrc to be renamed storage).  Then we can unify dag.HTTP and dag.File as @nwt suggeted on the hazmat PR.

**Comment by philrz** [comment]
Following up on my note-to-self from [https://github.com/brimdata/zed/issues/2615#issuecomment-825996460,](https://github.com/brimdata/zed/issues/2615#issuecomment-825996460,) I just did a re-check and the error messages are still present, so I've opened #2699 so we can look into that.
