### ISSUE TITLE
Git-style branches in Zed lakes

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#2626]
In watching the reactions to the Git-style workflows being built for Zed lakes, a couple of us have thought about extending the metaphor all the way to actually having the concept of "branches". For instance, the Zed lake already provides for the ability to delete by commit to undo mistaken data imports. However, users accustomed to Git workflows might feel even safer working with Zed lakes if they could have the have the sense of "working in a branch". So if they were sitting down to work on shaping or importing a new data source into the lake, by working in such a branch they could do their data adds/deletes off a completely separate journal while feeling there's zero disk that their changes would muck up the "main" production journal that other users/apps are dependent on. If the work in their branch ends up being a failure, they could delete the branch and it'd be as if the data never touched the lake. Or if their work is a success and they want to incorporate the data they'd already shaped and cleaned up in their branch, they could merge it into the main journal.

In thinking this through, @mccanne had the following additional thoughts:

> A branch is just another journal object that points to the main journal and we could pretty easily write the code to  merge a branch journal into the main journal (or into another branch) and the write-conflict logic will be the same as merging commits from staging to main.

Given our need to focus on other priorities, this is feeling like a priority to consider in the MVP1 timeframe.

**Comment by mccanne** [comment]
@mattnibs suggested a good improvement where there would be a separate staging area for each branch rather than at the pool level.  This will make the status command show you only the stuff you've staged to your branch and be less confusing...

**Comment by philrz** [comment]
I verified the changes in the linked PRs by running through the steps in the [lake design doc](https://github.com/brimdata/zed/blob/main/docs/lake/design.md) that had been updated as part of the changes in the linked PRs to reveal the new branch concept. I found a few glitches along the way that were ultimately addressed via the changes in #3014.

Thanks @mccanne!
