### ISSUE TITLE
get rid of compile.Custom and turn TypeSplitter and FieldCutter into Zed query operators

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#2656]

**Comment by philrz** [comment]
In Zed commit dc82704, I've verified the first take at the `explode` operator that was introduced in the linked PR. Using the example from #2221, we can break the values out into separate records as long as we specify `by` and a type name.

```
$ echo '{responders:|[10.47.3.142,10.47.8.19,10.47.8.142,10.47.8.154,10.47.21.25,10.47.21.82,10.47.22.25,10.47.24.25]|}' | zq -z 'explode responders by ip' -
{value:10.47.3.142}
{value:10.47.8.19}
{value:10.47.8.142}
{value:10.47.8.154}
{value:10.47.21.25}
{value:10.47.21.82}
{value:10.47.22.25}
{value:10.47.24.25}
```

Further enhancements to `explode` will be tracked in #2221.

Thanks @mccanne!
