### ISSUE TITLE
fix dataflow bug when cutting layout key

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#2663]
This doesn't seem to do the right thing...
```
zed compile -C -P 2 "from 'pool-ts' | cut x=ts,ts=1"
```
which gives...
```
from (
  G2eDzBUfU6IEmUSGCa5kHyXMhoO =>
    cut x=ts,ts=1;
  G2eDzBUfU6IEmUSGCa5kHyXMhoO =>
    cut x=ts,ts=1;
)
| merge ts
```
The merge here should be on `x`.  I believe this bug was in the original parallelization code so we will put the hazmat PR up and fix this later.

**Comment by philrz** [comment]
I've verified that as of Zed commit 874ac74 this is now showing a merge on `x` as expected. The updated Zed language syntax also now requires `:=` to be used for assignment.

```
$ zed -version
Version: v0.29.0-358-g874ac748

$ zed compile -C -P 2 "from 'pool-ts' | cut x:=ts,ts:=1"
from (
  G2eDzBUfU6IEmUSGCa5kHyXMhoO =>
    cut x:=ts,ts:=1;
  G2eDzBUfU6IEmUSGCa5kHyXMhoO =>
    cut x:=ts,ts:=1;
)
| merge x:asc
```

Thanks @mccanne!
