### ISSUE TITLE
zed lake serve: Improve error message when no lake root specified

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#2671]
Repro is with Zed commit cbfb2d7.

I happened to forget to set `ZED_LAKE_ROOT` or specify `-R` when attempting to run `zed lake serve`, and this was the observed output:

```
$ zed lake serve
{"level":"info","ts":1620169439.6254737,"msg":"Open files limit raised","limit":65536}
item does not exist: 
```

It took me a few minutes of head-scratching to realize my mistake. It might be helpful if `zed` had provided better guidance along the lines of:

> error: path to Zed Lake store must be specified via `-R` flag or `ZED_LAKE_ROOT` variable

**Comment by mccanne** [comment]
There's two things going on here.  "item does not exist" is a bad error message and zed lake serve uses the current directory for the lake root if not otherwise specified.  Do we want to eliminate the latter situation and force a root to be specified?

**Comment by mccanne** [comment]
We should add better errors to the storage engine (which will handle this situation), but this should wait until #2688 is merged.

**Comment by philrz** [comment]
@mccanne: You said:

> zed lake serve uses the current directory for the lake root if not otherwise specified

This is news to me, actually. I was accustomed to `zqd listen` working this way, which was why I was somewhat thrown when `zed lake serve` kicked back the error message rather than starting successfully. Granted, due to the bad-ness of the error I couldn't tell _what_ it was trying to do when it failed. Did it fail when trying to take some first steps related to setting up camp in the current directory?

I'm not wedded to the behavior of it using the current directory, but I felt it was handy and would be happy to see it return.

**Comment by philrz** [comment]
I'm reopening this one as, after attempting to verify in Zed commit 09de9ba, it seems the fix is incomplete.

As shown in the test in the linked PR, I can indeed see that for operations like `zed lake ls` it does now fail with a helpful error message.

```
$ unset ZED_LAKE_ROOT

$ zed -version
Version: v0.29.0-323-g09de9bab

$ zed lake ls
no lake path specied: use -R or set ZED_LAKE_ROOT
```

However, for the case of `zed lake serve` which was the example for which I originally opened this issue, the error message is different, but is not helping me understand the problem as well as the error message shown above.

```
$ unset ZED_LAKE_ROOT

$ zed lake serve
{"level":"info","ts":1620770749.531515,"msg":"Open files limit raised","limit":24576}
root path cannot have scheme ""
```

**Comment by philrz** [comment]
Verified in Zed commit 035b439.

Now I get a helpful error message in place of the opaque one that was shown before.

```
$ zed -version
Version: v0.29.0-345-g035b439b

$ unset ZED_LAKE_ROOT

$ zed lake serve
no lake path specied: use -R or set ZED_LAKE_ROOT
```

Thanks @mccanne!
