### ISSUE TITLE
Move to Zed Lake Service API

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#2680]
As of right now, Zed clients such as the Brim app and `zapi` are still talking to Zed Lakes through the old API. The new APIs for interacting with Zed Lakes is being brought up such that we'll be able to support both old & new for a while, then clients can be converted to use the new API as priorities allow, then the old API can be deprecated.

Here's a summary of background as I captured in a recent conversation with @mccanne. In the era of Zed Lakes when any data can be queried with any key type, it's now possible in the Zed language itself to write `from [pool] ...` as well as a key range. Therefore a client such as the Brim app is expected to prepend a user's Zed queries with this info (e.g. populating `from` with the name of the Pool the user is currently working with, or the range being populated based on the picker that's currently only used for time range and is expected to be used for any key range in the future). Right now this information goes into the search request and is translated into what the Lake expects. However, there's no way to put two "froms" in a search request (to do joins of data from multiple Pools, for example), hence our motivation to move to the new API so we can unlock more functionality.

The first order of business is to just get the new API working as part of MVP0, then we'll make the call on how soon to change the Brim app to use it, which might wait until MVP1.

**Comment by mccanne** [comment]
This is all done.
