### ISSUE TITLE
Sort with no fields ignores alias types when picking sort field

### ISSUE THREAD

**Issue by nwt** [brimdata/zed#2733]
The [`sort` documentation](https://github.com/brimdata/zed/blob/main/docs/language/processors/README.md#sort) implies that the following command will sort on field `b` because its type, `alias`, has an underlying type of `int64`. It incorrectly sorts on field `a` instead.
```sh
$ ./dist/zq -z sort - <<EOF
{a:"1",b:2 (=alias)} (=0)
{a:"2",b:1} (0)
EOF
{a:"1",b:2 (=alias)} (=0)
{a:"2",b:1} (0)
```

**Comment by philrz** [comment]
Verified in Zed commit 7adbb36.

Now the example input data is sorted by the aliased field `b`, which is the expected behavior since it resolves to an underlying numeric type.

```
$ zq -version
Version: v0.29.0-360-g7adbb368

$ cat input.zson
{a:"1",b:2 (=alias)} (=0)
{a:"2",b:1} (0)

$ zq -z 'sort' input.zson 
{a:"2",b:1 (=alias)} (=0)
{a:"1",b:2} (0)
```

Thanks @nwt!
