### ISSUE TITLE
Sort with no fields ignores nested fields when picking sort field 

### ISSUE THREAD

**Issue by nwt** [brimdata/zed#2734]
The [`sort` documentation](https://github.com/brimdata/zed/blob/main/docs/language/processors/README.md#sort) implies that the following command will sort on field `b.c` because its type is `int64`. It incorrectly sorts on field `a` instead.
```sh
$ ./dist/zq -z sort - <<EOF
{a:"1",b:{c:2}}
{a:"2",b:{c:1}}
EOF
{a:"1",b:{c:2}}
{a:"2",b:{c:1}}
```

**Comment by philrz** [comment]
Verified in Zed commit 7adbb36.

Now the example input data is sorted by the nested field `b.c`, which is the expected behavior since it's of a numeric type.

```
$ zq -version
Version: v0.29.0-360-g7adbb368

$ cat input.zson 
{a:"1",b:{c:2}}
{a:"2",b:{c:1}}

$ zq -z 'sort' input.zson 
{a:"2",b:{c:1}}
{a:"1",b:{c:2}}
```

Thanks @nwt!
