### ISSUE TITLE
zq from file ergonomics

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#2754]
Currently, if you try to use a from "file" query with zq without other arguments you get the following:
```
$ zq -z "file in.zson | pass"
zq: no such file: file in.zson | pass
```
This should work and is particularly convenient when running queries from the shell because you can easily hit ctrl-P and edit the query at the end of the command line rather than backing up over the file argument as in:
```
 zq -z "complicated | query | here | ..." long/path/with/file.zng 
```

This could be easily implemented by noting when there is one argument to zq that files with file-not-found.  Then it is parsed as a query and if it leads with a from-file AST node, then we can run the query, e.g., 
```
zc "file in.zson | pass"
{
    "kind": "Sequential",
    "procs": [
        {
            "kind": "From",
            "trunks": [
                {
                    "kind": "Trunk",
                    "source": {
                        "format": "",
                        "kind": "File",
                        "layout": null,
                        "path": "in.zson"
                    }
                }
            ]
        },
        {
            "kind": "Pass"
        }
    ]
}
```

**Comment by nwt** [comment]
Done in #3704.

```console
$ zq -version
Version: v1.9.0
$ zq -z "file in.zson | pass"
in.zson: file:///Users/noah/brimdata/zed/in.zson: file does not exist
```
