### ISSUE TITLE
"zed lake drop" causes "zapi"-level & "zed lake"-level Pool states to be out-of-sync

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#2798]
Repro is with Zed commit e425777. This issue was originally reported by a community user in a [thread on public Slack](https://brimsec.slack.com/archives/C010DR0HHMF/p1623329084040400). I'm starting this out as a bug, but I'm also prepared to have this be a "yeah don't do that" situation. :smile:  

I start by starting a Zed Lake service with an empty root.

```
$ zed -version
Version: v0.29.0-377-ge425777f

$ zed lake serve
{"level":"info","ts":1623355987.710143,"msg":"Open files limit raised","limit":24576}
{"level":"info","ts":1623355987.7117598,"logger":"core","msg":"Started"}
{"level":"info","ts":1623355987.7120798,"logger":"httpd","msg":"Listening","addr":"[::]:9867"}
...
```

First I'll show the happy path where everything works if I stick to just `zapi` commands to make changes to the Lake.

```
$ zapi create -p mypool
pool created: mypool

$ zapi ls
mypool 1tludINwNd2n259J8jWAE90r44w key ts order desc

$ zed lake ls
mypool 1tludINwNd2n259J8jWAE90r44w key ts order desc

$ zapi drop -p mypool
pool deleted: mypool

$ zed lake ls
[no output... expected!]

$ zapi ls
[no output... expected!]
```

However, if I start over and do the `drop` by using the `zed lake` command to perform the operation at the filesystem layer, checking via `zapi` to ask the Lake service for Pool state makes it seem as if the Pool still exists.

```
$ zapi create -p mypool
pool created: mypool

$ zapi ls
mypool 1tluuz7NfIhMJ5a2kQv5azH2gUD key ts order desc

$ zed lake ls
mypool 1tluuz7NfIhMJ5a2kQv5azH2gUD key ts order desc

$ zed lake drop -p mypool
pool deleted: mypool

$ zed lake ls
[no output... expected!]

$ zapi ls
mypool 1tluuz7NfIhMJ5a2kQv5azH2gUD key ts order desc
```

If I stop and restart the `zed lake serve` at this point, now the `zapi ls` no longer returns `mypool`.

Based on these symptoms, I'm guessing the Zed Lake service may reserve the right to hold some state in memory on the assumption that commands like `zed lake drop` aren't changing stuff at the filesystem layer. I'd encouraged beta users to use `zed lake` commands to give them an early jump on playing with Lakes before we'd finished adding all the equivalent commands to `zapi`, and now that we've added just about all those commands to `zapi`, maybe I just need to walk that back. OTOH if we'd like to be able to say that it's safe to manipulate the Lake directly with `zed lake` commands even while it's fronted by a Lake service, then I guess this would be a bug.

**Comment by philrz** [comment]
@mccanne looked at this issue and suspects that #2547 may address it. I'll wait and see how that plays out. Even if that addresses this one specific case, I'd then revisit the question of whether we can set expectations that filesystem-layer manipulation will _always_ be immediately reflected at the service layer.

**Comment by mccanne** [comment]
The storage layer will always prevail.  We have a bit more work to make it all work but the architecture supports it.
