### ISSUE TITLE
zson.String() problem with null

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#2818]
zson.String() is printing `null (null) (null)` for a null of type null.   We should make type null implied to fix this, which should also fix the extra decorator.

**Comment by philrz** [comment]
Verified in Zed commit b28cfe0.

As of Zed commit 6cc190b that was right before the changes in the linked PR, the `(null)` was still explicit.

```
$ zq -version
Version: v0.29.0-392-g6cc190b9

$ echo '{foo:null (null)} (=0)' | zq -z -
{foo:null (null)} (=0)
```

After the changes in the linked PR, it's now an implied type.

```
$ zq -version
Version: v0.29.0-403-gb28cfe0b

$ echo '{foo:null (null)} (=0)' | zq -z -
{foo:null}
```

Thanks @mccanne!
