### ISSUE TITLE
remove decorator space in -z output

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#2821]
The only space that appears in -z output is between a value and its decorator.  We should remove this for consistency (while keeping the space in -Z output).  e.g., `{a:1(int8)}` instead of `{a:1 (int8)}`.

**Comment by philrz** [comment]
Verified in Zed commit 1099f2f.

At Zed commit 1924d64 that was right before the changes in the linked PR, this space was present:

```
$ zq -version
Version: v0.29.0-447-g1924d649

$ echo '{"foo": 1}' | zq -z 'put foo:=int8(foo)' -
{foo:1 (int8)} (=0)
```

Now on Zed commit 1099f2f, it's gone.

```
$ zq -version
Version: v0.29.0-460-g1099f2f6

$ echo '{"foo": 1}' | zq -z 'put foo:=int8(foo)' -
{foo:1(int8)}(=0)
```

As noted above, the space is still present in the `-Z` output.

```
$ echo '{"foo": 1}' | zq -Z 'put foo:=int8(foo)' -
{
    foo: 1 (int8)
} (=0)
```

Thanks @nwt!
