### ISSUE TITLE
change join syntax to use subquery

### ISSUE THREAD

**Issue by nwt** [brimdata/zed#2839]
A join using `from` currently looks like this.
```
from (
    left => pass;
    right => pass;
) | join on left_field == right_field
```

This might be more readable if the upstream operation provides the left input and a subquery provides the right input, like this.
```
from left | join (from right) on left_field == right_field
```

**Comment by philrz** [comment]
The description text for #2836 includes a three-way `join` example I was hoping to show, but I could never come up with a workable syntax in the current implementation. When we implement this issue, I can validate it by expressing the example in the revised syntax and add it to the docs.

**Comment by mccanne** [comment]
Steve and Noah agree that we will keep join on `=` to mean strict equi-join and in the future when we have generalized join expressions, join on `==` will mean coercible equi-join.

**Comment by philrz** [comment]
The main [`join` operator docs page](https://zed.brimdata.io/docs/next/language/operators/join) now leads with the new syntax and the [join tutorial](https://zed.brimdata.io/docs/next/tutorials/join) shows several working examples that use the new syntax. The prior syntax is still available and shown in the docs as well.

Thanks @nwt!
