### ISSUE TITLE
consistent topology syntax

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#2849]
Currently, `switch`, `split`, and `from` use different conventions for denoting the termination of each parallel path.  We should unify this syntax.

The proposal is to use semi-colon termination consistently.  This would allow us to get rid of the `case` keyword in switch.  We should also have a form of switch where you can switch on an expression and have a list of cases with default instead of just a list boolean predicates, e.g., 
```
switch  _path ( 
  "conn" => ... ;
  "dns" => ... ;
  default => ... ;
) |  ...
```

**Comment by philrz** [comment]
Note: When this gets implemented, the link to this issue from the top-level [Zed language README](https://github.com/brimdata/zed/blob/main/docs/language/README.md) should be removed.

**Comment by philrz** [comment]
Verified in Zed commit 8ca4e07.

Now the parenthetical portion of `from`, `split`, and `switch` all consistently use `=>` and to indicate parallel paths, each of which is terminated by `;`.

Test data:

```
$ cat a.ndjson 
{"a": 1, "color": "blue"}

$ cat b.ndjson 
{"b": 2, "color": "red"}

$ cat c.ndjson 
{"c": 3, "color": "yellow"}

$ zq -version
Version: v0.29.0-438-g8ca4e07a
```

### `from`

```
$ cat from.zed 
from (
  file a.ndjson => put a:=a+1;
  file b.ndjson => put b:=b+1;
  file c.ndjson => put c:=c+1;
)

$ zq -z -I from.zed 
{c:4,color:"yellow"}
{a:2,color:"blue"}
{b:3,color:"red"}
```

### `split`

```
$ cat split.zed 
* | split (
  => count();
  => put color:=to_upper(color);
)

$ cat a.ndjson b.ndjson c.ndjson | zq -z -I split.zed -
{a:1,color:"BLUE"}
{b:2,color:"RED"}
{c:3,color:"YELLOW"}
{count:3 (uint64)} (=0)
```

(Eliminating the required leading`* | ` is tracked separately in #2837.)

### `switch`

```
$ cat switch.zed 
switch (
  color=="red" => put note:="the color is red";
  color=="blue" => put note:="this color is blue";
  default => put note:="unknown color: " + color;
)

$ cat a.ndjson b.ndjson c.ndjson | zq -z -I switch.zed -
{b:2,color:"red",note:"the color is red"}
{c:3,color:"yellow",note:"unknown color: yellow"}
{a:1,color:"blue",note:"this color is blue"}
```

Finally, as noted above and addressed in the second linked PR, a new alternate syntax is also available for `switch`.

### New `switch`

```
$ cat new-switch.zed 
switch color (
  "red" => put note:="the color is red";
  "blue" => put note:="this color is blue";
  default => put note:="unknown color: " + color;
)

$ cat a.ndjson b.ndjson c.ndjson | zq -z -I new-switch.zed -
{c:3,color:"yellow",note:"unknown color: yellow"}
{b:2,color:"red",note:"the color is red"}
{a:1,color:"blue",note:"this color is blue"}
```

Thanks @nwt!
