### ISSUE TITLE
optional put keyword

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#2850]
The `put` keyword should be optional, e.g., so
```
... | put x := 1 | ...
```
can be abbreviated 
```
... | x := 1 | ...
```

**Comment by philrz** [comment]
Note: When this gets implemented, the link to this issue from the top-level [Zed language README](https://github.com/brimdata/zed/blob/main/docs/language/README.md) should be removed.

**Comment by philrz** [comment]
Verified in Zed commit 59dc184.

Revisiting what's described in the initial issue text:

```
$ zq -version
Version: v0.29.0-487-g59dc1843

$ echo '{}' | zq 'x := 1' -
{x:1}
```

The docs at [https://github.com/brimdata/zed/tree/main/docs/language/operators#put](https://github.com/brimdata/zed/tree/main/docs/language/operators#put) have been updated to reflect some of the other shorthand added in the linked PR.

While testing, I noticed something didn't match up with the representation in canonical Zed as described in [https://github.com/brimdata/zed/blob/main/docs/language/README.md#operators,](https://github.com/brimdata/zed/blob/main/docs/language/README.md#operators,) so I've opened #2992 to track that.

Thanks @mattnibs!
