### ISSUE TITLE
Add merge operator to Zed language parser/AST/etc.

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#2906]
Repro is with Zed commit 4423f55.

There's currently a use of `merge` shown in the Zed language docs in the top example under [https://github.com/brimdata/zed/tree/main/docs/language#directed-acyclic-flow-graphs](https://github.com/brimdata/zed/tree/main/docs/language#directed-acyclic-flow-graphs). However, as of Zed commit 4423f55, the parser currently turns this into a filter (i.e., a search for the strings `merge` and `ts` against the output of the combined flow graph branches). Filling in the abbreviated parts of the example:

```
$ zc -version
Version: v0.29.0-443-g4423f550

$ cat merge.zed 
from PoolOne | split (
  => put foo:=1;
  => put bar:=2;
) | merge ts

$ zc -I merge.zed 
...
        {
            "expr": {
                "kind": "BinaryExpr",
                "lhs": {
                    "kind": "Search",
                    "text": "merge",
                    "value": {
                        "kind": "Primitive",
                        "text": "merge",
                        "type": "string"
                    }
                },
                "op": "and",
                "rhs": {
                    "kind": "Search",
                    "text": "ts",
                    "value": {
                        "kind": "Primitive",
                        "text": "ts",
                        "type": "string"
                    }
                }
            },
            "kind": "Filter"
        }
    ]
}
```

#2905 discusses a possible future approach when we could perhaps avoid having to expose an explicit `merge` operator. However, since that's not happening yet, and we want to show `merge` in the docs in the interim, I'm opening this issue. In the short term, I'll link to it from a note under the example that discloses how `merge` is not yet available. Time permitting, we may potentially go ahead and add `merge` before the next GA release, but since we may end up taking it out, that's not a certainty.

**Comment by philrz** [comment]
Note to self: If we do end up implementing this, make sure the ztest added in #2901 gets updated to use `merge`.

**Comment by mccanne** [comment]
This has been done...
```
% cat merge.zed
from PoolOne | fork (
  => put foo:=1
  => put bar:=2
) | merge ts
% zq -C -I merge.zed
from (
  pool PoolOne
)
| fork (
  =>
    put foo:=1
  =>
    put bar:=2
)
| merge ts
```
