### ISSUE TITLE
Update docs/lake/README.md

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#2932]
The [Zed Lake README](https://github.com/brimdata/zed/blob/main/docs/lake/README.md) has not been updated incrementally as the Zed Lake concepts have evolved, so it's become quite out of date. Meanwhile, the [Zed Lake Design](https://github.com/brimdata/zed/blob/main/docs/lake/design.md) doc has been kept current. As long as we intend to maintain both docs, we should bring the README current.

Related: #2429 has also been open for some time to track the need to use some kind of automation to protect its content from falling out of sync again, as it's been notorious for doing this in the past. However, I imagine we should worry about getting the correct content first, then worry about automation.

**Comment by philrz** [comment]
I'll take a shot at updating this after the branches PR merges.

**Comment by philrz** [comment]
@mccanne took the first step on this via #3034.

**Comment by mccanne** [comment]
This was completed as part of the big docs project.
There is more work to do here but we'll open a new issue down the road.
