### ISSUE TITLE
add journal snapshots to storage model

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#2936]
The journal currently is read a ZNG file at a time generating inefficient I/O with the storage layer.  Snapshots should be stored alongside journal entries so that only the latest snapshot need be read and the fast-forwarded to HEAD.  For time travel, the last snapshot before the "at" pointer can be read then fast-forwarded.

**Comment by nwt** [comment]
#3296 added storage and retrieval of serialized `lake/commit.Snapshot` objects to `lake/commit.Store`.
