### ISSUE TITLE
nulls in seekindex

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#2965]
@aousterh stumbled across this when using the id.orig_h as the pool key...

When the seekindex has nulls from records without pool keys or records with a pool key that has a null value, it punts.   The if-statement that rejects this case should be removed and the code that computes intersections over keyspans should be updated to handle nullsmax.

https://github.com/brimdata/zed/blob/7359b7de0f2989e809ba82b043dbb0586ef2dcb9/lake/segment/reader.go#L40

Replicate with:
```
zed lake create -p bug -orderby id.orig_h
zed lake load -p bug zq-sample-data/zeek-default/*.gz
```
Then you will see meta.last is null:
```
zed lake query -Z "from bug[objects]"
```
And this query will run slowly because the seek index isn't used:
```
zed lake query -z "from ip2 range 10.128.0.241 to 10.128.0.241 | id.orig_h == 10.128.0.241"
```

**Comment by philrz** [comment]
Verified in Zed commit cf116a83.

Circling back to Zed commit 97cb737 that was right before the changes in the linked PR, here's the repro steps with current Zed syntax showing the baseline of the noted query slowness.

```
$ zed -version
Version: v0.30.0-63-g97cb7379

$ zed lake init
using environment variable ZED_LAKE_ROOT
lake created: /Users/phil/logs

$ zed lake create -orderby id.orig_h bug
pool created: bug 1z2wC7ygSUaxizuZ7WIXdy1UdAz

$ zed lake use -p bug
Switched to branch "main" on pool "bug"

$ zed lake load zed-sample-data/zeek-default/*.gz
1z2wHGW1HvqRvq7u7N0vWb7kqOn committed

$ zed lake query -Z "from bug@main:objects"
{
    id: 0x0de8c81c96307da996fbcc8051a0802ff372c000 (=ksuid.KSUID),
    meta: {
        first: 10.0.0.111,
        last: null,
        count: 1462078 (uint64),
        row_size: 83899492
    } (=data.Meta)
} (=data.Object)

$ time zed lake query -z "from bug range 10.128.0.241 to 10.128.0.241 | id.orig_h == 10.128.0.241" > /dev/null
real	0m1.920s
user	0m3.205s
sys	0m0.227s
```

But repeating the query at Zed commit cf116a83 that has the benefit of the fix in the linked PR, now it completes much faster.

```
$ zed -version
Version: v0.30.0-64-gcf116a83

$ time zed lake query -z "from bug range 10.128.0.241 to 10.128.0.241 | id.orig_h == 10.128.0.241" > /dev/null
real	0m0.455s
user	0m0.586s
sys	0m0.055s
```

Thanks @nwt!
