### ISSUE TITLE
better ergonomics for zed default output to terminal

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#2974]
When we decided to make zng the default output format, we realized that would create problems when users send the output to a terminal without specify -z.  Thus, we added the warning...
```
writing binary zng data to terminal; override with -B or use -z for ZSON.
```
We decided this sucked less than having `-z` be the default and users (including us!) wondering why things are running correctly but so slow without realizing that everything was being sent in ZSON and parsed back to ZNG by downstream processes (the a lovely feature of auto-detection... it just works!  just not what you intended).

I propose that instead of issuing the warning above, we silently change "-f zng" to "-z" when sending stdout to a terminal unless -B is specified.

I have no idea why you would send binary output to a terminal but the flag is already there so why not leave it.

**Comment by philrz** [comment]
Verified in Zed commit 63f7117.

Revisiting the state of things at Zed commit 0f21060 right before the changes landed from the linked PR:

```
$ zq -version
Version: v0.29.0-480-g0f21060e

$ echo '{"foo": "bar"}' | zq -
writing binary zng data to terminal; override with -B or use -z for ZSON.
```

Now at Zed commit 63f7117 with the benefit of the enhancement:

```
$ echo '{"foo": "bar"}' | zq -
{foo:"bar"}
```

And if the output is _not_ a terminal, we still get binary ZNG, so our pipelines should still get max performance.

```
$ echo '{"foo": "bar"}' | zq - > /tmp/my.zng

$ cat /tmp/my.zng
?fobar?

$ zq -f zng /tmp/my.zng 
{foo:"bar"}
```

Thanks @mccanne!
