### ISSUE TITLE
in-memory caching for commit objects and journal entries

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#3002]
We need a sensible approach for caching objects in memory that are read from storage. Right now, the tables aren't limited, so problems will arise at scale.

We should also persist journal and commit-history snapshots. The design of this will interplay with the in-memory caching decisions.

@noah suggested github.com/hashicorp/golang-lru will be useful...

Ultimately, we will move the commit-history into a sub-pool but this is beyond the scope of this near-term issue.

This relates to the perf tests in #3027

**Comment by mccanne** [comment]
We need a general solution to caching immutable cloud objects both in memory and nearby, but for now, the in-memory cache in the snapshot logic should be limited.  This should be done closely tied to the November goal to build cache immutable snapshots in storage.

**Comment by nwt** [comment]
#3318 and #3322 take care of this.
