### ISSUE TITLE
consts in literal switch cases

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#3003]
The literal version of switch should be able to take constant identifiers in addition to literals.  e.g., while this works because it's expression version of switch cases:
```
const s1=<big type value>
switch (
  typeof(this)==s1 => postal_code:=int64(zip) | drop zip ;
  default => pass ;
)
```
This variation of it does not parse
```
const s1=<big type value>
switch (
  s1 => postal_code:=int64(zip) | drop zip ;
  default => pass ;
)
```
We need to change the parser and the semantic and kernel modules to handle consts in the literal switch cases.

**Comment by philrz** [comment]
Verified in Zed commit b01f993.

Revisiting Zed commit da27123 before the fix, a repro of the original parse error:

```
$ cat data.zson 
{foo:"bar",zip:"94107"}
{foo:"baz",country_code:"UK"}

$ cat repro.zed 
const s1={foo:string,zip:string}
const s2={foo:string,country_code:string}
switch typeof(this) (
  s1 => postal_code:=int64(zip) | drop zip ;
  default => pass ;
)

$ zq -version
Version: v0.29.0-489-gda271238
08:14:16-phil@PhilMac:~/work/zed-3003$ zq -I repro.zed data.zson
zq: error parsing Zed in repro.zed at line 4, column 6:
  s1 => postal_code:=int64(zip) | drop zip ;
 === ^ ===
```

Now in Zed commit b01f993 with the benefit of the fix, the parse error is gone and the logic of the appropriate `switch` case fires.

```
$ zq -I repro.zed data.zson
{foo:"baz",country_code:"UK"}
{foo:"bar",postal_code:94107}
```

Thanks @mccanne!
