### ISSUE TITLE
typeID-less zson

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#3005]
Henri had an idea a while back to eliminate the integer type IDs from ZSON and make each line self contained.

Now that we are further along and typedefs can be redefined, I realize we can implement this idea without changing the ZSON spec at all, but just have an option to output ZSON in this form.

e.g., this zson
```
{x:1(uint8)}(=0)
{x:1}(0)
{p:80(port=(uint16))}(=1)
{p:81}(1)
```
could be formatted like this:
```
{x:1(uint8)}
{x:1(uint8)}
{p:80(port=(uint16))}
{p:81(port=(uint16))}
```
Note that this latter ZSON is perfectly valid and parseable by the current zq and both inputs format to exactly the same ZNG (of course).

The typedef binding should bind within the DFS traversal of the record, e.g.,
```
{p:80(port=(uint16)), p2:8080(port)}
```
 This seems less cryptic and more user friendly so should be less off-putting in demos and articles.

**Comment by philrz** [comment]
Verified in Zed commit f5fef7c.

After the changes in the linked PR, the default ZSON output now matches the proposal shown in the original issue text.

```
$ cat input.zson 
{x:1(uint8)}(=0)
{x:1}(0)
{p:80(port=(uint16))}(=1)
{p:81}(1)

$ zq -version
Version: v0.29.0-504-gf5fef7c0

$ zq input.zson 
{x:1(uint8)}
{x:1(uint8)}
{p:80(port=(uint16))}
{p:81(port=(uint16))}
```

brimdata/zed-sample-data#29 tracked the changing of the [ZSON-format Zeek zed-sample-data](https://github.com/brimdata/zed-sample-data/tree/main/zson) to match this.

Thanks @mccanne!
