### ISSUE TITLE
"zed lake delete" needs a ztest & help text adjustment

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#3012]
While reviewing a revision of the Zed lake design doc as a user, I got the mistaken impression that `zed lake delete` could be used on commits, not just objects. @mccanne confirmed this is as designed, though.

> That behavior is now handled by `revert`.  `delete` is still useful (delete individual data objects instead of reverting a commit) and I meant to make a test for it so the issue should just be create a test for delete.

In addition to creating a test, it looks like the help text also needs to be adjusted, since as of Zed commit b2643c2 it still indicates can take "a list of commit tags".

```
$ zed -version
Version: v0.29.0-493-gb2643c22

$ zed lake delete -h
NAME
    zed lake delete - delete commits or data objects from a pool branch

USAGE
    delete -p pool[@commit] id [id ...]

OPTIONS
    -message commit message
    -p name of pool
    -q quiet mode (default "false")
    -user user name for commit message (default "phil@PhilMac.local")
    
    [lake flags]
    -R URI of path to Zed lake store (default "/Users/phil/logs")
    
    [zed flags]
    -cpuprofile write cpu profile to given file name
    -h display help (default "false")
    -hidden show hidden options (default "false")
    -memprofile write memory profile to given file name
    -version print version and exit (default "false")

DESCRIPTION
    "zed lake delete" takes a list of commit tags and/or data object tags
    in the specified pool branch and deletes all of the corresponding data
    objects. Once the delete operation completes, the deleted data is no
    longer seen when read data from the pool.

    No data is actually removed from the lake.  Instead, a delete operation
    is an action in the pool's commit journal.  Any delete can be "undone"
    by adding the commits back to the log using "zed lake add".
```

As for the Zed lake design doc, I've already got a branch in progress with some other fixes, so I'll propose the fix to that one.

**Comment by mattnibs** [comment]
Completed with https://github.com/brimdata/zed/pull/3216
