### ISSUE TITLE
change "checkout" to "use"

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#3025]
Since zed lake checkout doesn't have a local copy of the "repo" and it's pretty different compared to git checkout, we should use a different command name to refer to setting the HEAD pointer.  The current contender is "use".

**Comment by philrz** [comment]
Verified in Zed commit d10df29.

`use` now takes the place of `checkout`, e.g.:

```
$ zed -version
Version: v0.29.0-508-gd10df299

$ zed lake init
using environment variable ZED_LAKE_ROOT
lake created: /Users/phil/logs

$ zed lake create logs
pool created: logs 1xpSm3yaXEIE8R6SNUJ7pLuscHs

$ zed lake use -p logs
Switched to branch "main" on pool "logs"

$ zed lake load *
1xpSp5kh4nqO1HobIyAR0znk00v committed
```

Thanks @mccanne!
