### ISSUE TITLE
Performance degradation as commits accumulate

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#3027]
@mccanne identified a performance exposure as the commit log gets long, so I ran the following script on my Mac laptop to quantify the degradation. The test data is the first Zeek `conn` record from the [zed-sample-data](https://github.com/brimdata/zed-sample-data) in ZNG format.

```
#!/bin/sh
rm -rf $ZED_LAKE_ROOT
zed lake init
zed lake create logs
zed lake checkout logs@main
NUM=1
while true; do
  echo "Performing commit #${NUM}:"
  time zed lake load one_conn.zng
  echo
  echo "Performing minimal query:"
  time zed lake query 'head 1' > /dev/null
  echo
  NUM=$(expr $NUM + 1)
done
```

As shown in the chart below, the simple `head 1` query goes from 23 milliseconds when the pool contains just the one commit to 4+ seconds when there's 21k commits.

![](https://user-images.githubusercontent.com/5934157/132365667-9e7d8c86-d31e-47d1-b73b-0bf52462cb68.png)

**Comment by mccanne** [comment]
Just to be clear, this is all "by design" and shall be taken care of by not-yet-implemented cats and snanpshots of the commit history.  Since everything is immutable (and since ZNG can be simply concatenated), it is trivial to concatenate a commit history at any object and to create snapshots of the current state of the object store at any commit.

**Comment by mccanne** [comment]
I'm also curious about our commit-per-second speed.  There are some easy things here we can do here to speed this up too...

**Comment by mccanne** [comment]
(The commit history overhead slows down the commits because you have to build the commit state for each commit made...)

**Comment by mccanne** [comment]
Also query times are slow because of the massive number of single-record ZNG objects in the store.  Small commits will be address with LSM-style rollups via the forthcoming compat command (which is trivial to implement... just read a bunch of small objects in a mergescan and write them back).

**Comment by philrz** [comment]
The addition of `zed compact` via #3940 justifies revisiting the tests performed here to see if compacting the objects from the large number of commits might improve query performance.,

As the initial tests were performed back in September of 2021, it first seemed appropriate to re-baseline by repeating the original test with current Zed. The Zed commands have changed a bit in the time since, so here's an update of the repro script that's in sync with current Zed commit 28029f06.

```
#!/bin/sh
export ZED_LAKE="$HOME/.zed-3027-lake"
rm -rf $ZED_LAKE
zed init
zed create logs
zed use logs@main
NUM=1
while true; do
  echo "Performing commit #${NUM}:"
  time zed load one_conn.zng
  echo
  echo "Performing minimal query:"
  time zed query 'head 1' > /dev/null
  echo
  NUM=$(expr $NUM + 1)
done
```

While I didn't let it run for as many hours, since the prior results indicated a linear degradation, I repeated the test up through 7000 commits. Here's results that chart the slower commit and query times as the number of commits increases.

![image](https://user-images.githubusercontent.com/5934157/177426839-4472e57e-1a12-4a4e-85e7-01827894b0b4.png)

While the results are roughly similar to what we saw in the past, comparing just the commit times then vs. now, we see that the time per commit is actually a bit _worse_ now than it was before.

![image](https://user-images.githubusercontent.com/5934157/177426993-5f64fee6-032a-497e-979a-8d294317af81.png)

Whereas the query times are slightly _better_ now.

![image](https://user-images.githubusercontent.com/5934157/177427040-15679cc9-5c1e-49d0-ab98-e5fc90bc435c.png)

Finally, we see that we're able to compact the objects from the 7000 commits in 1.438 seconds.

```
$ ulimit -n 1000000
$ time zed compact $(zed query -f text 'from logs@main:objects | yield "0x${hex(id)}"')
2BXimaptwtcBm5U9vcixBureyxA compaction committed

real	0m1.438s
user	0m2.575s
sys	0m1.232s
```

Now the time for our `head 1` query is 0.444 seconds, which is almost 3x better than the 1.26 seconds it took for the same query before compacting.

```
$ time zed query 'head 1' > /dev/null

real	0m0.444s
user	0m0.471s
sys	0m0.260s
```
