### ISSUE TITLE
flatten function

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#3049]
We should have a flatten function like we have an unflatten function.

The mechanism is all there as its used by the table and csv writers.  We just need to wrap it as a function call in package expr and add a case to compiler/kernel next to unflatten.

**Comment by philrz** [comment]
This was added some time ago. In #3548 it was initially implemented to return a map, then in #3624 and #3625 it was changed to instead return an array of key/value records. The docs at https://zed.brimdata.io/docs/next/language/functions/flatten show a working example that's regularly run through automation.
