### ISSUE TITLE
Can't cut a field in a nested record using rec["..."] notation

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#3071]
Repro is with Zed commit 4f67f3e.

If I have a field in a nested record, I can do field/value matches as well as operations like `cut` using the simple dot notation.

```
$ zq -version
Version: v0.30.0-7-g4f67f3ee

$ echo '{"foo": {"bar": "text", "baz": "more"}}' | zq 'foo.bar=="text"' -
{foo:{bar:"text",baz:"more"}}

$ echo '{"foo": {"bar": "text", "baz": "more"}}' | zq 'cut foo.bar' -
{foo:{bar:"text"}}
```

However, if I have a field name that contains special characters and hence needs the string-quoted references introduced in #1291, only the field/value match works. The `cut` causes an error.

```
$ echo '{"foo": {"bar with space": "text", "baz": "more"}}' | zq 'foo["bar with space"]=="text"' -
{foo:{"bar with space":"text",baz:"more"}}

$ echo '{"foo": {"bar with space": "text", "baz": "more"}}' | zq 'cut foo["bar with space"]' -
invalid expression on lhs of assignment
```

**Comment by mccanne** [comment]
Good one.  This might be most easily addressed by having the semantic analyzer change an index with a constant into an explicit field access as cut requires an l-value, i.e., changing BinaryExpr with op `[` and a string-constant index  into a dag.Path.

**Comment by philrz** [comment]
Verified in Zed commit 84fedec.

Now I can use the `rec["..."]` notation to successfully `cut` a field whose name includes special characters.

```
$ zq -version
Version: v1.2.0-76-g84fedec6

$ echo '{"foo": {"bar with space": "text", "baz": "more"}}' | zq 'cut foo["bar with space"]' -
{foo:{"bar with space":"text"}}
```

Thanks @nwt!
