### ISSUE TITLE
Post data from Python

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#3103]
The [Python client](https://github.com/brimdata/zed/tree/main/python/zed) is currently only scoped to handle queries. @mccanne noted that we should add an easy way to post data from the Python client as well.

**Comment by garrisonhess** [comment]
Hi @philrz!

I have a little example of pulling Reddit post/comment data into a zpool in the linked python code.
https://github.com/garrisonhess/zeddit/blob/44d2783963294e07eed9673df260a1ecfa4b8a1d/ingest_from_praw.py#L23

- A method for checking which pools exist in the lake using python would be helpful.  It could return a list of tuples (poolname, poolid, any other metadata).
- The ability to create a pool might also be helpful.  As you can see, I made a dirty subprocess call to create a pool.

It might also be interesting to consider what a native python "Pool" object would look like.  From a data science perspective, I'm currently thinking about zpools as scalable, persistent (Pandas) dataframes with much better querying.  Maybe that isn't the right way to think about them, but I think there may be something in that direction.

Any perspective you might have on this would be great!

**Comment by nwt** [comment]
@garrisonhess: Though #3232 doesn't add a method for listing pools, I think it does add everything needed by https://github.com/garrisonhess/zeddit/blob/44d2783963294e07eed9673df260a1ecfa4b8a1d/ingest_from_praw.py.
