### ISSUE TITLE
zed emit command

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#3143]

**Comment by mccanne** [comment]
We talked about this being "from const <expr>[,<expr>]"

**Comment by philrz** [comment]
We've since decided we can live without this command since we discovered `seq` at the shell which seems like it could cover most use cases, e.g.:

```
$ zq -version
Version: v1.1.0-58-gd97c452a

$ seq 5 | zq -f table 'sum(this),count()' -
sum count
15  5
```
