### ISSUE TITLE
querying ZNG slows down with more types

### ISSUE THREAD

**Issue by aousterh** [brimdata/zed#3146]
I created two ZNG files, each with 1 million simple ZNG values (see below). The only difference between the two files is how many distinct types each file spans (19 vs. 156), which is controlled by varying the name of the first field in each value. However, querying the file with more types takes noticeably longer:

```
$ zq -version
Version: v0.31.0
$ zq "head 3" data_19_types.zng
{f0000000:"E",value:536}
{f0000001:"j",value:251}
{f0000002:"K",value:439}

$ time zq -z -validate=false "sum(value)" data_19_types.zng
{sum:500165493}
real    0m0.282s
user    0m0.588s
sys     0m0.028s

$ time zq -z -validate=false "sum(value)" data_156_types.zng
{sum:500165493}

real    0m1.033s
user    0m1.836s
sys     0m0.124s
```

With fewer than 19 types, query times only decrease slightly, to about 0.15 s with 1 type and 0.16 s with 2 types. With more than 156 types, query times only increase slightly, to about 1.1 s with 1250 types and 1.2 s with 10000 types. So there seems to be a significant change in query time somewhere between 19 and 156 types, but not with other changes in the number of types.

[data_19_types.zng.zip](https://github.com/brimdata/zed/files/7282467/data_19_types.zng.zip)
[data_156_types.zng.zip](https://github.com/brimdata/zed/files/7282468/data_156_types.zng.zip)

**Comment by nwt** [comment]
I'm not sure exactly why but the performance difference went away in v1.0.0.

```console
$ zq -version
Version: v1.0.0

$ time zq -z -validate=false "sum(value)" data_19_types.zng
{sum:500165493}

real	0m0.382s
user	0m0.489s
sys	0m0.049s

$ time zq -z -validate=false "sum(value)" data_156_types.zng
{sum:500165493}

real	0m0.376s
user	0m0.477s
sys	0m0.046s
```
