### ISSUE TITLE
uniform docs for operators, aggregators, and functions

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#3150]
We should have a clean and uniform way to document operators, aggregators, and functions.  We will define conventions where the Go implementation of any such entity has a godoc comment with a URL that points to the markdown docs for that entity.

We should inventory the existing code and make sure everything conforms to this new approach.  There is some goofiness in `compiler/expr/expr.go:compileCall()` that should be cleaned up with a simpler API into the expr package for compiling these entities.

We should document this convention in CONTRIBUTING.md

Any PRs with such additions must follow these conventions.

**Comment by philrz** [comment]
Consensus during an issue scrub is that the way this is handled via Docusaurus now is adequate uniform docs handling for [operators](https://zed.brimdata.io/docs/next/language/operators/), [aggregators](https://zed.brimdata.io/docs/next/language/aggregates/), and [functions](https://zed.brimdata.io/docs/next/language/functions/). Therefore I'm closing this one.
