### ISSUE TITLE
length of record should be number of fields

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#3157]
I was curious how many columns were in a `fuse` output so I piped the output to `cut len(this)` and got `1` for every record.

It seems more intuitive that the length of a record should be the number of fields/columns it contains.  Not sure where the 1 is coming from.

**Comment by philrz** [comment]
@mccanne: Can you share your test data? With random test data I can't reproduce this on the latest Zed.

```
$ zq -version
Version: v0.31.0-3-gc361fd52

$ cat data.ndjson 
{"foo": "bar", "one": "two"}
{"foo": "bar", "one": "two", "three": "four"}

$ zq 'cut len(this)' data.ndjson 
{len:2}
{len:3}

$ zq 'fuse | cut len(this)' data.ndjson 
{len:3}
{len:3}
```

**Comment by mccanne** [comment]
Closind due to operator error :-)
