### ISSUE TITLE
index files should be zst

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#3163]
This is low priority but index files should be columnar once the zst format matures a bit.  It will make looking up key values more efficient.  Since the zst engine will ultimately support pushdown searches, we could use that to do faster lookups.

On the other hand, the bottleneck to a search lookup is fetching the data so this might not make much difference though caching may make a difference.

**Comment by philrz** [comment]
@mccanne remarked that he thinks ZNG will be better for indexes in the long run, so closing this as a "wontfix".
