### ISSUE TITLE
Index predicates: allow more than just astzed.Primitive

### ISSUE THREAD

**Issue by mattnibs** [brimdata/zed#3182]
Currently you can create an index rule that will index a non-primitive value. However when querying on an indexed field, for example, for non-primitive value, the value will not be searched for in the index pass of the query. This is because the compiler optimize pass, which decides which expressions in a filter to lookup in the index, ignores any value that is not an astzed.Primitive.

This functionality should be extended to include the other zed complex types (e.g. Record, Map, Arrays, etc). There's a catch here; the compiler SHOULD ignore values in a zed complex type that has child expressions that cannot be resolved by the compiler to a zed.Primitive. For example, the filter `foo == {bar:baz+1}` should be ignored by the index since the value of `bar` is dependent on the adjacent record value `baz` that we'll only know once the record is retrieved. However the filter expression `foo == {bar:1}` should be used. Bonus points if `foo=={bar:1+1}` also gets recognized as an indexable predicate.

**Comment by nwt** [comment]
Closing because #4972 removed the index package.
