### ISSUE TITLE
more fully featured index predicate expressions

### ISSUE THREAD

**Issue by mattnibs** [brimdata/zed#3183]
Right now the optimize pass that computes what part of a filter expression can be used in an index lookup is kind of dumb; it merely creates a list of field equal expression. The index then takes this list and does a look up for each field/value combination and if it has at least one match among the list, the data object is scanned. There's some features in a filter expression that if taken into account could speed up the index:
- Binary `and` operations
- `>`, `>=`, `<`, `<=` operators
- `in` operators

## And operations
If you are searching for a chain of `or` key/value expressions this works fine (e.g. `foo == 1 or bar == 2`), but what if your query looks like `foo == 1 bar == 2`? While currently an object would be scanned if there is a match for `foo == 1` or `bar ==2` but ideally you would only scan the object if both predicates exist in the index.

## gt, gte, lt, lte operators

Since an index is essentially a list of ordered values we could check an index to see if there are any values that meet these conditions

## in operators

There's two flavors of lookups here. The first is seeing if an index has values within a range (e.g. an ip subnet). Here the logic is similar to the comparator operators mentioned above. The second is seeing if an index has a match amongst a set of values. This is will be the same as doing a chan of `or` index lookups on all the members of the set.

## != operators
~~Additionally the optimize pass completely ignore unary expressions and `!=` comparators which is another area where the index could be used to filter out objects. XXX I am recalling some trickiness here in previous incarnations of index having to do with the fact that the index is looking at batches of records and not individual records and the naive approach created some false negatives with `!=` expressions. I do not recall the exact situations, I need to dig back in the old source code and figure this out.~~
EDIT You cannot actually use the `!=` operation in the index because while an index may contain a value, there may be a record that does not contain that value. For instance a naive implementation for the query `x != 1`, would skip a data object if there was a hit in the index for `x == 1`, but there could be a whole of records in the data object where `x != 1` is true.

## unary operations
For the same reason that you can't use != operators, I am skeptical that use of the unary expression in an index filter. I need to fully think this case through.

**Comment by nwt** [comment]
Closing because #4972 removed the index package.
