### ISSUE TITLE
fuzzy string matching

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#3200]
We should have functions for fuzzy string matching.

Postgres has a nice set of options to consider:

https://www.postgresql.org/docs/9.1/fuzzystrmatch.html

It looks like there are so open-source Go implementations of some of these algorithms...

**Comment by philrz** [comment]
We attempted a [poll](https://brimdata.slack.com/archives/CTT24051C/p1663192286626839) of the community to see if there were opinions about a preferred fuzzy matching algorithm to start with, and with a whopping single vote for Levenshtein, we've decided to try that one first. 😉

**Comment by philrz** [comment]
Verified in Zed commit 28f95a3.

```
$ echo '{"name": "Phillip"}' | zq -Z 'yield {name, distance_1: levenshtein(name, "Philip"), distance_2: levenshtein(name, "Phil")}' -
{
    name: "Phillip",
    distance_1: 1,
    distance_2: 3
}
```

Thanks @nwt!
