### ISSUE TITLE
zapi drop fails silently with no server

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#3248]
If there is no zed service, `zapi drop` exits with no indication of failure, e.g.,
```
% zapi ls
Post "http://localhost:9867/query": dial tcp [::1]:9867: connect: connection refused
% zapi drop foo
%
```
BTW, we should also make a better error message for service unavailable.

**Comment by mccanne** [comment]
Also if you drop a pool that doesn't exist (i.e., because typo), zapi drop silently exits.

**Comment by nwt** [comment]
> BTW, we should also make a better error message for service unavailable.

I created #3312 for this.
