### ISSUE TITLE
zapi load fails oddly when zq works fine

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#3271]
This is really weird.

Run a zed lake and create a bug pool:
```
zapi create bug 
zapi use bug@main
```
These work:
```
echo '{v:|["x"]|}' | zapi load -
echo '{v:|["1","x"]|}' | zapi load -
```
But these do not...
```
echo '{v:|["x","1"]|}' | zapi load -
echo '{v:|["1","1"]|}' | zapi load -
```
while this works...
```
echo '{v:|["x","1"]|}' | zq -
echo '{v:|["1","1"]|}' | zq - 
```

**Comment by mccanne** [comment]
Also, when this bug was hit in the middle of the ZSON file on zapi load, the records up to that point were commited and the rest were dropped... I think the whole commit should fail and be fixed by the client if an error liek this is encounetered, or at least the behavior should be specifiable.

**Comment by nwt** [comment]
The problem is that `zapi load` isn't normalizing sets when it translates ZSON to ZNG.

**Comment by nwt** [comment]
> Also, when this bug was hit in the middle of the ZSON file on zapi load, the records up to that point were commited and the rest were dropped... I think the whole commit should fail and be fixed by the client if an error liek this is encounetered, or at least the behavior should be specifiable.

#3274 covers this.
