### ISSUE TITLE
group-by bug with array ref

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#3291]
For the zson below, we get different answers for this (incorrect):
```
zq "by callee:=stack[2]" bug.zson

{callee:"__tcp_transmit_skb"}
```
vs this (correct):
```
zq "cut callee:=stack[2] | by callee" bug.zson

{callee:"tcp_v4_send_ack"}
{callee:"udp_sendmsg"}
{callee:"tcp_conn_request"}
{callee:"__tcp_transmit_skb"}
```

**Comment by mccanne** [comment]
[bug.txt](https://github.com/brimdata/zed/files/7582114/bug.txt)

**Comment by mccanne** [comment]
The old logic in the group-by operator blocks the type when an expression error occurs (including ErrMissing).  We should relax this to properly handle Missing value semantics.

**Comment by philrz** [comment]
I've verified that this started working as of Zed commit 07ddc90 that's associated with #3368.

Now both queries return the same result.

```
$ zq -version
Version: v0.33.0-41-g07ddc902

$ zq "by callee:=stack[2]" bug.zson
{callee:"tcp_conn_request"}
{callee:"__tcp_transmit_skb"}
{callee:"missing"(error)}
{callee:"tcp_v4_send_ack"}
{callee:"udp_sendmsg"}

$ zq "cut callee:=stack[2] | by callee" bug.zson
{callee:"tcp_conn_request"}
{callee:"__tcp_transmit_skb"}
{callee:"missing"(error)}
{callee:"tcp_v4_send_ack"}
{callee:"udp_sendmsg"}
```

Note that both also now include the "missing" error, which is in sync with @mccanne's statement in #3368:

> Missing values are now generally not ignored in group-bys, cut, put etc. If you want to ignore them in these context, you can wrap the underlying expressions in the new quiet() function...

Thanks @mccanne!
