### ISSUE TITLE
404 Client Error when contacting Brim API

### ISSUE THREAD

**Issue by belveruski** [brimdata/zed#3293]
Hi, 

Python script to contact the API at http://localhost:9867
```python
import zqd as zqd
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

#space = 'tzng'
space='2020-09-01-Emotet-epoch-3-infection-with-Trickbot-gtag-mor119.pcap'

zql = '_path=="conn" | cut id.orig_h, id.resp_h, proto | sort id.orig_h, id.resp_h'

# Create ZQD client instance
c = zqd.Client()  

# Send ZQL query to ZQD
s = c.search(space, zql)

# Create dataframe and flatten json/dictionary
df = pd.json_normalize(s)
```

I have the following error when i run the script
```text
HTTPError                                 Traceback (most recent call last)
<ipython-input-16-594608269f0f> in <module>
     13 
     14 # Send ZQL query to ZQD
---> 15 s = c.search(space, zql)
     16 
     17 # Create dataframe and flatten json/dictionary

~/.local/lib/python3.8/site-packages/zqd.py in search(self, space_name, zql)
     20 
     21     def search(self, space_name, zql):
---> 22         raw = self.search_raw(space_name, zql)
     23         zjson = take_zjson(raw)
     24         return decode_zjson(zjson)

~/.local/lib/python3.8/site-packages/zqd.py in search_raw(self, space_name, zql)
     27         body = {
     28             'dir': -1,
---> 29             'proc': self.ast(zql),
     30             'space': self.spaces()[space_name]['id'],
     31         }

~/.local/lib/python3.8/site-packages/zqd.py in ast(self, zql)
     16     def ast(self, zql):
     17         r = self.session.post(self.base_url + "/ast", json={'zql': zql})
---> 18         r.raise_for_status()
     19         return r.json()
     20 

~/.local/lib/python3.8/site-packages/requests/models.py in raise_for_status(self)
    939 
    940         if http_error_msg:
--> 941             raise HTTPError(http_error_msg, response=self)
    942 
    943     def close(self):

HTTPError: 404 Client Error: Not Found for url: http://127.0.0.1:9867/ast
```
Brim is correctly launch with the PCAP file and the Zed Lake server is correctly listening on 127.0.0.1:9867. 

**Brim version**: v0.28
**Zed Version**: v0.33.0

Thank you for your help.

**Comment by nwt** [comment]
@belveruski: Looks like you're using an old version of the Python client.

To get this to work, you'll first need to install a client version that matches your Brim and Zed versions.
```sh
pip3 install "git+https://github.com/brimdata/zed@v0.33.0#subdirectory=python/zed"
```

Then, since the package name and API have changed, you'll need to update your Python script.
```py
import zed
import pandas as pd

space = '2020-09-01-Emotet-epoch-3-infection-with-Trickbot-gtag-mor119.pcap'
query = f'from {space} | _path=="conn" | cut id.orig_h, id.resp_h, proto | sort id.orig_h, id.resp_h'
c = zed.Client()  
s = c.query(query)
df = pd.json_normalize(s)
```

**Comment by belveruski** [comment]
> @belveruski: Looks like you're using an old version of the Python client.
> 
> To get this to work, you'll first need to install a client version that matches your Brim and Zed versions.
> 
> ```shell
> pip3 install "git+https://github.com/brimdata/zed@v0.33.0#subdirectory=python/zed"
> ```
> 
> Then, since the package name and API have changed, you'll need to update your Python script.
> 
> ```python
> import zed
> import pandas as pd
> 
> space = '2020-09-01-Emotet-epoch-3-infection-with-Trickbot-gtag-mor119.pcap'
> query = f'from {space} | _path=="conn" | cut id.orig_h, id.resp_h, proto | sort id.orig_h, id.resp_h'
> c = zed.Client()  
> s = c.query(query)
> df = pd.json_normalize(s)
> ```

Thanks for the reply, i have installed a new version  that match with my Brim and Zed versions, it works now but i have another python error on the parsing:

```text
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    s = c.query(query)
  File "/home/user/anaconda3/lib/python3.8/site-packages/zed.py", line 60, in query
    return decode_raw(self.query_raw(query))
  File "/home/user/anaconda3/lib/python3.8/site-packages/zed.py", line 65, in query_raw
    self.__raise_for_status(r)
  File "/home/user/anaconda3/lib/python3.8/site-packages/zed.py", line 76, in __raise_for_status
    raise RequestError(error, response)
zed.RequestError: error parsing Zed at column 10:
from 2020-09-01-Emotet-epoch-3-infection-with-Trickbot-gtag-mor119.pcap | _path=="conn" | cut id.orig_h, id.resp_h, proto | sort id.orig_h, id.resp_h
     === ^ ===
```

**Comment by nwt** [comment]
@belveruski: Looks like quotes are required around that space name, like this.

**Comment by nwt** [comment]
@belveruski: Looks like quotes are required around that pool name. (Pools used to be called spaces.)

**Comment by nwt** [comment]
@belveruski: I've edited https://github.com/brimdata/zed/issues/3293#issuecomment-981141606 to include the quotes.

**Comment by belveruski** [comment]
> @belveruski: Looks like quotes are required around that pool name. (Pools used to be called spaces.)

It's works, i'm very grateful, i follow this guide on Medium "[Visualizing IP Traffic with Brim, Zeek and NetworkX](https://medium.com/brim-securitys-knowledge-funnel/visualizing-ip-traffic-with-brim-zeek-and-networkx-3844a4c25a2f)" written by Olivier Rochford but it not up to date so I will try to follow it and update it.
