### ISSUE TITLE
consecutive top-level ZSON type values

### ISSUE THREAD

**Issue by nwt** [brimdata/zed#3299]
The ZSON specification allows top-level values of any type, but the identical syntax for type decorators and type values creates an ambiguity: Is `(type) (type)` a single, decorated value or two consecutive values? We should resolve the ambiguity.

**Comment by mason-fish** [comment]
I've verified that the top-level ZSON does not have to be a record. I ran into an issue with adding a filter to data that wasn't within a top level record but that is meant to be addressed in a different issue. Thanks, @nwt!

**Comment by mccanne** [comment]
This is fixed with the angle bracket syntax for type values.
