### ISSUE TITLE
format flag day 2021

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#3344]
Update the ZNG, ZSON, and ZJSON implementations to conform with the updates to the Zed formats as documented in PR #3319.

**Comment by philrz** [comment]
@mccanne indicated that these updates to the implementations have been completed. While I'm not 100% sure which PRs covered them, based on titles/timing, it looks like #3477 is the one for ZNG and #3505 is the one for ZJSON. I don't see a single grand PR for ZSON, but #3454, #3459, and #3498 may be related.
