### ISSUE TITLE
dynamic math aggregators

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#3357]
Rework math aggregators to be more robust and promote themselves to the proper type instead of determining the fixed type from the first value.

**Comment by philrz** [comment]
I've verified via binary search that this got fixed at Zed commit 0a48345, which is associated with the changes in #3826.

To show a repro of the original issue, at Zed commit ed65f28 that was right before the fix, we see that `sum()` locked in the integer type based on the first value read.

```
$ cat data.zson 
{a: 2}
{a: 1.2}

$ zq -version
Version: v1.0.0-79-ged65f282

$ zq -z 'sum(a)' data.zson 
{sum:3}
```

Now at current Zed commit 480d4fa that has the benefit of the fix, the float type is maintained as one would expect.

```
$ zq -version
Version: v1.2.0-43-g480d4fa9

$ zq -z 'sum(a)' data.zson 
{sum:3.2}
```

Thanks @mattnibs!
