### ISSUE TITLE
add WarningsFilter to filter Zed warnings and write to stderr

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#3389]
With the nuke-driver branch, the warnings channel is gone and warnings are written directly into the resulting Zed output.

We should implement a simple WarningsFilter that wraps a zio.Reader that would filter out these warnings and write them to stderr for zq and zed query.

We might want to create `type warning = error`

**Comment by philrz** [comment]
This is obsolete because the warnings channel is gone.
