### ISSUE TITLE
fix type grammar to match new ZSON syntax

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#3452]
Instead of 
```
type t = {a:port=(int16)} 
```
we should say 
```
type t = {a:port=<int16>} 
```

**Comment by philrz** [comment]
I can see that a couple changes were made in this area, with the current state reflected by the changes in #3559 such that there's no longer parens _nor_ angle brackets, e.g.:

```
$ zq -version
Version: v1.2.0-49-g9c0f0973

$ echo '{"addr": "192.168.0.1", "port": 80}' | zq -z 'type socket = {addr:ip,port:port=uint16} shape(socket)' -
{addr:192.168.0.1,port:80(port=uint16)}(=socket)
```

However, while I was confirming that, I did notice the docs are currently out of sync with the implementation, so I've opened #4086 to fix that. Also, when attempting the angle bracket syntax just to see what would happen, I saw a crash, but per https://github.com/brimdata/zed/issues/3899#issuecomment-1247007116 a fix for this may already be in the works.

Closing this one as completed.
