### ISSUE TITLE
fix intermittent problem with order of union

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#3499]
The collect union test seems to fail occasionally based on the order of the types in the union.  We will disable the test and created this issue to fix it...

https://github.com/brimdata/zed/runs/4928520319?check_suite_focus=true

This should be addressed by the fix to have a canonical order of types in the union as defined in the Zed 2021 data model.

**Comment by mattnibs** [comment]
Resolved with https://github.com/brimdata/zed/pull/3533
