### ISSUE TITLE
comparisons of complex values

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#3578]
Right now comparisons of complex values don't work.

We should be able to say 
```
{a:1}=={a:1}
```
(true)

and 
```
[1,2,3]==[4,5,6]
```
(false)

in particular, `x=={y:1}` should work

**Comment by mattnibs** [comment]
This appears to be working.

```
$ echo '{}' | zq 'x := [1,2,3]==[1,2,3]' -
{x:true}
```

```
$ echo '{}' | zq 'x := {a:1}=={a:1}' -
{x:true}
```

**Comment by philrz** [comment]
Like @mattnibs, I see that this appears fixed. At current Zed commit ed3b086, in addition to the examples @mattnibs cited, here's the ones from @mccanne's opening text.

```
$ echo null | zq 'yield {a:1}=={a:1}' -
true

$ echo null | zq 'yield [1,2,3]==[4,5,6]' -
false

$ echo '{x: {y:1}}' | zq -z 'yield x=={y:1}' -
true

$ echo '{}' | zq 'x := [1,2,3]==[1,2,3]' -
{x:true}

$ echo '{}' | zq 'x := {a:1}=={a:1}' -
{x:true}
```

I'm not sure if there is more to the story than what's captured in the comments above, but I'll tee this up for our next group discussion and confirm if it can be closed.

**Comment by philrz** [comment]
@nwt and I discussed this one and he also agreed it could be closed. There's a corner case related to complex values still open & tracked in #4588.
