### ISSUE TITLE
configurable CSV

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#3710]
For more flexible CSV parsing, the CSV reader should be able to be configured with a schema or a list of types.

The schema could be specified simply as a record type,
e.g., `{x:int64,s:string}` or a list of types to clarify 
the type of an ambiguous column like a number, e.g.,
`[<int64>,<string>]`

`sqlite` has a similar config with its
[CSV virtual table feature](https://www.sqlite.org/csv.html)

**Comment by philrz** [comment]
Closing this one as a duplicate of #3758.
