### ISSUE TITLE
"sample" as identifier in OpExpr

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#3728]
this causes a parse error...
```
sample:=any(<expr>) by typeof(<expr>)
```
we should fix the peg grammar to not let the sample operator get in 
the name here.

**Comment by philrz** [comment]
I verified via binary search that this was fixed as of Zed commit 39b2546, which is associated with the changes in #3792.

At Zed commit that was right before those changes arrived:

```
$ zq -version
Version: v1.0.0-15-g7a424e6c

$ echo "" | zq -z 'sample:=any(<expr>) by typeof(<expr>)' -
zq: error parsing Zed at column 7:
sample:=any(<expr>) by typeof(<expr>)
  === ^ ===
```

Then at Zed commit 39b2546 that has the fixes:

```
$ zq -version
Version: v1.0.0-16-g39b25463

$ echo "" | zq -z 'sample:=any(<expr>) by typeof(<expr>)' -
[no output]
```

Closing as fixed.
