### ISSUE TITLE
Casting time as duration

### ISSUE THREAD

**Issue by mattnibs** [brimdata/zed#3742]
You should be able to cast time as a duration (or probably any other number since time is nanoseconds since epoch). I stumbled this while trying to find the duration between two points in time by subtracting the time. In this case the result was a time (ok) but I couldn't cast it as a duration.

**Comment by philrz** [comment]
I've confirmed via binary search that this was fixed via #3816.

For example, at commit 8e12516 that was right before those changes:

```
$ zq -version
Version: v1.0.0-38-g8e125162

$ echo '{ts:2018-03-24T17:30:20Z}' | zq -z 'yield duration(ts)' -
error("cannot cast 2018-03-24T17:30:20Z to type duration")
```

But starting with commit ef2bf5b that has the changes from #3816:

```
$ zq -version
Version: v1.0.0-39-gef2bf5bb

$ echo '{ts:2018-03-24T17:30:20Z}' | zq -z 'yield duration(ts)' -
48y94d17h30m20s
```
