### ISSUE TITLE
Feature idea: assert keyword

### ISSUE THREAD

**Issue by twolodzko** [brimdata/zed#3853]
I came across Zed and really like it. It'd be a great tool for validating data, but for this it'd be nice if it has an "assert" operator defined as

```
switch(
  case not CONDITION => yield error( "assertion error: CONDITION not met for ..." ) 
  default => yield this
)
```

In such a case, it would be possible to write data assertion pipes like

```
assert Age > 0 |
assert Age < 120 |
assert Height > 0 |
...
```

In case any assertion is not met it throws an error like

```
error("Assertion error: Age > 0 not met for ...")
```

**Comment by mccanne** [comment]
Thanks @twolodzko.  This is a good idea and super easy!  We'll get it in right away.
