### ISSUE TITLE
zq command fails with "zngio: uncompressed length exceeds MaxSize" for large files

### ISSUE THREAD

**Issue by muthu-rk** [brimdata/zed#3881]
Hello,

I am trying to query a 100MB JSON file converted to ZNG format. However the query fails with **"zngio: uncompressed length exceeds MaxSize"** error. I tried setting -readsize and -readmax to higher values (1GiB). The error still persist.

However querying the JSON file directly instead of ZNG format, gave expected results. But it took more time to complete. I am trying to optimize it with ZNG format.

Also, the same query worked well for smaller files (about 10MB JSON)

Errors:
`
$ zq -z -i zng 'over arr | where id==10001 | cut level0.level1' 100mb.zng 
100mb.zng: zngio: uncompressed length exceeds MaxSize

$ zq -z -i zng -readmax 1GiB -readsize 1GiB 'over arr | where id==10001 | cut level0.level1' 100mb.zng 
100mb.zng: zngio: uncompressed length exceeds MaxSize
`
How files were converted from JSON to ZNG format:

`
$ zq -f zng -i json 100mb.json > 100mb.zng

$ ll -h
total 1.7G
drwxrwxr-x 2 user user  4.0K May 11 02:09 ./
drwxrwxr-x 9 user user  4.0K May  6 10:52 ../
-rw-rw-r-- 1 user user  102M May 11 01:25 100mb.json
-rw-rw-r-- 1 user user  728K May 11 01:26 100mb.zng
-rw-rw-r-- 1 user user   11M May 11 01:24 10mb.json
-rw-rw-r-- 1 user user   60K May 11 01:26 10mb.zng

`
Can you suggest how to solve this problem?

**Comment by mccanne** [comment]
Hmm, look like a bug.  We'll get to the bottom of it.

**Comment by muthu-rk** [comment]
Thanks @mccanne for quick response.

We have use case to perform CRUD on 1GiB size JSON file. It equivalent ZNG file comes to about 8.7 MB size.

I hope there wont be any file size restriction with the fix, given that querying a json file with input of 1GiB instead of equivalent ZNG input is already works as expected.

**Comment by nwt** [comment]
@muthu-rk: Is it possible for you to share that 100mb.zng file by [attaching it here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files)?

**Comment by muthu-rk** [comment]
[100mb.zng.zip](https://github.com/brimdata/zed/files/8669438/100mb.zng.zip)
[500mb.zng.zip](https://github.com/brimdata/zed/files/8669461/500mb.zng.zip)
[1gb.zng.zip](https://github.com/brimdata/zed/files/8669462/1gb.zng.zip)

@nwt Please find the requested 100mb.zng file. Additionally I am attaching 500mb and 1gb sized json equivalent zng files. Our input files are usually over 500mb size. 

Hope this helps. Kindly let me know if you need additional info.

**Comment by nwt** [comment]
@muthu-rk: Thank you!

**Comment by mccanne** [comment]
> Thanks @mccanne for quick response.
> 
> We have use case to perform CRUD on 1GiB size JSON file. It equivalent ZNG file comes to about 8.7 MB size.
> 
> I hope there wont be any file size restriction with the fix, given that querying a json file with input of 1GiB instead of equivalent ZNG input is already works as expected.

Looks like @nwt has the fixes worked out (first PR is merged, second PR is coming).  From the tip of main, I can query your test files now without error.

Crazy amount of nesting :-)

Were you planning to use zq to do the CRUD update?

Would it look something l like this?
```
over arr | switch id (
  case 10001 =>  put level0.level1...levelx.value:=<new value>
  default => pass 
) | arr:=collect(this)
```

Just curious.  This is definitely pushing the envelope on nesting.

**Comment by muthu-rk** [comment]
Hi @mccanne 

Yes. I am evaluating zed to perform CRUD on large JSON files (few 100 MBs to 1 GB). And it is likely to have deeply nestled objects. The samples I shared with you are written to mimic those scenarios.

Currently checking if I can achieve them using zq command line tool. Later I will check how to achieve these functionalities via APIs.

However I am still yet to understand how to perform in-place put/drop on json/zng files? 

**Could you share sample queries to Put/Cut/Drop _inplace_ and store the result directly in the same zng/json file?**

What I have tried?:
Put a specific value in a deeply nested object. I am able to achieve it like this. 

`zq -i zng -o out.zng 'over arr | where id==2 | put level0.level1.level2.level3.value:=100' min.zng `

It gives only object with id=2. I am able to redirect to out.zng. However I would want to change this value and store in min.zng itself. Is it possible to do this? If so, how?

**Comment by nwt** [comment]
Closing this since #3884 and #3885 should address the problem here. Please reopen if they don't.

(CRUD discussion continues in #3891.)
