### ISSUE TITLE
Put doesnt create new fields in nested objects

### ISSUE THREAD

**Issue by muthu-rk** [brimdata/zed#3889]
[min_5level.zng.zip](https://github.com/brimdata/zed/files/8681798/min_5level.zng.zip)

The new field is added to the root element, instead to the given nested path.

**Input used for PUT query:**
$ zq -i zng  'over arr | where id==2' min_5level.zng
{id:2,next:3,_id:"625664e3ea574290b931f172",friends:[{id:0,name:"Bradford Shaffer"},{id:1,name:"Monroe Kent"},{id:2,name:"John Carey"}],greeting:"Hello, Hart Kline! You have 9 unread messages.",favoriteFruit:"strawberry",level0:{tags:[1,2,3],value:"0",level1:{tags:[1,2,3],value:"1","level-2":{tags:[1,2,3],value:"2","level-3":{tags:[1,2,3],value:"3","level-4":{tags:[1,2,3],value:"4","level-5":{tags:[1,2,3],value:"5"}}}}}}}

Working scenario: **PUT works when the field is ALREADY present:**
$ zq -i zng  'over arr | where id==2 | put level0.level1.**value**:=100' min_5level.zng
{id:2,next:3,_id:"625664e3ea574290b931f172",friends:[{id:0,name:"Bradford Shaffer"},{id:1,name:"Monroe Kent"},{id:2,name:"John Carey"}],greeting:"Hello, Hart Kline! You have 9 unread messages.",favoriteFruit:"strawberry",level0:{tags:[1,2,3],value:"0",level1:{tags:[1,2,3],**value:100**,"level-2":{tags:[1,2,3],value:"2","level-3":{tags:[1,2,3],value:"3","level-4":{tags:[1,2,3],value:"4","level-5":{tags:[1,2,3],value:"5"}}}}}}}

Buggy scenario: **The new field is added to the root element, instead to the given nested path:**
$ zq -i zng  'over arr | where id==2 | put level0.level1.**value1**:=100' min_5level.zng

{id:2,next:3,_id:"625664e3ea574290b931f172",friends:[{id:0,name:"Bradford Shaffer"},{id:1,name:"Monroe Kent"},{id:2,name:"John Carey"}],greeting:"Hello, Hart Kline! You have 9 unread messages.",favoriteFruit:"strawberry",level0:{tags:[1,2,3],value:"0",level1:{tags:[1,2,3],value:"1","level-2":{tags:[1,2,3],value:"2","level-3":{tags:[1,2,3],value:"3","level-4":{tags:[1,2,3],value:"4","level-5":{tags:[1,2,3],value:"5"}}}}**,value1:100}**}}

I was expecting value1 to be created under level0.level1 path with this query. Can you suggest how to do this?

Additional info:
Buggy scenario: **New subpaths are created at the root level when the level2.level3 are present:**
$ zq -i zng  'over arr | where id==2 | put level0.level1.level2.level3.value1:=100' min_5level.zng

{id:2,next:3,_id:"625664e3ea574290b931f172",friends:[{id:0,name:"Bradford Shaffer"},{id:1,name:"Monroe Kent"},{id:2,name:"John Carey"}],greeting:"Hello, Hart Kline! You have 9 unread messages.",favoriteFruit:"strawberry",level0:{tags:[1,2,3],value:"0",level1:{tags:[1,2,3],value:"1","level-2":{tags:[1,2,3],value:"2","level-3":{tags:[1,2,3],value:"3","level-4":{tags:[1,2,3],value:"4","level-5":{tags:[1,2,3],value:"5"}}}},**level2:{level3:{value1:100}}**}}}

**Comment by philrz** [comment]
@muthu-rk: I got curious after seeing your issue so I tried to reproduce it. Maybe my vision is failing me (there's a lot of nesting here, after all :wink:) but I don't think the problems you describe appear in that output.

It might help to use the `-Z` option, as this pretty prints the ZSON with indentation to better show the nesting. Doing this with the first output you labeled as "Buggy scenario", it's easier to see that `value` is indeed nested under `level0.level1`, but I suppose the fact that it was added as the "rightmost" field under `level1` gave the illusion of it being a root field when in the non-pretty-printed output.

```
$ zq -version
Version: v1.0.0-94-g4600f3e7

$ zq -i zng -Z 'over arr | where id==2 | put level0.level1.value1:=100' min_5level.zng
{
    id: 2,
    next: 3,
    _id: "625664e3ea574290b931f172",
    friends: [
        {
            id: 0,
            name: "Bradford Shaffer"
        },
        {
            id: 1,
            name: "Monroe Kent"
        },
        {
            id: 2,
            name: "John Carey"
        }
    ],
    greeting: "Hello, Hart Kline! You have 9 unread messages.",
    favoriteFruit: "strawberry",
    level0: {
        tags: [
            1,
            2,
            3
        ],
        value: "0",
        level1: {
            tags: [
                1,
                2,
                3
            ],
            value: "1",
            "level-2": {
                tags: [
                    1,
                    2,
                    3
                ],
                value: "2",
                "level-3": {
                    tags: [
                        1,
                        2,
                        3
                    ],
                    value: "3",
                    "level-4": {
                        tags: [
                            1,
                            2,
                            3
                        ],
                        value: "4",
                        "level-5": {
                            tags: [
                                1,
                                2,
                                3
                            ],
                            value: "5"
                        }
                    }
                }
            },
            value1: 100
        }
    }
}
```

Yet another way to confirm this would be to `cut` the nested field and confirm it's at the same level you `put` it.

```
$ zq -i zng -Z 'over arr | where id==2 | put level0.level1.value1:=100 | cut level0.level1.value1' min_5level.zng 
{
    level0: {
        level1: {
            value1: 100
        }
    }
}
```

I think your second output labeled "Buggy scenario" has a similar trap in that you're targeting fields with names like `level2` and `level3` but the original data doesn't have fields of that name but instead the slightly-differently-named `level-2` and `level-3`, so the fact it's starting a new nested branch with the uniquely-named `level2` seems appropriate.

**Comment by muthu-rk** [comment]
My apologies. I should checked this carefully before reporting the issue. Thanks for the detailed explanation. Appreciate it!
