### ISSUE TITLE
zed yield query doesnt returns error("missing") when the query has special character (hyphen)

### ISSUE THREAD

**Issue by muthu-rk** [brimdata/zed#3890]
$ zq -i zng 'arr[0].level0.level1.level-2' min_5level.zng 
error("missing")

level-2 (note the hyphen) is present in the input.
$ zq -i zng 'arr[0].level0' min_5level.zng 
{tags:[1,2,3],value:"0",level1:{tags:[1,2,3],value:"1","level-2":{tags:[1,2,3],value:"2","level-3":{tags:[1,2,3],value:"3","level-4":{tags:[1,2,3],value:"4","level-5":{tags:[1,2,3],value:"5"}}}}}}

Can you suggest how to pass fields that have special characters to zed query? 

While checking the typeof(this) the record, level-2 is detected as string "level-2" (query below). Is it possible to perform escape sequencing in this case?
 
$ zq -i zng 'typeof(this)' min_5level.zng 
<{arr:[{id:int64,next:int64,_id:string,friends:[{id:int64,name:string}],greeting:string,favoriteFruit:string,level0:{tags:[int64],value:string,level1:{tags:[int64],value:string,"level-2":{tags:[int64],value:string,"level-3":{tags:[int64],value:string,"level-4":{tags:[int64],value:string,"level-5":{tags:[int64],value:string}}}}}}}]}> 

[min_5level.zng.zip](https://github.com/brimdata/zed/files/8681798/min_5level.zng.zip)

**Comment by philrz** [comment]
@muthu-rk: The way to deal with special characters is to use the "array-style reference" described at [https://zed.brimdata.io/docs/language/overview/#65-field-dereference:](https://zed.brimdata.io/docs/language/overview/#65-field-dereference:) 

```
$ zq -version
Version: v1.0.0-94-g4600f3e7

$ zq -i zng -Z 'arr[0].level0.level1["level-2"]' min_5level.zng
{
    tags: [
        1,
        2,
        3
    ],
    value: "2",
    "level-3": {
        tags: [
            1,
            2,
            3
        ],
        value: "3",
        "level-4": {
            tags: [
                1,
                2,
                3
            ],
            value: "4",
            "level-5": {
                tags: [
                    1,
                    2,
                    3
                ],
                value: "5"
            }
        }
    }
}
```

I know you're familiar with #3888 and #3071 that show there's currently bugs where this type of reference is not working in other places where it's supposed to, but it should work for this specific example at least.

**Comment by muthu-rk** [comment]
This will helps my use case. Thanks a bunch!
