### ISSUE TITLE
Index updated at effective rate of 1.07 MByte/sec while using ~2.6 cores out of 12

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#3962]
Repro is with:
* Zed commit 88ad6e9
* 12-core Intel-based Mac laptop
* Test data pre-loaded as described in #3961

The repro steps for indexing a field:

```
$ zed -version
Version: v1.1.0-42-g88ad6e92

$ zed index create IndexGroupEx field value
IndexGroupEx
    rule 2BRWHPCEfxeBkNoh5U9bjk69Dil field value

$ date +%s && time zed index update && date +%s
1656869299
2BRedLIV73iObSivyJ88xhFsRrN committed

real	68m31.249s
user	0m0.092s
sys	0m0.031s
1656873410
```

This indicates the data set was scanned and the index updated at an effective rate of 1.07 MByte/sec.

Here's the per-second CPU utilization during the length of the run:

![image](https://user-images.githubusercontent.com/5934157/177054276-719e9259-bb71-4730-8e8f-d8239ac6a320.png)

As indicated by the legend below the chart, the CPU was busy about 21.8% on average across the whole of the run, indicating about 2.6 out of the 12 available cores were being leveraged on average.

File [prometheus.tgz](https://github.com/brimdata/zed/files/9035380/prometheus.tgz) contains the metrics storage fro the run. Once unpacked, the screenshot can be recreated via:

http://localhost:3000/d/-z-YR3qnk/host-and-zed-stats?orgId=1&from=1656870087339&to=1656870270035

**Comment by nwt** [comment]
Closing because #4972 removed lake indexes.
