### ISSUE TITLE
user-defined functions (UDF)

### ISSUE THREAD

**Issue by mccanne** [brimdata/zed#4026]
The time has come to implement a simple form of user-defined function.

We can debate the syntax but I propose this pythonic form:
```
def f(x,y,...): ( <any expression>)
```
We need parens to define the scope of the expression (since we don't use whitespace
scoping like python)

In the initial implementation no recursion or control structures will be allowed.
This can come later.  For now, we will support just the existing expression syntax.

**Comment by philrz** [comment]
A community zync user recently expressed a need for this functionality.
