### ISSUE TITLE
Unflatten non-deterministic and panics

### ISSUE THREAD

**Issue by cwohlman** [brimdata/zed#4090]
Before opening a new issue, please make sure you've reviewed the troubleshooting guide:
https://github.com/brimdata/brim/wiki/Troubleshooting

**Describe the bug**
The unflatten function is returning wrong, non-deterministic, and buggy results for me. Depending on how I run my query (same underlying data & eventual result), I will get either a panic, incorrect data, and/or different results each time I run the same query.

**To Reproduce**
The simplest way to reproduce the issue, which seems to give some insight into the underlying problem is:

1. Load [reproduction.txt](https://github.com/brimdata/brim/files/8718057/reproduction.txt)
2. Run this query: `{ ts, foo: unflatten(this.collect) }`

Changing the query to `{ ts, ...(unflatten(this.collect)) }` results in different (incorrect) behavior.

Loading my data & intermediate queries up instead of the reproduction data above results in a panic about 50% of the time.

**Expected behavior**
I expect the unflatten function not to carry over state from one record to the next, and for the behavior to be consistent across re-runs of the same query.

**Desktop Info**
 - OS: Windows
 - Brim Version: 0.29.0

**Comment by philrz** [comment]
@cwohlman: Have you been able to reproduce the issue again?

**Comment by philrz** [comment]
@cwohlman: Since we've not heard back from you, we'll assume it hasn't reproduced or you've moved on to other priorities. If you still need help just ping us anytime.
