### ISSUE TITLE
Have "head" accept an expr rather than only a static integer

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#4168]
A community zync user inquired:

> Do you have any idea why `head 10` works while `head 10+1` (with an expression) doesn't?

A look at the [docs](https://zed.brimdata.io/docs/next/language/operators/head) indicates this is an expected limitation of the current implementation, since it shows the parameter being an integer `[ n ]` rather than `[ expr ]`. I'm not certain if it would be feasible/easy to accept an expression in this context, but this user indicated they have a likely use for this in a Zed BI proxy server they're building. If we end up doing it for `head`, surely we'd want `tail` to have the same treatment. Looking through the docs, I don't see any other operators that take a simple integer parameter at the moment.

**Comment by mattnibs** [comment]
@philrz I think this makes sense so long as the expression can evaluate at compile time (e.g. `10+1` works but `10+n` where `n` is not a const does not). If this user wants something like `10+n` where `n` is not a const to work I would suggest we create a new  op (something like `done [expr]`) that exits the flowgraph when the expression evaluates true.

**Comment by philrz** [comment]
I just tested out the branch. It seems to work fine and the docs changes seem good. 👍

**Comment by philrz** [comment]
Verified in Zed commit a7ce5b7.

Revisiting the original phrasing of the user inquiry, now `head 10+1` works where it didn't before.

```
$ zq -version
Version: v1.6.0-21-ga7ce5b77

$ seq 1 100 | zq -z 'head 10+1' -
1
2
3
4
5
6
7
8
9
10
11
```

#4463 has been opened to give `tail` the same treatment.

Thanks @dianetc!
