### ISSUE TITLE
Failed response over API looks like success

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#4215]
Repro is with Zed commit 0066c8a.

I was tinkering in a Brim branch https://github.com/brimdata/brim/tree/parquet-export to add Parquet as an **Export** format. It works fine for the happy path, but the backend currently won't create Parquet output when the query response has one or more of the following:

1. Multiple shapes
2. A `union` type

With the Zed CLI tooling, this is well-reported to the user. The following examples use test data [sample.zng](https://github.com/brimdata/brim/blob/main/src/test/shared/data/sample.zng?raw=true) from the Brim repo.

```
$ zq -f parquet sample.zng > /dev/null
Parquet output requires uniform records but multiple types encountered (consider 'fuse')

$ echo $?
1

$ zq -f parquet 'fuse' sample.zng > /dev/null
union type unsupported

$ echo $?
1

$ curl http://localhost:9867/version
{"version":"v1.2.0-132-g0066c8aa"}

$ zed create foo
pool created: foo 2HeFzcYxjPT6hCQ7oZ54rUu7MPa

$ zed -use foo load sample.zng 
(2/1) 4910B/4910B 4910B/s 100.00%
2HeG09yuVGPz3gQg5d0c4yUC8ru committed

$ zed query -f parquet 'from foo' > /dev/null
Parquet output requires uniform records but multiple types encountered (consider 'fuse')

$ echo $?
1

$ zed query -f parquet 'from foo | fuse' > /dev/null
union type unsupported

$ echo $?
1
```

However, If I attempt those queries over the API (as the Brim app would need to do), the errors seem to be masked by the fact that the response comes back as HTTP 200.

```
$ curl -v --fail-with-body -X POST --output /dev/null -H 'Accept: application/x-parquet' -H 'Content-Type: application/json' http://localhost:9867/query -d '{"query":"from foo"}'

Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1:9867...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to localhost (127.0.0.1) port 9867 (#0)
> POST /query HTTP/1.1
> Host: localhost:9867
> User-Agent: curl/7.84.0
> Accept: application/x-parquet
> Content-Type: application/json
> Content-Length: 20
> 
} [20 bytes data]
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/x-parquet
< Vary: Origin
< X-Request-Id: 2HeGbXwUEzZLarpK8Cj4N6CyTgT
< Date: Wed, 16 Nov 2022 22:36:47 GMT
< Content-Length: 1111
< 
{ [1111 bytes data]
100  1131  100  1111  100    20   134k   2484 --:--:-- --:--:-- --:--:--  552k
* Connection #0 to host localhost left intact

$ echo $?
0

$ curl -v --fail-with-body -X POST --output /dev/null -H 'Accept: application/x-parquet' -H 'Content-Type: application/json' http://localhost:9867/query -d '{"query":"from foo | fuse"}'

Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1:9867...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to localhost (127.0.0.1) port 9867 (#0)
> POST /query HTTP/1.1
> Host: localhost:9867
> User-Agent: curl/7.84.0
> Accept: application/x-parquet
> Content-Type: application/json
> Content-Length: 27
> 
} [27 bytes data]
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Vary: Origin
< X-Request-Id: 2HeGg9a4VuJ1QpVjYkHMAbRMK5h
< Date: Wed, 16 Nov 2022 22:37:23 GMT
< Content-Length: 0
< 
100    27    0     0  100    27      0   3580 --:--:-- --:--:-- --:--:-- 13500
* Connection #0 to host localhost left intact

$ echo $?
0
```

I showed this to @nwt and his first thought was that the client would maybe need to get smarter here, which makes sense since the Zed CLI tools were somehow able to deduce there was an error. However, I then also remembered that the `zed query` pulls the response over the API as ZNG and does the Parquet conversion client-side, so that explains it.

**Comment by philrz** [comment]
A similar problem can be reproduced by attempting CSV export using the [imdb.txt](https://github.com/brimdata/zed/files/11298681/imdb.txt) test data from [zui/2751](https://github.com/brimdata/zui/issues/2751). Therefore I'm changing the description of this issue to be applicable more than just Parquet since it seems like a general problem with error handling over the API.

The attached video shows the user-facing symptom reproduced with [Zui Insiders 1.0.2-17](https://github.com/brimdata/zui-insiders/releases/tag/v1.0.2-17) which uses Zed commit 2286e6a. The data being imported is just strings, so `line` format is used to load it. Exporting as CSV then appears to succeed, but the output file has zero length and no error message is shown.

https://user-images.githubusercontent.com/5934157/233718607-33de3641-94f3-408f-acfd-86b7db1ecf2d.mp4

Like the Parquet problem described earlier in this issue, the root cause is apparent when running with the CLI tooling.

```
$ zq -i line -f csv 'fuse' imdb.txt 
CSV output encountered non-record value: "15 avg_score_16 full_time_teachers percent_black percent_white percent_asian percent_hispanic"
```

...but the problem is masked behind the successful HTTP 200.

```
$ curl -v --fail-with-body -X POST -H 'Accept: text/csv' -H 'Content-Type: application/json' http://localhost:9988/query -d '{"query":"from imdb.txt | fuse"}'
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1:9988...
* Connected to localhost (127.0.0.1) port 9988 (#0)
> POST /query HTTP/1.1
> Host: localhost:9988
> User-Agent: curl/7.87.0
> Accept: text/csv
> Content-Type: application/json
> Content-Length: 32
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Vary: Origin
< X-Request-Id: 2OkXFAvfJIqXupF9S6zqWxrufs4
< Date: Fri, 21 Apr 2023 19:30:47 GMT
< Content-Length: 0
< 
* Connection #0 to host localhost left intact
```

**Comment by philrz** [comment]
Another community user recently bumped into CSV variant of this problem as captured in a [Slack thread](https://brimdata.slack.com/archives/C010DR0HHMF/p1690892944787139).

**Comment by mattnibs** [comment]
Reopening since this really needs zui support before it can be closed.

**Comment by philrz** [comment]
Verified in Zed commit 8f00fa6.

I've repeated the original repro steps that show the current error message from the Zed CLI tooling and how the message can now be retrieved from the new [Query Status endpoint](https://zed.brimdata.io/docs/next/lake/api#query-status) using the `X-Request-Id` value from the original query response.

```
$ zed -version
Version: v1.9.0-17-g8f00fa61

$ zed create -use foo
pool created: foo 2V7RM2gZyAQNDB7TJvR2yELJYKz
Switched to branch "main" on pool "foo"

$ zed load sample.zng 
(2/1) 4910B/4910B 4910B/s 100.00%
2V7RNiU0jUQHUql0ffA6mJgFcaW committed

$ zed query -f parquet 'from foo' > /dev/null
parquetio: unsupported type: not implemented yet

$ curl -v --fail-with-body -X POST --output /dev/null -H 'Accept: application/x-parquet' -H 'Content-Type: application/json' http://localhost:9867/query -d '{"query":"from foo"}'
Note: Unnecessary use of -X or --request, POST is already inferred.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1:9867...
* Connected to localhost (127.0.0.1) port 9867 (#0)
> POST /query HTTP/1.1
> Host: localhost:9867
> User-Agent: curl/8.1.2
> Accept: application/x-parquet
> Content-Type: application/json
> Content-Length: 20
> 
} [20 bytes data]
< HTTP/1.1 200 OK
< Vary: Origin
< X-Request-Id: 2V7RUXE0H5vHMrKDkVXzs0Jf7Dt
< Date: Fri, 08 Sep 2023 14:59:07 GMT
< Content-Length: 0
< 
100    20    0     0  100    20      0   2603 --:--:-- --:--:-- --:--:-- 20000
* Connection #0 to host localhost left intact

$ curl -X GET -H 'Accept: application/json' http://localhost:9867/query/status/2V7RUXE0H5vHMrKDkVXzs0Jf7Dt
{"error":"parquetio: unsupported type: not implemented yet"}
```

Note that the error message is currently only made available for 10 seconds. This gives plenty of time for a client like Zui to retrieve it, though for a manual situation like the one I've done here with `curl` it requires moving pretty quickly to catch it, and it got me to wondering if users might find this limiting if they should find themselves trying to use the feature in manual/batch contexts. I checked witth @mattnibs and it sounds like we could probably make this number configurable to higher values in the future if users cite it as a problem.

Per the last comment above from @mattnibs, I'll open a Zui issue to prioritize taking advantage of this endpoint since the app is what needs this functionality most right now.

Thanks @mattnibs!

**Comment by philrz** [comment]
Per the prior comment, Zui issue https://github.com/brimdata/zui/issues/2751 is now tracking the work to have the app take advantage of this status endpoint, so I'm closing this issue on the Zed side.
