### ISSUE TITLE
Replace zio/parquetio with zio/arrowio and pqarrow

### ISSUE THREAD

**Issue by nwt** [brimdata/zed#4278]
We can replace the Parquet reader and writer in zio/parquetio with a combination of zio/arrowio and github.com/apache/arrow/go/v11/parquet/pqarrow, and we probably should since
* it'll let us remove about 750 lines from zio/parquetio,
* the Arrow Parquet implementation will probably receive more attention the one we're currently using, and
* it fixes #764.

**Comment by philrz** [comment]
Verifications of this change are in https://github.com/brimdata/zed/issues/764#issuecomment-1526667106 and https://github.com/brimdata/zed/issues/4527#issuecomment-1526671541. Thanks @nwt!
