### ISSUE TITLE
Corrupt pool name based on filename

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#4431]
Repro is with Zed commit 7882cee. This was originally originally reported by a community user in a [Slack message](https://brimdata.slack.com/archives/C010DR0HHMF/p1678630507084789).

Repro requires the attached test data 
[Alice test_full-report.json.gz](https://github.com/brimdata/zed/files/10951704/Alice.test_full-report.json.gz), though it must be `gunzip`'ed first, as there's something about using this filename as a pool name that triggers the problem.

```
$ zed -version
Version: v1.6.0-4-g7882cee3

$ rm -rf lake && zed -lake lake serve
```

```
$ gunzip Alice\ test_full-report.json.gz

$ zed create "Alice test_full-report.json" 
pool created: Alice test_full-report.json 2MvSa0aIBXymAIFxgQ7TFogdAuD

$ zed ls
Alice test_full-report.json 2MvSa0aIBXymAIFxgQ7TFogdAuD key ts order desc

$ zed use "Alice test_full-report.json"
branch not found

$ zed use 2MvSa0aIBXymAIFxgQ7TFogdAuD
Switched to branch "main" on pool "2MvSa0aIBXymAIFxgQ7TFogdAuD"

$ zed query 'from "Alice test_full-report.json" | count()'
status code 404: AlichftestYfulosreporwtjson: pool not found
```

The `branch not found` and corrupt pool name `AlichftestYfulosreporwtjson` are signs of the bug. I was tinkering with some debug in the Go code and there's something highly suspicious about these all having the same number of characters:

```
AlichftestYfulosreporwtjson
2MvSa0aIBXymAIFxgQ7TFogdAuD
Alice test_full-report.json
```

**Comment by nwt** [comment]
This is caused by https://github.com/segmentio/ksuid/issues/74. We can work around that, but before we do, let's see if it gets fixed over there.

**Comment by philrz** [comment]
There doesn't seem

**Comment by philrz** [comment]
Verified in Zed commit 935c334.

Repeating the original repro steps, the name of the pool is no longer a problem.

```
$ zed -version
Version: v1.13.0-15-g935c3340

$ zed create "Alice test_full-report.json"
pool created: Alice test_full-report.json 2cNInaDXCQXBLNLxJH3f8aXsDdl

$ zed ls
Alice test_full-report.json 2cNInaDXCQXBLNLxJH3f8aXsDdl key ts order desc

$ zed use "Alice test_full-report.json"
Switched to branch "main" on pool "Alice test_full-report.json"

$ zed load Alice.test_full-report.json 
(2/1) 19B/19B 19B/s 100.00%
2cNIp3i8sNCkr4uDKqLRkmYv6Ld committed

$ zed query 'from "Alice test_full-report.json" | count()'
1(uint64)
```

Thanks @mattnibs!
