### ISSUE TITLE
WebAssembly (wasm) support

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#4436]
Once Zed tools can be built for the [WebAssembly](https://webassembly.org/) (wasm) architecture, we'll be able to do things like show Zed queries running in [Observable](https://observablehq.com/) notebooks without depending on external storage or services. This is also expected to enable a [Zui tour/playground](https://github.com/brimdata/zui/issues/2563) for demo/training purposes.

**Comment by nwt** [comment]
https://github.com/nwt/zqjs demonstrates one approach to this. @jameskerr is going use it as a starting point for something publishable for brimdata/zui#2736.
