### ISSUE TITLE
Querying pool with small object size consumes too much memory

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#4441]
Repro is with Zed commit d14bc2c.

In a [public Slack thread](https://brimdata.slack.com/archives/CTSMAK6G7/p1679087818529299), a community user reported it taking as much as 30 minutes do do a `count()` on their 82 GB pool of Zeek & Suricata logs. They explained their system had 6 cores, a fast SSD, 64 GB of RAM, and they reported seeing the `zed serve` process using about 44 GB of memory during the query. They also mentioned having loaded their data in the form of ~10 MB ZNG files.

I attempted to reproduce something close to their setup by spinning up an AWS `m6idn.4xlarge` VM, which has 16 cores, an instance SSD, and 64 GB of RAM. I created my pool with an object size of 10 MB in an attempt to replicate the effects of their ~10 MB data loads, then loaded the full 70 GB wrrcdc data set from `s3://brim-sampledata/wrccdc/zeek-logs/`.

After loading the pool, what I observed on my first `zed query 'from zeek | count()'` was that all the memory on the system was consumed in just a few seconds such that the host became completely unresponsive for several minutes and I had to forcefully shut it down. By comparison, with the default 500 MB object size the memory usage stayed under a ceiling of ~3 GB as shown below.

```
$ time zed query 'from zeek | count()'
573070060(uint64)

real    5m24.953s
user    0m0.095s
sys     0m0.026s
```

![image](https://user-images.githubusercontent.com/5934157/226139981-bb52e9f4-8b10-452f-b9a5-3be6c30d1280.png)

I then fiddled with the object size a bit and found that at 35 MB I could see it jump up and use _most_ of the memory on the system (~45 GB) but not completely exhaust it, therefore allowing me to take a memory profile: [memprofile.out.gz](https://github.com/brimdata/zed/files/11009603/memprofile.out.gz)

```
$ zed create -S 35MB zeek
pool created: zeek 2NCanEPI9zD8tMkfy8czPjo0uTF

$ zed use zeek
Switched to branch "main" on pool "zeek"

$ time zed load *
(35/35) 17.75GB/17.75GB 12.44MB/s 100.00%
2NCcynqLpFGhz6lgDbWsv0RPb2c committed

real    17m52.414s
user    17m40.170s
sys     0m22.425s

$ time zed query 'from zeek | count()'
573070060(uint64)

real    5m59.681s
user    0m0.090s
sys     0m0.041s
```

![image](https://user-images.githubusercontent.com/5934157/226140040-b6bb9c73-3f7a-4528-99bd-522819c27469.png)

A secondary observation is that <10% of the available CPU is seen being used during the query. That's being tracked in separate issue #4450.

**Comment by nwt** [comment]
@philrz: I think #4526 took care of this. Here's what I see for a wrccdc pool with 10 MB data objects with 1ac878fa1388e288aab32d72bc23f751f812b516. (Max RSS here is below 300 MB.)
```console
$ /usr/bin/time -l zed -lake tmp query 'from zeek10MiB | count()'
573070060(uint64)
        6.71 real        53.52 user         4.80 sys
           314359808  maximum resident set size
                   0  average shared memory size
                   0  average unshared data size
                   0  average unshared stack size
               19608  page reclaims
                   3  page faults
                   0  swaps
                   0  block input operations
                   0  block output operations
                   0  messages sent
                   0  messages received
                3342  signals received
               11911  voluntary context switches
              192828  involuntary context switches
        686484411688  instructions retired
        169749567839  cycles elapsed
           299943808  peak memory footprint
```

**Comment by philrz** [comment]
Thanks @nwt. Right you are! Just to have an apples-to-apples verification, here's a run at commit 2314053 using the same repro steps & charts I used when I opened up the issue, done once again on an AWS `m6idn.4xlarge` VM with the 10 MB object size.

```
$ zed --version
Version: v1.8.1-28-g23140538

$ zed create -S 10MB zeek
pool created: zeek 2RAQDupr5ar49BS0iwLm4C2IbSJ

$ zed use zeek
Switched to branch "main" on pool "zeek"

$ time zed load *
(35/35) 17.75GB/17.75GB 18.31MB/s 100.00%
2RASWhlC3IcUelu0QDaLDkLe11x committed  

real    17m45.815s
user    17m36.637s
sys     0m20.228s

$ time zed query 'from zeek | count()'
573070060(uint64)

real    0m7.314s
user    0m0.012s
sys     0m0.012s
```

And here's the system metrics during the `count()`, which shows the memory usage stayed below 600 MiB.

![image](https://github.com/brimdata/zed/assets/5934157/205cf4f4-e02f-4664-9814-824d7cd47948)

Closing as verified.
