### ISSUE TITLE
count() of wrccdc pool uses <10% of available CPU

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#4450]
Repro is with Zed commit d14bc2c.

The same test that reproduced the high memory usage shown in #4441 showed a second problem: Not much of the available CPU on the system was being used. If more could be leveraged, we'd expect the `count()` to complete much faster.

```
$ time zed query 'from zeek | count()'
573070060(uint64)

real    5m24.953s
user    0m0.095s
sys     0m0.026s
```

![image](https://user-images.githubusercontent.com/5934157/226139981-bb52e9f4-8b10-452f-b9a5-3be6c30d1280.png)

@nwt spotted the first layer of the cause: We were not parallelizing `from x | count()`. That has since been addressed in linked PR #4442. But that alone doesn't solve the performance problem. The summary of why, also from @nwt:

> The problem is that parallelism gives us multiple scanners but then the planner generates one big partition, and each scanner needs a partition to keep it busy, so if you’ve only got one partition, you can only keep one scanner busy.

**Comment by philrz** [comment]
#4488 was a first attempt at this, but it never quite wrapped so has been closed for now. @mattnibs has said he intends to pick up the branch again some point soon.

**Comment by nwt** [comment]
@philrz: I think #4526 took care of this. Here's what I see for a wrccdc pool with 1ac878fa1388e288aab32d72bc23f751f812b516.
```console
$ time zed query 'from zeek | count()'
573070060(uint64)

real	0m6.374s
user	0m0.018s
sys	0m0.015s
```

**Comment by philrz** [comment]
Thanks @nwt. Right you are! I see this is also reflected in the Autoperf macro metric trend and I had indeed marked that point of transition with a reference to #4526, but I failed to make the connection with this issue.

![image](https://github.com/brimdata/zed/assets/5934157/4bd2bb44-50fd-4a6b-9bb2-04a42ad8257d)

Closing this one as verified.
