### ISSUE TITLE
Csv data import problem

### ISSUE THREAD

**Issue by AFgh24** [brimdata/zed#4514]
Csv data import problem

The problem occurs when a large csv file has an error in its syntax
The next lines are not checked and this makes the next data not imported

I think the better option is to check the next lines if there is an error in one line and add them if there is no problem.

And finally, after import, it will show how many lines of data have not been imported
Line 6
I tested this in the Zui UI and it has problems

[imdb.csv](https://github.com/brimdata/zed/files/11294803/imdb.csv)

**Comment by AFgh24** [comment]
I wrote a piece of code to solve the problem of files
I think it would be much better if such a feature is added to the main software itself

I enter the number of commas manually

`@echo off
setlocal enabledelayedexpansion

set "input_file=*.csv"
set "output_file=output.txt"

for /f "delims=" %%a in ('type "%input_file%"') do (
    set "line=%%a"
    set "count=0"
    for %%b in ("!line:,=" "!") do set /a count+=1
    if !count! lss 14 (
        set /a diff=14-!count!
        set "line=!line!,"
        for /l %%c in (1,1,!diff!) do set "line=!line!,"
    )
    echo !line!>>"%output_file%"
)

echo Done!
pause
`

**Comment by philrz** [comment]
@AFgh24: Thanks for reporting. Indeed, this is a topic that's come up a couple times before, and we just had a group discussion about it and came up with an idea to address it at the Zed layer that's now being tracked in #4546. I'm going to go ahead and close this particular issue so please feel free to keep an eye on #4546 and see how you like it when the enhancement lands. I made mention there of your idea to make sure Zui prominently displays the error count when there's such problems.
