### ISSUE TITLE
Control messages aren't sent until the first batch from the flowgraph is emitted

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#4583]
At the time of the filing of this issue, Zed is at commit 0d949c4.

While we're not certain it's the root cause of https://github.com/brimdata/zync/issues/118, when looking at the logs @mattnibs had one theory:

>  I think this has to do with a bug in the query endpoint where control messages aren't sent until the first batch from the flowgraph is emitted.
> my first question would be to find out what query zync is issuing that is going so slow.

**Comment by mattnibs** [comment]
Closing, I was wrong about this. As it turns out zed serve does send back control messages before the first batch has been emitted. This must have been fixed at some point from when I last observed this.
