### ISSUE TITLE
Auto-detect failure on ZNG input: buffer exceeded max size

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#4586]
Repro is with GA Zed tagged [v1.7.0](https://github.com/brimdata/zed/releases/tag/v1.7.0).

A community zync user was using the [Zed lake migration](https://github.com/brimdata/zed-lake-migration) tools and reported the following failure:

![image](https://github.com/brimdata/zed/assets/5934157/43945e70-d13a-4926-ae83-db9fc5980029)

This failure was at the step where it attempted to `zed load` the ZNG dump of the old-format pool to make the new-format pool. Since we knew the expected input was ZNG, they were able to easily work around the problem by adding an explicit `-i zng` to the `zed load`. However, since it's Zed's own format, we'd expect we should be able to auto-detect ZNG pretty reliably, so we'd like to better understand what broke here.

Unfortunately, due to the sensitive nature of the data, it could not be shared for us to reproduce the problem ourselves. Thankfully the `zed dev dig frames` command can be used to show the structure of the ZNG file without revealing its contents. They shared the following output:

![image](https://github.com/brimdata/zed/assets/5934157/4a5ae0ba-f742-47d1-b625-b4b24dc413f1)

**Comment by nwt** [comment]
We should modify zio/anyio.NewReaderWithOpts to avoid Recorder and Track if its io.Reader parameter implements io.Seeker. That would eliminate this problem for file inputs (but not for fifos and pipes).
