### ISSUE TITLE
Failed field dereference inside User Op

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#4651]
Repro is with Zed commit 2314053.

Start from this simple example in main scope that uses a [field dereference with indexing](https://zed.brimdata.io/docs/next/language/expressions#field-dereference).

```
$ zq -version
Version: v1.8.1-28-g23140538

$ cat put-in-main.zed
this["hello"]:="world"

$ echo '{foo: "bar"}' | zq -Z -I put-in-main.zed -
{
    foo: "bar",
    hello: "world"
}
```

I can wrap this in a User Op and it still works as long as I use static strings to reference the field names.

```
$ cat put-in-op-1.zed
op CallMe(...): (
  this["hello"]:="world"
)
CallMe(this)

$ echo '{foo: "bar"}' | zq -Z -I put-in-op-1.zed -
{
    foo: "bar",
    hello: "world"
}
```

However, if I try to pass the field names into `const` parameters in the User Op, now it fails.

```
$ cat put-in-op-2.zed
op CallMe(const fname, const fval, ...): (
  this[fname]:=fval
)

CallMe("hello", "world", this)

$ echo '{foo: "bar"}' | zq -Z -I put-in-op-2.zed -
illegal left-hand side of assignment
```

---

Side note: Because that failed, I thought this one would fail as well, but it actually works. Just putting here in case @mattnibs wants to take a closer look.

```
$ cat has-in-op-2.zed
op CallMe(const f1, const f2, ...): (
  yield {yes:has(this[f1]),no:has(this[f2])}
)
CallMe("foo", "bar", this)

$ echo '{foo:10}' | zq -z -I has-in-op-2.zed -
{yes:true,no:false}
```

**Comment by philrz** [comment]
Update: As of the changes in #4663, this one is still with us. With the changes in that PR, both constants and field paths can be passed in as parameters. Updating the repro steps to align with the revised syntax, the errors are the same as before regardless of how we try to reference the field we want to populate from inside the User Op.

```
$ zq -version
Version: v1.8.1-37-ge57e90ee

$ cat put-in-op-revised.zed 
op CallMe_const(fname, fval): (
  this[fname]:=fval
)

op CallMe_path(fname, fval): (
  fname:=fval
)

$ echo '{foo:10}' | zq -I put-in-op-revised.zed 'CallMe_const("hello", "world")' -
illegal left-hand side of assignment

$ echo '{foo:10}' | zq -I put-in-op-revised.zed 'CallMe_path(hello, "world")' -
illegal left-hand side of assignment
```

**Comment by mattnibs** [comment]
FWIW this issue is not specific to the implementation of user ops. For instance the query:
```
over this with key="hello" => (
    this[key] := "world"
)
```
yields the same "illegal left-hand side of assignment".

**Comment by philrz** [comment]
@mattnibs: Yes, fair point. This same error message is cited in different contexts in both #4555 and #4556.

**Comment by philrz** [comment]
Note to self: I called out this limitation in the User Ops [docs](https://zed.brimdata.io/docs/next/language/statements#limitations), so make sure to remove that when this gets addressed.

**Comment by philrz** [comment]
While doing other testing, I happened to notice that this has already been fixed in `main`. Specifically, starting with commit 380845a that's associated with the changes in #4702, what's shown in https://github.com/brimdata/zed/issues/4651#issuecomment-1603130206 no longer produce the `illegal left-hand side of assignment` error.

```
$ zq -version
Version: v1.8.1-65-g380845a4

$ cat put-in-op-revised.zed
op CallMe_const(fname, fval): (
  this[fname]:=fval
)

op CallMe_path(fname, fval): (
  fname:=fval
)

$ echo '{foo:10}' | zq -I put-in-op-revised.zed 'CallMe_const("hello", "world")' -
{foo:10,hello:"world"}

$ echo '{foo:10}' | zq -I put-in-op-revised.zed 'CallMe_path(hello, "world")' -
{foo:10,hello:"world"}
```

Thanks @mattnibs!
