### ISSUE TITLE
Python library returns False for all bool values

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#4705]
Repro is with Zed commit 7ba4ecc. This issue was found when updating the Rug tests.

```
$ zed -version
Version: v1.8.1-59-g7ba4ecc6

$ zed create -use foo
pool created: foo 2SDTbUqbbPfmsShCmRCLrh6wN6W
Switched to branch "main" on pool "foo"

$ echo '{foo: true, bar: false}' | zed load -
(13/1) 24B 24B/s
2SDTcY2Lo5Ku3i18D81ggGmEbwu committed

$ zed query 'from foo'
{foo:true,bar:false}

$ python3
Python 3.11.4 (main, Jun 20 2023, 16:59:59) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import zed
>>> client = zed.Client()
>>> values = client.query('from foo')
>>> for val in values:
...   print(val)
... 
{'foo': False, 'bar': False}
```

I see where the problem is, so I'll put up a PR right away to fix this.

I suspect #2526 is what broke this. I confirmed it was working ok at the commit right before that PR merged, but I couldn't even get the Python client to run at all at the commit after that PR merged, so I stopped there and just focused on the fix.

**Comment by mikesbrown** [comment]
Happy to hear Rug was nominally helpful. Cheers y'all.
