### ISSUE TITLE
Better zq error for single argument that isn't a valid file or valid Zed program

### ISSUE THREAD

**Issue by nwt** [brimdata/zed#4731]
This came up recently in a [public Slack thread](https://brimdata.slack.com/archives/CTSMAK6G7/p1690493519776799?thread_ts=1690482181.297299&cid=CTSMAK6G7).

The following error has proven confusing to newcomers.

```console
$ zq "from x y"
zq: no such file: from x y
```

Here's what you get when you add another argument.

```console
$ zq "from x y" -
zq: error parsing Zed at column 8:
from x y
   === ^ ===
```

One way to improve things would be to combine the errors.

```console
$ zq "from x y"
zq: no such file and not valid Zed: from x y
```

**Comment by philrz** [comment]
We ended up addressing this one with the changes in #5053. Per the verification notes in #5046, we did indeed end up taking the approach proposed above of combining the errors, albeit in a bit more verbose way.

```
$ zq -version
Version: v1.15.0-8-g20a867d9

$ zq "from x y"
zq: could not invoke zq with a single argument because:
 - a file could not be found with the name "from x y"
 - the argument could not be compiled as a valid Zed query due to parse error (column 7):
   from x y
      === ^ ===
```

That said, recent community issue #5110 reminds us there's still probably room for improvement here. But we've at least covered what was originally proposed in this issue so I'll close it out.
