### ISSUE TITLE
CSV reader error when file doesn't end in newline: bare " in non-quoted-field

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#4732]
Repro is with Zed tagged `v1.9.0`.

A user in a [public Slack thread](https://brimdata.slack.com/archives/CTSMAK6G7/p1690568261979059) observed the following when attempting to read the attached test data [chatgpt-vcs-2.csv](https://github.com/brimdata/zed/files/12197294/chatgpt-vcs-2.csv).

```
$ zq -version
Version: v1.9.0

$ zq -i csv 'count()' chatgpt-vcs-2.csv 
chatgpt-vcs-2.csv: parse error on line 630, column 27: bare " in non-quoted-field
```

Closer inspection revealed the problem was triggered because the file lacks a newline on the last line. Therefore this works around the problem:

```
$ echo >> chatgpt-vcs-2.csv 

$ zq -i csv 'count()' chatgpt-vcs-2.csv 
629(uint64)
```

This can surely be added to the list of CSV dialect headaches for which there may not be one 100% correct way to handle, but it seems like a simple enough corner cases that hopefully we can handle it better. Could we just detect this case and pretend the newline was there even if it isn't? If not, could we at least have a better error message so has a better chance of making the fix themselves?

**Comment by AFgh24** [comment]
Hello
I took help from a tool to solve csv file problem
In the csv files of the above record, there is probably a problem in the data import
But I converted the original csv file to the csv file of my house with **[visidata](https://github.com/saulpw/visidata)** and it is imported without any problems

It may not be a professional solution, but it is an answer

> visidata input.csv -b -o output.csv

**Comment by philrz** [comment]
Thanks @AFgh24. I just reproduced your `visidata` command line and I see that it removs the quotes around the field names, but most importantly it added the newline at the end of the file that wasn't there before, and that makes all the difference. The fact that tools like this are tolerant of such things is further evidence that the Zed tooling could be made more tolerant as well so users don't need to employ additional tooling just to deal with a small corner case like this.

**Comment by philrz** [comment]
We had another community user bump into this one as described in #5173, which has been closed as a duplicate. Their specific repro steps:

>This example was reduced from a real CSV file, which had several fields, complete with inlined double-quotes, commas, and other potential hazards (I can't share the original file due to PII). Numbers and a few other programs parsed it correctly. `zq` parses it correctly, once I add a newline on the very last line of the file.
>
>I can reproduce the same behavior with this:
>```
># Unquoted simple strings, plus final newline (due to default `echo` behavior) - works fine
>❯ echo "foo,bar\nfoo,bar" | zq -i csv -z 'yield this' -
>{foo:"foo",bar:"bar"}
>
># Quoted string values, plus final newline - still works fine
>❯ echo "foo,bar\n\"foo\",\"bar\"" | zq -i csv -z 'yield this' -
>{foo:"foo",bar:"bar"}
>
># Quoted string values, but without a newline ending the contents (changed to `echo -n`), I receive this error message.
>❯ echo -n "foo,bar\n\"foo\",\"bar\"" | zq -i csv -z 'yield this' -
>stdio:stdin: parse error on line 2, column 10: bare " in non-quoted-field
>
># Removing the quotes from the values, still with no final newline (`echo -n`), works again.
>❯ echo -n "foo,bar\nfoo,bar" | zq -i csv -z 'yield this' -
>{foo:"foo",bar:"bar"}
>
>❯ zq -version
>Version: v1.16.0
>```

**Comment by philrz** [comment]
Verified in Zed commit 9766d17.

The two examples shown above that previously returned the error message now parse their respective inputs successfully.

```
$ zq -version
Version: v1.17.0-1-g9766d17d

$ zq -i csv 'count()' chatgpt-vcs-2.csv
629(uint64)

$ echo -n -e "foo,bar\n\"foo\",\"bar\"" | zq -i csv -z 'yield this' -
{foo:"foo",bar:"bar"}
```

Thanks @mattnibs!
