### ISSUE TITLE
"--help" for help text

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#4774]
Repro is with Zed commit aa06e5b.

A community user spoke up in a recent [Slack thread](https://brimdata.slack.com/archives/CTT24051C/p1695143932772009):

> Thought here! Would be great for new users if `--help` returned something
>```
>❯ zq --help
>at flag: "--help": flag: help requested
>```

Reproducing this, indeed, I also find it a little strange. While the help text indicates `-h` is the way to display help text, the way the output above shows "help requested" seems to imply that the user's intent is understood but for some reason the tooling is just not wired up to show the help text here. However, grepping the code base, I can't find the "help requested" string anywhere. 🤔

By comparison, a wholly unsupported flag returns:

```
$ zq --foo
flag provided but not defined: -foo
at flag: "--foo": flag provided but not defined: -foo
```

**Comment by zmajeed** [comment]
The error message comes from two places - "help requested" is from https://pkg.go.dev/flag

```
var ErrHelp = errors.New("flag: help requested")
ErrHelp is the error returned if the -help or -h flag is invoked but no such flag is defined.
```

and "at flag" is from https://github.com/brimdata/zed/blob/main/pkg/charm/instance.go
```go
err = fmt.Errorf("at flag: %q: %w", s, err)
```

**Comment by philrz** [comment]
Verified in Zed commit 485623e.

The long form of requesting help now exists.

```
$ zq -version
Version: v1.11.1-24-g485623e8

$ zq | grep help
    -h display help (default "false")
    -help display help (default "false")
```

While that shows the single-dash variant `-help` (which also works), that responds to the double-dash variant as well.

```
$ zq --help
NAME
    zq - process data with Zed queries

USAGE
    zq [ options ] [ zed-query ] file [ file ... ]

...
```

Thanks @zmajeed!
