### ISSUE TITLE
zq -h prints help and usage message to stderr instead of stdout

### ISSUE THREAD

**Issue by zmajeed** [brimdata/zed#4901]
Since `zq -h` is a supported option letter and the exit status is zero, the output should be to stdout not stderr

```
zq -h >help.stdout 2>help.stderr

echo $?
0
```
```
ls -l help.*
-rw-r--r-- 1 5878 Nov 28 12:23 help.stderr
-rw-r--r-- 1 0 Nov 28 12:23 help.stdout
```

**Comment by philrz** [comment]
Thanks @zmajeed. Indeed, the [angry HackerNews mob](https://news.ycombinator.com/item?id=37682859) and [GNU Coding Standards](https://www.gnu.org/prep/standards/standards.html#Command_002dLine-Interfaces) seem to agree on this as well, so we'll look to change this soon. Perhaps whoever takes this on might address #4774 at the same time.

**Comment by zmajeed** [comment]
PR 4907 is in for this issue and #4774
