### ISSUE TITLE
Expressing non-numeric float values

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#491]
The Go implementation of floating point used by zq (https://golang.org/pkg/math/) includes the concepts of +/- Infinity and NaN. Since ZNG uses this for its underlying storage, it's technically feasible for these non-numeric values to be written/read as ZNG today. However, due to lack of full support all the way into the upper layers of the Zed language, the following gaps remain:

* There are no float literals in the Zed language that match the underlying Go constructs (i.e. no way for a user to check if a field contains one of these non-numeric values).
* There's no conventions in ZSON for presenting these values. (i.e. no way for data to take a "round trip" from binary ZNG to ZSON presentation and then back to being stored as binary ZNG again).

**Comment by mccanne** [comment]
@nwt this is done right?

**Comment by mccanne** [comment]
This has been done...
```
% echo '+Inf -Inf NaN' | zq "yield typeof(this)" -
(float64)
(float64)
(float64)
```
