### ISSUE TITLE
support regexps in zql expressions

### ISSUE THREAD

**Issue by aswan** [brimdata/zed#619]
zql expressions currently use zngnative values which use the zng type system, which does not have a regular expression type.  As a result, an expression like `s =~ /regexp/` currently parses but if you try to compile it, it results in the error `unsupported type regexp in ast.Literal`
Figure out a way to support these (e.g., an "internal" type id that isn't valid in (t)zng data)

**Comment by philrz** [comment]
Testing with current Zed commit 4f67f3e verifies that this has been addressed.

Revisiting an older Zed commit to remind ourselves what was mentioned at https://github.com/brimdata/zed/issues/534#issuecomment-622589440 as still undone to be tracked in this issue:

```
$ zq -version
Version: v0.12.0-29-gd4cba020

$ zq -t 'method=TRACE OR method=CONNECT | cut method | put isTrace = method=~/TRACE/' http.log.gz 
unsupported type regexp in ast.Literal
```

Bringing the Zed language syntax current, we can see that in current Zed commit 4f67f3ee, we can now use regexps in this expression.

```
$ zq -version
Version: v0.12.0-29-gd4cba020

$ zq -f tzng 'method=="TRACE" OR method=="CONNECT" | cut method | put isTrace := method matches /^TRACE$/' http.log.gz 
#0:record[method:bstring,isTrace:bool]
0:[CONNECT;F;]
0:[TRACE;T;]
0:[CONNECT;F;]
...
```
