### ISSUE TITLE
Add /search tests with non-zng formats

### ISSUE THREAD

**Issue by henridf** [brimdata/zed#744]
All of the /search endpoint tests in `zqd/handlers_tests.go` use the zng format (via the `format=zng` query param that the go api client defaults to). We should add at least one search test using `format=zjson`, seeing as that is the format requested by Brim.

**Comment by philrz** [comment]
@nwt commented during an old issue scrub:

> We have `service/ztests/curl-query-json.yaml` and `service/ztests/curl-query-zjson.yaml` . Makes sense to add tests for the other supported formats, though.
