### ISSUE TITLE
Match on "time" value sometimes failing

### ISSUE THREAD

**Issue by philrz** [brimdata/zed#789]
Repro is with `zq` commit `cc989d2`.

Notice how the query only matches one record:

```
$ zq -t input.zng 
#0:record[ts:time,uid:bstring]
0:[1428779281.268858;CdQGby3rZAhOnx7p57;]
0:[1428779881.908318;ClCg3I3CdZ8hyPjAP;]

$ zq -t "ts=1428779281.268858 OR ts=1428779881.908318" input.zng 
#0:record[ts:time,uid:bstring]
0:[1428779881.908318;ClCg3I3CdZ8hyPjAP;]
```

**Comment by aswan** [comment]
The right-hand side of the timestamp comparison is a floating point number that is then cast to a timestamp, and we've got a floating point precision issue there:
https://play.golang.org/p/2BRLKvcBxXS

**Comment by philrz** [comment]
We had a group discussion yesterday about how to approach this issue, and it spawned a few different ideas. There's now an Epic https://github.com/brimsec/brim/issues/799 to cover them all.

While the other two issues linked to that Epic represent the cleanest fix, _this_ issue can live on to deal with the likelihood that users might still type the shorthand with float literal such as `ts=1428779281.268858`. We agreed that in this case we should return whatever matches we get, but also have the backend issue a warning along the lines of "Comparison between a floating point literal and `time` value may not produce exact matches. Use a time conversion function instead." (And replace the reference to "time conversion function" with the syntax for the specific functions we settle on in https://github.com/brimsec/zq/issues/808. If this is all deemed a little too complex to cram into an error message we could also write a wiki article and link to that.)

**Comment by philrz** [comment]
Per the [ZSON spec](2015-04-11T19:18:01.908318Z), things have changed such that `time` values are now internally stored as "signed 64-bit nanoseconds from epoch", which means the vulnerability to the floating point problems shown above is now gone. To up-level the original repro to show there's no precision problems confirming equality of these specific time values, testing with current Zed syntax at commit 4f67f3e:

```
$ zq -version
Version: v0.30.0-7-g4f67f3ee

$ cat input.tzng 
#0:record[ts:time,uid:bstring]
0:[1428779281.268858;CdQGby3rZAhOnx7p57;]
0:[1428779881.908318;ClCg3I3CdZ8hyPjAP;]

$ zq input.tzng 
{ts:2015-04-11T19:08:01.268858Z,uid:"CdQGby3rZAhOnx7p57"(bstring)}
{ts:2015-04-11T19:18:01.908318Z,uid:"ClCg3I3CdZ8hyPjAP"(bstring)}

$ zq -z 'ts==2015-04-11T19:08:01.268858Z OR ts==2015-04-11T19:18:01.908318Z' input.tzng 
{ts:2015-04-11T19:08:01.268858Z,uid:"CdQGby3rZAhOnx7p57"(bstring)}
{ts:2015-04-11T19:18:01.908318Z,uid:"ClCg3I3CdZ8hyPjAP"(bstring)}
```

Therefore I'm closing this one as no longer relevant.
