### ISSUE TITLE
Define semantics of expressions with unset values

### ISSUE THREAD

**Issue by henridf** [brimdata/zed#850]
[This issue was filed by @aswan in our previous issue tracking system.]

At the moment, any expression that references a field that holds the zeek/zng unset value fails to evaluate.  This is probably okay in many cases but there will certainly be cases where we don't want that (e.g., a filter field != null shouldn't fail if the field is unset!)
At the very least, we need to define the semantics for every element of the expression syntax and how it handles an unset value.  How to make this ergonomic for users is a trickier question and will probably result in additional language syntax...

**Comment by philrz** [comment]
I think the issue #2066 I just filed is a specific instance of this.

**Comment by mccanne** [comment]
Unset is now completely gone.  Null values take the place of unset.
