### ISSUE TITLE
Define semantics of zql expressions with aliases

### ISSUE THREAD

**Issue by henridf** [brimdata/zed#851]
At the moment, zql expressions convert aliases to their underlying types before processing, and don't attempt to "restore" aliases in the results. However, given our design goal of supporting aliases throughout zng and zql, we need to decide the semantics of expressions on aliased types, and implement that.

As an example of this to-be-specified behavior, consider
```
#myint=uint64
#0:record[i:myint,j:uint64]
```
the type of `i + i` should presumably be `myint`. How about `i + j` and `i + 4`? 

similar questions arise with the use of functions.

**Comment by henridf** [comment]
Also, given 
```
#0:record[i:myint,j:uint64]
0:[1;1;]
```

does `filter i=j` evaluate to true on this record?

**Comment by henridf** [comment]
Also, given 

```
#ipaddr=ip
#0:record[addr:ip]
0:[1.1.1.1;]
#1:record[addr:ipaddr]
0:[1.1.1.1;]
```

does `count() by ip` result in one or two groups?

**Comment by henridf** [comment]
One solution would be to say that as soon as a record field is operated on, any aliased types contained in that field are reduced down to their underlying "concrete" type. 

This would go with  high-level idea that aliases are part of zng rather than zql; however zql preserves them when doing non-destructive record manipulation. (cut, rename, tail, head, sort, ..).  Expressions and other places that compare and/or create new values would not preserve aliases. 

Going back to the above examples:

- `i+i`, `i+j`, and `i+4` would all be `uint64`
- `count() by addr` results in one group
- `filter i=j` evaluates to true on that record


Open question:
- does `put a=b` preserve an alias type in b? probably it should.
- does `rename a=b` preserve an alias? probably likewise

**Comment by mccanne** [comment]
This is still problematic...
```
% cat in.zson
{addr:1.1.1.1}
{addr:1.1.1.1(ipaddr=(ip))}
% zq "count() by addr" in.zson
{addr:1.1.1.1,count:1(uint64)}
{addr:1.1.1.1(=ipaddr),count:1(uint64)}
% zq "count() by addr:=ip(addr)" in.zson
{addr:1.1.1.1,count:1(uint64)}
{addr:1.1.1.1(=ipaddr),count:1(uint64)}
% zq " yield ip(addr)" in.zson
1.1.1.1
1.1.1.1(=ipaddr)
```

**Comment by mccanne** [comment]
No longer relevant / done.
