### ISSUE TITLE
Support union types in expressions

### ISSUE THREAD

**Issue by henridf** [brimdata/zed#857]
zql expressions currently don't support union types. They presumably will need to at some point.

**Comment by mccanne** [comment]
This is partially implemented, e.g., the dot operator properly pulls union-tagged values out of the union wrapper.  We need to audit the expr package, create tests, and make sure we do this everywhere necessary.  It is especially relevant as shaping and JSON ingest of mixed type arrays can create copious type unions.

**Comment by mattnibs** [comment]
To the best of my knowledge this has been completed. Closing.
