### ISSUE TITLE
zapi and zqd should support unix sockets

### ISSUE THREAD

**Issue by alfred-landrum** [brimdata/zed#862]
We'd like to write script-style tests that have a per-test zqd instance, and then interact with it via zapi. However, with the current capabilities, we'd need to handle port rendezvous as well; just using our default port of 9867 will likely interfere with a dev running zqd/Brim on their machine.

We could get around this by supporting unix sockets. We can alter zapi to take a url for a server location, and it should handle urls in the form of `unix:///a/b/c/foo.sock` . zqd would then need to be able to listen & accept connections from a specified socket file.

FYI that resty (the http library we use), supports unix sockets:
https://github.com/go-resty/resty#unix-socket

**Comment by mccanne** [comment]
There are better ways to handle port collision.
