### ISSUE TITLE
zar index cli ux: omitting -z yields different negative experiences

### ISSUE THREAD

**Issue by mikesbrown** [brimdata/zed#865]
_This is a bug first mentioned in a team conversation. I first thought it was a more serious zar-on-Windows bug, but after further investigation, it's a minor CLI bug. I filed this because it was previously discussed, but I feel like what's more needed--and acknowledged in the past--is a zar CLI UX polish._

Given `zar` version `Version: v0.14.0-9-g802a3bd`, when trying to create a zql-custom index and mistyping the command, the behavior on mac and windows differs, and both are negative. 

For starters, note I wasn't using `zar index` properly. This is the correct command:
```
zar index -k _path -o countbypath -z "* | count() by _path | sort _path"
```
As best I can tell this works on both mac and windows.

My mistake is that specifying Zql with `zar index` differs from `zq` or `zar zq` in that `-z` is needed, but I dropped that. This to `-z` or not to `-z` difference is one of the things that could be improved in a general zar CLI UX polish.

So this is the command I *actually* ran, and the command that makes this bug:
```
zar index -k _path -o countbypath  "* | count() by _path | sort _path"
```
### Mac
On Mac, this is an accepted command, but it yields a bogus index.
```
$ zar index -k _path -o countbypath "* | count() by _path | sort _path"
/Users/mikeb/git/brim/zar/20200225/1582646597.838527.zng: creating index /Users/mikeb/git/brim/zar/20200225/1582646597.838527.zng.zar/zdx-field-* | count() by _path | sort _path
/Users/mikeb/git/brim/zar/20200225/1582646594.050187.zng: creating index /Users/mikeb/git/brim/zar/20200225/1582646594.050187.zng.zar/zdx-field-* | count() by _path | sort _path
/Users/mikeb/git/brim/zar/20200225/1582646593.978298.zng: creating index /Users/mikeb/git/brim/zar/20200225/1582646593.978298.zng.zar/zdx-field-* | count() by _path | sort _path
/Users/mikeb/git/brim/zar/20200225/1582646587.715839.zng: creating index /Users/mikeb/git/brim/zar/20200225/1582646587.715839.zng.zar/zdx-field-* | count() by _path | sort _path
$
```
They're bogus in the sense that:
1. `-o` was ignored.
1. The zql preferred became part of the filename, but the file name has dropped the intended `-o` token.
1. The indices are completely empty, even of metadata.
```
$ find zar/*/*.zng.zar -type f -print -exec zq -t {} \;
zar/20200225/1582646587.715839.zng.zar/zdx-field-* | count() by _path | sort _path.zng
zar/20200225/1582646593.978298.zng.zar/zdx-field-* | count() by _path | sort _path.zng
zar/20200225/1582646594.050187.zng.zar/zdx-field-* | count() by _path | sort _path.zng
zar/20200225/1582646597.838527.zng.zar/zdx-field-* | count() by _path | sort _path.zng
$
```
### Windows
With Windows, there's a recognized, but unhelpful error:
```
$ ./dist/zar index -k _path -o countbypath "* | count() by _path | sort _path"
The filename, directory name, or volume label syntax is incorrect.
```
This is a generic Windows error message and there's no helpful context as to what went wrong. In fact, I was doing this first, not realizing missing `-z` was a problem, and thought there was an even deeper `zar`-on-Windows bug.

**Comment by philrz** [comment]
Since we've been changing `zar` code a lot lately, I checked in on this as of commit `56ed80d`. While some of the optics have changed, the ignore of `-o` seems to still be with us, as microindex file names were still created based on the intended ZQL. This was after having imported the wrccdc "year1" data set.

```
$ tree -s logs | head -10
logs
├── [         88]  zar.json
└── [        160]  zd
    ├── [       8224]  20170324
    │   ├── [   25002326]  d-1iKR9BM0iSIMk29Yr1L5blsG5SP.zng
    │   ├── [         96]  d-1iKR9BM0iSIMk29Yr1L5blsG5SP.zng.zar
    │   │   └── [         93]  microindex-field-*\ |\ count()\ by\ _path\ |\ sort\ _path.zng
...
```

The microindex files _do_ have contents now, however.

```
$ zq -t logs/zd/20170324/d-1iKR9BM0iSIMk29Yr1L5blsG5SP.zng.zar/microindex-field-\*\ \|\ count\(\)\ by\ _path\ \|\ sort\ _path.zng 
#0:record[magic:string,version:int32,child_field:string,frame_thresh:int32,sections:array[int64],keys:record[key:null]]
0:[microindex;1;;65536;-;-;]
```

**Comment by alfred-landrum** [comment]
I can address this during the work for #1265 .

**Comment by mccanne** [comment]
zed lake deprecates this
