### ISSUE TITLE
zql: add support for type-aware sorting of records

### ISSUE THREAD

**Issue by henridf** [brimdata/zed#868]
Currently, our sorting helpers fall back to raw byte comparison when comparing records. 

See https://github.com/brimsec/zq/blob/802a3bdce8a3c5bcef01b5ca315563353113c5ae/expr/sort.go#L210 and the "XXX" comment towards the top of this function.

I ran into this while writing corner-case unit tests for streaming groupby. It is probably not an urgent priority.

**Comment by philrz** [comment]
@alfred-landrum & @mccanne note:
>`zar index`, group-by, and sort should all use the same zng.record sorting machinery.

**Comment by henridf** [comment]
group-by and sort already do. Not sure about zar index, and also not sure if this comment deserves its own issue?

**Comment by mccanne** [comment]
This was done a while ago...
