### ISSUE TITLE
python zq integration prototype

### ISSUE THREAD

**Issue by alfred-landrum** [brimdata/zed#888]
We'd like to produce a prototype quality Python module that supports some zq operations directly, ie, not by exec'ing `zq`, but via making Python calls. This would be implemented by packaging the zq Go based machinery via Go's c-shared buildmode option, then using some form of FFI between Python and Go.

It should be compatible with Python 3.7 or later, and should be installable via the usual `pip install`. We should use the manylinux process documented here:
https://github.com/pypa/manylinux
to produce a Python wheel for easy distribution.

**Comment by nwt** [comment]
This was implemented in #891 and #911 and then removed in #3096.
