### ISSUE TITLE
zqd package reorg

### ISSUE THREAD

**Issue by alfred-landrum** [brimdata/zed#965]
I think the organization of code & packages under the zqd directory could be improved with a changed layout, including changes like:

- create a new directory & package, zqd/handler, move most of zqd/*.go there, except core.go
- create package zqd/client from zqd/api/{connection.go, jsonpipescanner.go, stream.go, search.go, zng.go} 
- create package zqd/pcap from zqd/ingest/pcap.go, zqd/search/pcapsearch.go
- create package zqd/logs from zqd/ingest/log.go, zqd/search/search.go

**Comment by mccanne** [comment]
no longer relevant
