### ISSUE TITLE
zar import ux: accept glob

### ISSUE THREAD

**Issue by mikesbrown** [brimdata/zed#976]
Most of our CLI tools accept a glob, but `zar import` does not:
```
$ zar import *.log
zar import: exactly one input file must be specified (- for stdin)
```
It would be convenient to be able to specify glob. If that's not desired and pipelines with `zq` are preferred, the message could be changed to suggest `zq`. And along those lines, the workaround to this problem is:
```
$ zq '*' *.log | zar import -
```
This is filed assuming `zar` is going to become a first-class citizen.

**Comment by mccanne** [comment]
no longer relevant
