### ISSUE TITLE
zar import ux: bring over relevant zq options 

### ISSUE THREAD

**Issue by mikesbrown** [brimdata/zed#977]
When importing JSON into zar, I need to point to a schema file and also use -e, because I have some ts-less points sprinkled in my logs. The mechanism to do this has to be:

`zq -e=false -j schema.json '*' json_streaming_*.log.gz | zar import -`

If we want to make `zar` a first class citizen, using a pipeline with zq feels clunky. It seems like options like this should be available in zar directly so I don't have to use a pipeline.

**Comment by philrz** [comment]
I can verify that starting with `zar` commit `ca0ef53` (associated with #1249) the `-j` option is now present.

```
$ zar help import
...
OPTIONS
...
    -j path to json types file
...
```

However `-e` still is not, so, holding this one open.

**Comment by mccanne** [comment]
No longer relevant
