### ISSUE TITLE
ts-less records like those from Zeek's loaded scripts skew chunk stats

### ISSUE THREAD

**Issue by mikesbrown** [brimdata/zed#988]
ts-less Zeek logs like loaded_scripts can end up in a zar chunk such that the zar stats for that chunk start at ts=0 and have large offsets. For `zar stat` alone this might not be a problem, but for Brim it has the potential to create unsightly visualizations and confuse users looking at certain time windows. This last is most important: if I as a user know what time window I want, and some chunks are decades long and include my time window, I have to search those chunks.

We should handle ts-less records like this in the product as it's quite likely users will ingest some ts-less records, from loaded_scripts or elsewhere.

This is a snippet of chunks sorted by LOG_ID, which looks like a time representation. But in some chunks the start_ts is 0 and the duration is much longer:
```
TYPE  LOG_ID                         START             DURATION             SIZE
chunk 20190216/1550361599.526835.zng 1550346837.559955 14761.966880001      15605522
chunk 20190217/1550363502.539091.zng 1550359033.092012 4469.447079001       11656757
chunk 20190217/1550381312.215436.zng 0.000000          1550381312.215436001 8940346
chunk 20190301/1551459598.30676.zng  0.000000          1551459598.306760001 160450508
chunk 20190301/1551463199.842722.zng 1551458088.922101 5110.920621001       100067234
chunk 20190301/1551466799.91244.zng  1551458088.522204 8711.390236001       158699875
chunk 20190301/1551468669.138597.zng 1551458089.039000 10580.099597001      79103831
chunk 20190302/1551549599.963612.zng 0.000000          1551549599.963612001 24860205
chunk 20190302/1551553199.951388.zng 1551547802.177688 5397.773700001       352543589
```
If we take a chunk like `20190217/1550381312.215436.zng` and examine it, we see that `min(ts)` is *not* in fact 0:
```
$ zq -t 'min(ts)' 20190217/1550381312.215436.zng
#0:record[min:time]
0:[1550343250.215459;]
```
Unfortunately I can't use `ts=null` to find what's going on:
```
$ zq -t 'ts=null' 20190217/1550381312.215436.zng
$
```
But I have a priori knowledge about this data set and know that it's loaded_scripts, e.g.:
```
$ zq -t '_path=loaded_scripts | head 1' 20190217/1550381312.215436.zng
#0:record[_path:string,name:bstring,_write_ts:time]
0:[loaded_scripts;/usr/local/zeek/share/zeek/base/init-bare.zeek;0;]
```
When I look at the full list of start_ts ts=0 chunks, they all contain loaded_scripts records.

**Comment by mccanne** [comment]
No longer relevant.
